#  Data Analysis and Reporting with Python - Guiding Notebook

## 1. Defining the Question

### a) Specifying the Data Analysis Question

Our task is to come up with schools Jane can apply to which include the following criteria:
- is in an urban/metropolitan area
- is in a city that ranks 75th percentile or higher on Kauffman's startup rankings
- be below 50th percentile in overall crime
- offer a 2-year or 4-year degree in Information Technology/Science

### b) Defining the Metric for Success

We will have accomplished our objective if we get at least one school matching all the above-mentioned criteria.

### c) Understanding the Context

While applying for university, foreign student populations could greatly benefit from data and resources to support their wellbeing and success. Such students and families often lack information that is necessary to distinguish between their school options, access
services, and identify affordable housing near the high-quality school and in safe neighbourhoods that have access to transit and employment.

Jane is a 20-year-old high school graduate from Nigeria. She has recently completed her high school education and has decided to pursue a degree in Management Systems and Information Technology in the United States.

She has approached your university recruiting agency and has tasked you to help her search for the best school for her. She is willing to relocate anywhere in the continental United States, but she has a few criteria that her ideal schools must satisfy:
- safety (low crime)
- urban : Jane wants to live the big city life
- start-ups : the schol should be in a metropolitan area that ranks highly in entrepreneurialism (she plans to find an internship at a startup while she studies.

### d) Recording the Experimental Design

1. Load libraries and datasets.
2. Select the most appropriate variables to work with.
3. Find and deal with duplicated data.
4. Find and deal with missing values.
5. Drop data that does not match criteria, e.g., schools with "distance only" programs.
6. Merge the dataframe on crimes to the dataframe with the college data based on location (city and state).
7. Filter and select the schools with total crime rate below the 50th percentile.
8. Filter and select the schools found only in Metropolitan State Areas.
9. Filter and search for schools located in the 75th percentile or higher on the Kauffman Start-Up Index.
10. Filter and select the schools that offer a 2-year or 4-year degree in Information Technology/Science.

### e) Data Relevance

The given data sets were relevant in answering the research question.

## 2. Data Cleaning & Analysis

In [1]:
# Loading the required libraries

# Loading pandas
import pandas as pd

# Loading numpy
import numpy as np


# To preview all rows and columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
# Connecting to Google drive to access data
# We now load our dataset files to colab
# There are many ways to do this...
# You can use your method or alternatively do the 
# following if you have your files in google drive.
# ---
#

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Setting the data access locations in Google drive

# Setting our college scorecard dataset url
data_set_url = '/content/drive/My Drive/Datascience/exercises-data-wrangling-exercise-1/CollegeScorecard.csv'

# Setting our college scorecard dictionary url
college_score_card_dictionary_url = '/content/drive/My Drive/Datascience/exercises-data-wrangling-exercise-1/CollegeScorecardDataDictionary-09-12-2015.csv'

# Setting our crime dataset url
crime_2015_url = '/content/drive/My Drive/Datascience/exercises-data-wrangling-exercise-1/Crime_2015.csv'

# Setting our startup dataset url
kauffman_startup_index_url = '/content/drive/My Drive/Datascience/exercises-data-wrangling-exercise-1/KaufmanIndexData/2017_Startup_Index_final.csv'

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
# Loading our college scorecard dataset
df = pd.read_csv(data_set_url)


# Loading our college scorecard dictionary
df_college_score_card_dictionary = pd.read_csv(college_score_card_dictionary_url)



# Loading our crime dataset
df_crime_2015 = pd.read_csv(crime_2015_url, thousands=",")


# Loading our startup dataset
df_kauffman_startup_index = pd.read_csv(kauffman_startup_index_url)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7,9,1427,1542,1561,1575,1725,1726,1727,1728) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
# Previewing the first 5 records for the CollegeScorecard

df.head()

,UNITID,OPEID,opeid6,INSTNM,CITY,STABBR,ZIP,AccredAgency,INSTURL,NPCURL,sch_deg,HCM2,main,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,st_fips,region,LOCALE,locale2,LATITUDE,LONGITUDE,CCBASIC,CCUGPROF,CCSIZSET,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,MENONLY,WOMENONLY,RELAFFIL,ADM_RATE,ADM_RATE_ALL,SATVR25,SATVR75,SATMT25,SATMT75,SATWR25,SATWR75,SATVRMID,SATMTMID,SATWRMID,ACTCM25,ACTCM75,ACTEN25,ACTEN75,ACTMT25,ACTMT75,ACTWR25,ACTWR75,ACTCMMID,ACTENMID,ACTMTMID,ACTWRMID,SAT_AVG,SAT_AVG_ALL,PCIP01,PCIP03,PCIP04,PCIP05,PCIP09,PCIP10,PCIP11,PCIP12,PCIP13,PCIP14,PCIP15,PCIP16,PCIP19,PCIP22,PCIP23,PCIP24,PCIP25,PCIP26,PCIP27,PCIP29,PCIP30,PCIP31,PCIP38,PCIP39,PCIP40,PCIP41,PCIP42,PCIP43,PCIP44,PCIP45,PCIP46,PCIP47,PCIP48,PCIP49,PCIP50,PCIP51,PCIP52,PCIP54,CIP01CERT1,CIP01CERT2,CIP01ASSOC,CIP01CERT4,CIP01BACHL,CIP03CERT1,CIP03CERT2,CIP03ASSOC,CIP03CERT4,CIP03BACHL,CIP04CERT1,CIP04CERT2,CIP04ASSOC,CIP04CERT4,CIP04BACHL,CIP05CERT1,CIP05CERT2,CIP05ASSOC,CIP05CERT4,CIP05BACHL,CIP09CERT1,CIP09CERT2,CIP09ASSOC,CIP09CERT4,CIP09BACHL,CIP10CERT1,CIP10CERT2,CIP10ASSOC,CIP10CERT4,CIP10BACHL,CIP11CERT1,CIP11CERT2,CIP11ASSOC,CIP11CERT4,CIP11BACHL,CIP12CERT1,CIP12CERT2,CIP12ASSOC,CIP12CERT4,CIP12BACHL,CIP13CERT1,CIP13CERT2,CIP13ASSOC,CIP13CERT4,CIP13BACHL,CIP14CERT1,CIP14CERT2,CIP14ASSOC,CIP14CERT4,CIP14BACHL,CIP15CERT1,CIP15CERT2,CIP15ASSOC,CIP15CERT4,CIP15BACHL,CIP16CERT1,CIP16CERT2,CIP16ASSOC,CIP16CERT4,CIP16BACHL,CIP19CERT1,CIP19CERT2,CIP19ASSOC,CIP19CERT4,CIP19BACHL,CIP22CERT1,CIP22CERT2,CIP22ASSOC,CIP22CERT4,CIP22BACHL,CIP23CERT1,CIP23CERT2,CIP23ASSOC,CIP23CERT4,CIP23BACHL,CIP24CERT1,CIP24CERT2,CIP24ASSOC,CIP24CERT4,CIP24BACHL,CIP25CERT1,CIP25CERT2,CIP25ASSOC,CIP25CERT4,CIP25BACHL,CIP26CERT1,CIP26CERT2,CIP26ASSOC,CIP26CERT4,CIP26BACHL,CIP27CERT1,CIP27CERT2,CIP27ASSOC,CIP27CERT4,CIP27BACHL,CIP29CERT1,CIP29CERT2,CIP29ASSOC,CIP29CERT4,CIP29BACHL,CIP30CERT1,CIP30CERT2,CIP30ASSOC,CIP30CERT4,CIP30BACHL,CIP31CERT1,CIP31CERT2,CIP31ASSOC,CIP31CERT4,CIP31BACHL,CIP38CERT1,CIP38CERT2,CIP38ASSOC,CIP38CERT4,CIP38BACHL,CIP39CERT1,CIP39CERT2,CIP39ASSOC,CIP39CERT4,CIP39BACHL,CIP40CERT1,CIP40CERT2,CIP40ASSOC,CIP40CERT4,CIP40BACHL,CIP41CERT1,CIP41CERT2,CIP41ASSOC,CIP41CERT4,CIP41BACHL,CIP42CERT1,CIP42CERT2,CIP42ASSOC,CIP42CERT4,CIP42BACHL,CIP43CERT1,CIP43CERT2,CIP43ASSOC,CIP43CERT4,CIP43BACHL,CIP44CERT1,CIP44CERT2,CIP44ASSOC,CIP44CERT4,CIP44BACHL,CIP45CERT1,CIP45CERT2,CIP45ASSOC,CIP45CERT4,CIP45BACHL,CIP46CERT1,CIP46CERT2,CIP46ASSOC,CIP46CERT4,CIP46BACHL,CIP47CERT1,CIP47CERT2,CIP47ASSOC,CIP47CERT4,CIP47BACHL,CIP48CERT1,CIP48CERT2,CIP48ASSOC,CIP48CERT4,CIP48BACHL,CIP49CERT1,CIP49CERT2,CIP49ASSOC,CIP49CERT4,CIP49BACHL,CIP50CERT1,CIP50CERT2,CIP50ASSOC,CIP50CERT4,CIP50BACHL,CIP51CERT1,CIP51CERT2,CIP51ASSOC,CIP51CERT4,CIP51BACHL,CIP52CERT1,CIP52CERT2,CIP52ASSOC,CIP52CERT4,CIP52BACHL,CIP54CERT1,CIP54CERT2,CIP54ASSOC,CIP54CERT4,CIP54BACHL,DISTANCEONLY,UGDS,UG,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,UGDS_WHITENH,UGDS_BLACKNH,UGDS_API,UGDS_AIANOld,UGDS_HISPOld,UG_NRA,UG_UNKN,UG_WHITENH,UG_BLACKNH,UG_API,UG_AIANOld,UG_HISPOld,PPTUG_EF,PPTUG_EF2,CURROPER,NPT4_PUB,NPT4_PRIV,NPT4_PROG,NPT4_OTHER,NPT41_PUB,NPT42_PUB,NPT43_PUB,NPT44_PUB,NPT45_PUB,NPT41_PRIV,NPT42_PRIV,NPT43_PRIV,NPT44_PRIV,NPT45_PRIV,NPT41_PROG,NPT42_PROG,NPT43_PROG,NPT44_PROG,NPT45_PROG,NPT41_OTHER,NPT42_OTHER,NPT43_OTHER,NPT44_OTHER,NPT45_OTHER,NPT4_048_PUB,NPT4_048_PRIV,NPT4_048_PROG,NPT4_048_OTHER,NPT4_3075_PUB,NPT4_3075_PRIV,NPT4_75UP_PUB,NPT4_75UP_PRIV,NPT4_3075_PROG,NPT4_3075_OTHER,NPT4_75UP_PROG,NPT4_75UP_OTHER,NUM4_PUB,NUM4_PRIV,NUM4_PROG,NUM4_OTHER,NUM41_PUB,NUM42_PUB,NUM43_PUB,NUM44_PUB,NUM45_PUB,NUM41_PRIV,NUM42_PRIV,NUM43_PRIV,NUM44_PRIV,NUM45_PRIV,NUM41_PROG,NUM42_PROG,NUM43_PROG,NUM44_PROG,NUM45_PROG,NUM41_OTHER,NUM42_OTHER,NUM43_OTHER,NUM44_OTHER,NUM45_OTHER,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,TUITFTE,INEXPFTE,AVGFACSAL,PFTFAC,PCTPELL,C150_4,C150_L4,C150_4_POOLED,C150_L4_POOLED,poolyrs,PFTFTUG1_EF,D150_4,D150_L4,D150_4_POOLED,D150_L4_POOLED,C150_4_WHITE,C150_4_BLACK,C150_4_HISP,C150_4_ASIAN,C150_4_AIAN,C150_4_NHPI,C150_4_2MOR,C150_4_NRA,C150_4_UNKN,C150_4_WHITENH,C150_4_BLACKNH,C150_4_API,C150_4_AIANOld,C150_4_HISPOld,C150_L4_WHITE,C150_L4_BLACK,C150_L4_HISP,C150_L4_ASIAN,C150_L4_AIAN,C150_L4_NHPI,C150_L4_2MOR,C150_L4_NRA,C150_L4_UNKN,C150_L4_WHITENH,C150_L4_BLACKNH,C150_L4_API,C150_L4_AIANOld,C150_L4_HISPOld,C200_4,C200_L4,D200_4,D200_L4,RET_FT4,RET_FTL4,RET_PT4,RET_PTL4,C200_4_POOLED,C200_L4_POOLED,poolyrs200,D200_4_POOLED,D200_L4_POOLED,PCTFLOAN,UG25abv,CDR2,CDR3,DEATH_YR2_RT,COMP_ORIG_YR2_RT,COMP_4YR_TRANS_YR2_RT,COMP_2YR_TRANS_YR2_RT,WDRAW_ORIG_YR2_RT,WDRAW_4YR_TRANS_YR2_RT,WDRAW_2YR_TRANS_YR2_RT,ENRL_ORIG_YR2_RT,ENRL_4YR_TRANS_YR2_RT,ENRL_2YR_TRANS_YR2_RT,UNKN_ORIG_YR2_RT,UNKN_4YR_TRANS_YR2_RT,UNKN_2YR_TRANS_YR2_RT,LO_INC_DEATH_YR2_RT,LO_INC_COMP_ORIG_YR2_RT,LO_INC_COMP_4YR_TRANS_YR2_RT,LO_INC_COMP_2YR_TRANS_YR2_RT,LO_INC_WDRAW_ORIG_YR2_RT,LO_INC_WDRAW_4YR_TRANS_YR2_RT,LO_INC_WDRAW_2YR_TRANS_YR2_RT,LO_INC_ENRL_ORIG_YR2_RT,LO_INC_ENRL_4YR_TRANS_YR2_RT,LO_INC_ENRL_2YR_TRANS_YR2_RT,LO_INC_UNKN_ORIG_YR2_RT,LO_INC_UNKN_4YR_TRANS_YR2_RT,LO_INC_UNKN_2YR_TRANS_YR2_RT,MD_INC_DEATH_YR2_RT,MD_INC_COMP_ORIG_YR2_RT,MD_INC_COMP_4YR_TRANS_YR2_RT,MD_INC_COMP_2YR_TRANS_YR2_RT,MD_INC_WDRAW_ORIG_YR2_RT,MD_INC_WDRAW_4YR_TRANS_YR2_RT,MD_INC_WDRAW_2YR_TRANS_YR2_RT,MD_INC_ENRL_ORIG_YR2_RT,MD_INC_ENRL_4YR_TRANS_YR2_RT,MD_INC_ENRL_2YR_TRANS_YR2_RT,MD_INC_UNKN_ORIG_YR2_RT,MD_INC_UNKN_4YR_TRANS_YR2_RT,MD_INC_UNKN_2YR_TRANS_YR2_RT,HI_INC_DEATH_YR2_RT,HI_INC_COMP_ORIG_YR2_RT,HI_INC_COMP_4YR_TRANS_YR2_RT,HI_INC_COMP_2YR_TRANS_YR2_RT,HI_INC_WDRAW_ORIG_YR2_RT,HI_INC_WDRAW_4YR_TRANS_YR2_RT,HI_INC_WDRAW_2YR_TRANS_YR2_RT,HI_INC_ENRL_ORIG_YR2_RT,HI_INC_ENRL_4YR_TRANS_YR2_RT,HI_INC_ENRL_2YR_TRANS_YR2_RT,HI_INC_UNKN_ORIG_YR2_RT,HI_INC_UNKN_4YR_TRANS_YR2_RT,HI_INC_UNKN_2YR_TRANS_YR2_RT,DEP_DEATH_YR2_RT,DEP_COMP_ORIG_YR2_RT,DEP_COMP_4YR_TRANS_YR2_RT,DEP_COMP_2YR_TRANS_YR2_RT,DEP_WDRAW_ORIG_YR2_RT,DEP_WDRAW_4YR_TRANS_YR2_RT,DEP_WDRAW_2YR_TRANS_YR2_RT,DEP_ENRL_ORIG_YR2_RT,DEP_ENRL_4YR_TRANS_YR2_RT,DEP_ENRL_2YR_TRANS_YR2_RT,DEP_UNKN_ORIG_YR2_RT,DEP_UNKN_4YR_TRANS_YR2_RT,DEP_UNKN_2YR_TRANS_YR2_RT,IND_DEATH_YR2_RT,IND_COMP_ORIG_YR2_RT,IND_COMP_4YR_TRANS_YR2_RT,IND_COMP_2YR_TRANS_YR2_RT,IND_WDRAW_ORIG_YR2_RT,IND_WDRAW_4YR_TRANS_YR2_RT,IND_WDRAW_2YR_TRANS_YR2_RT,IND_ENRL_ORIG_YR2_RT,IND_ENRL_4YR_TRANS_YR2_RT,IND_ENRL_2YR_TRANS_YR2_RT,IND_UNKN_ORIG_YR2_RT,IND_UNKN_4YR_TRANS_YR2_RT,IND_UNKN_2YR_TRANS_YR2_RT,FEMALE_DEATH_YR2_RT,FEMALE_COMP_ORIG_YR2_RT,FEMALE_COMP_4YR_TRANS_YR2_RT,FEMALE_COMP_2YR_TRANS_YR2_RT,FEMALE_WDRAW_ORIG_YR2_RT,FEMALE_WDRAW_4YR_TRANS_YR2_RT,FEMALE_WDRAW_2YR_TRANS_YR2_RT,FEMALE_ENRL_ORIG_YR2_RT,FEMALE_ENRL_4YR_TRANS_YR2_RT,FEMALE_ENRL_2YR_TRANS_YR2_RT,FEMALE_UNKN_ORIG_YR2_RT,FEMALE_UNKN_4YR_TRANS_YR2_RT,FEMALE_UNKN_2YR_TRANS_YR2_RT,MALE_DEATH_YR2_RT,MALE_COMP_ORIG_YR2_RT,MALE_COMP_4YR_TRANS_YR2_RT,MALE_COMP_2YR_TRANS_YR2_RT,MALE_WDRAW_ORIG_YR2_RT,MALE_WDRAW_4YR_TRANS_YR2_RT,MALE_WDRAW_2YR_TRANS_YR2_RT,MALE_ENRL_ORIG_YR2_RT,MALE_ENRL_4YR_TRANS_YR2_RT,MALE_ENRL_2YR_TRANS_YR2_RT,MALE_UNKN_ORIG_YR2_RT,MALE_UNKN_4YR_TRANS_YR2_RT,MALE_UNKN_2YR_TRANS_YR2_RT,PELL_DEATH_YR2_RT,PELL_COMP_ORIG_YR2_RT,PELL_COMP_4YR_TRANS_YR2_RT,PELL_COMP_2YR_TRANS_YR2_RT,PELL_WDRAW_ORIG_YR2_RT,PELL_WDRAW_4YR_TRANS_YR2_RT,PELL_WDRAW_2YR_TRANS_YR2_RT,PELL_ENRL_ORIG_YR2_RT,PELL_ENRL_4YR_TRANS_YR2_RT,PELL_ENRL_2YR_TRANS_YR2_RT,PELL_UNKN_ORIG_YR2_RT,PELL_UNKN_4YR_TRANS_YR2_RT,PELL_UNKN_2YR_TRANS_YR2_RT,NOPELL_DEATH_YR2_RT,NOPELL_COMP_ORIG_YR2_RT,NOPELL_COMP_4YR_TRANS_YR2_RT,NOPELL_COMP_2YR_TRANS_YR2_RT,NOPELL_WDRAW_ORIG_YR2_RT,NOPELL_WDRAW_4YR_TRANS_YR2_RT,NOPELL_WDRAW_2YR_TRANS_YR2_RT,NOPELL_ENRL_ORIG_YR2_RT,NOPELL_ENRL_4YR_TRANS_YR2_RT,NOPELL_ENRL_2YR_TRANS_YR2_RT,NOPELL_UNKN_ORIG_YR2_RT,NOPELL_UNKN_4YR_TRANS_YR2_RT,NOPELL_UNKN_2YR_TRANS_YR2_RT,LOAN_DEATH_YR2_RT,LOAN_COMP_ORIG_YR2_RT,LOAN_COMP_4YR_TRANS_YR2_RT,LOAN_COMP_2YR_TRANS_YR2_RT,LOAN_WDRAW_ORIG_YR2_RT,LOAN_WDRAW_4YR_TRANS_YR2_RT,LOAN_WDRAW_2YR_TRANS_YR2_RT,LOAN_ENRL_ORIG_YR2_RT,LOAN_ENRL_4YR_TRANS_YR2_RT,LOAN_ENRL_2YR_TRANS_YR2_RT,LOAN_UNKN_ORIG_YR2_RT,LOAN_UNKN_4YR_TRANS_YR2_RT,LOAN_UNKN_2YR_TRANS_YR2_RT,NOLOAN_DEATH_YR2_RT,NOLOAN_COMP_ORIG_YR2_RT,NOLOAN_COMP_4YR_TRANS_YR2_RT,NOLOAN_COMP_2YR_TRANS_YR2_RT,NOLOAN_WDRAW_ORIG_YR2_RT,NOLOAN_WDRAW_4YR_TRANS_YR2_RT,NOLOAN_WDRAW_2YR_TRANS_YR2_RT,NOLOAN_ENRL_ORIG_YR2_RT,NOLOAN_ENRL_4YR_TRANS_YR2_RT,NOLOAN_ENRL_2YR_TRANS_YR2_RT,NOLOAN_UNKN_ORIG_YR2_RT,NOLOAN_UNKN_4YR_TRANS_YR2_RT,NOLOAN_UNKN_2YR_TRANS_YR2_RT,FIRSTGEN_DEATH_YR2_RT,FIRSTGEN_COMP_ORIG_YR2_RT,FIRSTGEN_COMP_4YR_TRANS_YR2_RT,FIRSTGEN_COMP_2YR_TRANS_YR2_RT,FIRSTGEN_WDRAW_ORIG_YR2_RT,FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT,FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT,FIRSTGEN_ENRL_ORIG_YR2_RT,FIRSTGEN_ENRL_4YR_TRANS_YR2_RT,FIRSTGEN_ENRL_2YR_TRANS_YR2_RT,FIRSTGEN_UNKN_ORIG_YR2_RT,FIRSTGEN_UNKN_4YR_TRANS_YR2_RT,FIRSTGEN_UNKN_2YR_TRANS_YR2_RT,NOT1STGEN_DEATH_YR2_RT,NOT1STGEN_COMP_ORIG_YR2_RT,NOT1STGEN_COMP_4YR_TRANS_YR2_RT,NOT1STGEN_COMP_2YR_TRANS_YR2_RT,NOT1STGEN_WDRAW_ORIG_YR2_RT,NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT,NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT,NOT1STGEN_ENRL_ORIG_YR2_RT,NOT1STGEN_ENRL_4YR_TRANS_YR2_RT,NOT1STGEN_ENRL_2YR_TRANS_YR2_RT,NOT1STGEN_UNKN_ORIG_YR2_RT,NOT1STGEN_UNKN_4YR_TRANS_YR2_RT,NOT1STGEN_UNKN_2YR_TRANS_YR2_RT,DEATH_YR3_RT,COMP_ORIG_YR3_RT,COMP_4YR_TRANS_YR3_RT,COMP_2YR_TRANS_YR3_RT,WDRAW_ORIG_YR3_RT,WDRAW_4YR_TRANS_YR3_RT,WDRAW_2YR_TRANS_YR3_RT,ENRL_ORIG_YR3_RT,ENRL_4YR_TRANS_YR3_RT,ENRL_2YR_TRANS_YR3_RT,UNKN_ORIG_YR3_RT,UNKN_4YR_TRANS_YR3_RT,UNKN_2YR_TRANS_YR3_RT,LO_INC_DEATH_YR3_RT,LO_INC_COMP_ORIG_YR3_RT,LO_INC_COMP_4YR_TRANS_YR3_RT,LO_INC_COMP_2YR_TRANS_YR3_RT,LO_INC_WDRAW_ORIG_YR3_RT,LO_INC_WDRAW_4YR_TRANS_YR3_RT,LO_INC_WDRAW_2YR_TRANS_YR3_RT,LO_INC_ENRL_ORIG_YR3_RT,LO_INC_ENRL_4YR_TRANS_YR3_RT,LO_INC_ENRL_2YR_TRANS_YR3_RT,LO_INC_UNKN_ORIG_YR3_RT,LO_INC_UNKN_4YR_TRANS_YR3_RT,LO_INC_UNKN_2YR_TRANS_YR3_RT,MD_INC_DEATH_YR3_RT,MD_INC_COMP_ORIG_YR3_RT,MD_INC_COMP_4YR_TRANS_YR3_RT,MD_INC_COMP_2YR_TRANS_YR3_RT,MD_INC_WDRAW_ORIG_YR3_RT,MD_INC_WDRAW_4YR_TRANS_YR3_RT,MD_INC_WDRAW_2YR_TRANS_YR3_RT,MD_INC_ENRL_ORIG_YR3_RT,MD_INC_ENRL_4YR_TRANS_YR3_RT,MD_INC_ENRL_2YR_TRANS_YR3_RT,MD_INC_UNKN_ORIG_YR3_RT,MD_INC_UNKN_4YR_TRANS_YR3_RT,MD_INC_UNKN_2YR_TRANS_YR3_RT,HI_INC_DEATH_YR3_RT,HI_INC_COMP_ORIG_YR3_RT,HI_INC_COMP_4YR_TRANS_YR3_RT,HI_INC_COMP_2YR_TRANS_YR3_RT,HI_INC_WDRAW_ORIG_YR3_RT,HI_INC_WDRAW_4YR_TRANS_YR3_RT,HI_INC_WDRAW_2YR_TRANS_YR3_RT,HI_INC_ENRL_ORIG_YR3_RT,HI_INC_ENRL_4YR_TRANS_YR3_RT,HI_INC_ENRL_2YR_TRANS_YR3_RT,HI_INC_UNKN_ORIG_YR3_RT,HI_INC_UNKN_4YR_TRANS_YR3_RT,HI_INC_UNKN_2YR_TRANS_YR3_RT,DEP_DEATH_YR3_RT,DEP_COMP_ORIG_YR3_RT,DEP_COMP_4YR_TRANS_YR3_RT,DEP_COMP_2YR_TRANS_YR3_RT,DEP_WDRAW_ORIG_YR3_RT,DEP_WDRAW_4YR_TRANS_YR3_RT,DEP_WDRAW_2YR_TRANS_YR3_RT,DEP_ENRL_ORIG_YR3_RT,DEP_ENRL_4YR_TRANS_YR3_RT,DEP_ENRL_2YR_TRANS_YR3_RT,DEP_UNKN_ORIG_YR3_RT,DEP_UNKN_4YR_TRANS_YR3_RT,DEP_UNKN_2YR_TRANS_YR3_RT,IND_DEATH_YR3_RT,IND_COMP_ORIG_YR3_RT,IND_COMP_4YR_TRANS_YR3_RT,IND_COMP_2YR_TRANS_YR3_RT,IND_WDRAW_ORIG_YR3_RT,IND_WDRAW_4YR_TRANS_YR3_RT,IND_WDRAW_2YR_TRANS_YR3_RT,IND_ENRL_ORIG_YR3_RT,IND_ENRL_4YR_TRANS_YR3_RT,IND_ENRL_2YR_TRANS_YR3_RT,IND_UNKN_ORIG_YR3_RT,IND_UNKN_4YR_TRANS_YR3_RT,IND_UNKN_2YR_TRANS_YR3_RT,FEMALE_DEATH_YR3_RT,FEMALE_COMP_ORIG_YR3_RT,FEMALE_COMP_4YR_TRANS_YR3_RT,FEMALE_COMP_2YR_TRANS_YR3_RT,FEMALE_WDRAW_ORIG_YR3_RT,FEMALE_WDRAW_4YR_TRANS_YR3_RT,FEMALE_WDRAW_2YR_TRANS_YR3_RT,FEMALE_ENRL_ORIG_YR3_RT,FEMALE_ENRL_4YR_TRANS_YR3_RT,FEMALE_ENRL_2YR_TRANS_YR3_RT,FEMALE_UNKN_ORIG_YR3_RT,FEMALE_UNKN_4YR_TRANS_YR3_RT,FEMALE_UNKN_2YR_TRANS_YR3_RT,MALE_DEATH_YR3_RT,MALE_COMP_ORIG_YR3_RT,MALE_COMP_4YR_TRANS_YR3_RT,MALE_COMP_2YR_TRANS_YR3_RT,MALE_WDRAW_ORIG_YR3_RT,MALE_WDRAW_4YR_TRANS_YR3_RT,MALE_WDRAW_2YR_TRANS_YR3_RT,MALE_ENRL_ORIG_YR3_RT,MALE_ENRL_4YR_TRANS_YR3_RT,MALE_ENRL_2YR_TRANS_YR3_RT,MALE_UNKN_ORIG_YR3_RT,MALE_UNKN_4YR_TRANS_YR3_RT,MALE_UNKN_2YR_TRANS_YR3_RT,PELL_DEATH_YR3_RT,PELL_COMP_ORIG_YR3_RT,PELL_COMP_4YR_TRANS_YR3_RT,PELL_COMP_2YR_TRANS_YR3_RT,PELL_WDRAW_ORIG_YR3_RT,PELL_WDRAW_4YR_TRANS_YR3_RT,PELL_WDRAW_2YR_TRANS_YR3_RT,PELL_ENRL_ORIG_YR3_RT,PELL_ENRL_4YR_TRANS_YR3_RT,PELL_ENRL_2YR_TRANS_YR3_RT,PELL_UNKN_ORIG_YR3_RT,PELL_UNKN_4YR_TRANS_YR3_RT,PELL_UNKN_2YR_TRANS_YR3_RT,NOPELL_DEATH_YR3_RT,NOPELL_COMP_ORIG_YR3_RT,NOPELL_COMP_4YR_TRANS_YR3_RT,NOPELL_COMP_2YR_TRANS_YR3_RT,NOPELL_WDRAW_ORIG_YR3_RT,NOPELL_WDRAW_4YR_TRANS_YR3_RT,NOPELL_WDRAW_2YR_TRANS_YR3_RT,NOPELL_ENRL_ORIG_YR3_RT,NOPELL_ENRL_4YR_TRANS_YR3_RT,NOPELL_ENRL_2YR_TRANS_YR3_RT,NOPELL_UNKN_ORIG_YR3_RT,NOPELL_UNKN_4YR_TRANS_YR3_RT,NOPELL_UNKN_2YR_TRANS_YR3_RT,LOAN_DEATH_YR3_RT,LOAN_COMP_ORIG_YR3_RT,LOAN_COMP_4YR_TRANS_YR3_RT,LOAN_COMP_2YR_TRANS_YR3_RT,LOAN_WDRAW_ORIG_YR3_RT,LOAN_WDRAW_4YR_TRANS_YR3_RT,LOAN_WDRAW_2YR_TRANS_YR3_RT,LOAN_ENRL_ORIG_YR3_RT,LOAN_ENRL_4YR_TRANS_YR3_RT,LOAN_ENRL_2YR_TRANS_YR3_RT,LOAN_UNKN_ORIG_YR3_RT,LOAN_UNKN_4YR_TRANS_YR3_RT,LOAN_UNKN_2YR_TRANS_YR3_RT,NOLOAN_DEATH_YR3_RT,NOLOAN_COMP_ORIG_YR3_RT,NOLOAN_COMP_4YR_TRANS_YR3_RT,NOLOAN_COMP_2YR_TRANS_YR3_RT,NOLOAN_WDRAW_ORIG_YR3_RT,NOLOAN_WDRAW_4YR_TRANS_YR3_RT,NOLOAN_WDRAW_2YR_TRANS_YR3_RT,NOLOAN_ENRL_ORIG_YR3_RT,NOLOAN_ENRL_4YR_TRANS_YR3_RT,NOLOAN_ENRL_2YR_TRANS_YR3_RT,NOLOAN_UNKN_ORIG_YR3_RT,NOLOAN_UNKN_4YR_TRANS_YR3_RT,NOLOAN_UNKN_2YR_TRANS_YR3_RT,FIRSTGEN_DEATH_YR3_RT,FIRSTGEN_COMP_ORIG_YR3_RT,FIRSTGEN_COMP_4YR_TRANS_YR3_RT,FIRSTGEN_COMP_2YR_TRANS_YR3_RT,FIRSTGEN_WDRAW_ORIG_YR3_RT,FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT,FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT,FIRSTGEN_ENRL_ORIG_YR3_RT,FIRSTGEN_ENRL_4YR_TRANS_YR3_RT,FIRSTGEN_ENRL_2YR_TRANS_YR3_RT,FIRSTGEN_UNKN_ORIG_YR3_RT,FIRSTGEN_UNKN_4YR_TRANS_YR3_RT,FIRSTGEN_UNKN_2YR_TRANS_YR3_RT,NOT1STGEN_DEATH_YR3_RT,NOT1STGEN_COMP_ORIG_YR3_RT,NOT1STGEN_COMP_4YR_TRANS_YR3_RT,NOT1STGEN_COMP_2YR_TRANS_YR3_RT,NOT1STGEN_WDRAW_ORIG_YR3_RT,NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT,NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT,NOT1STGEN_ENRL_ORIG_YR3_RT,NOT1STGEN_ENRL_4YR_TRANS_YR3_RT,NOT1STGEN_ENRL_2YR_TRANS_YR3_RT,NOT1STGEN_UNKN_ORIG_YR3_RT,NOT1STGEN_UNKN_4YR_TRANS_YR3_RT,NOT1STGEN_UNKN_2YR_TRANS_YR3_RT,DEATH_YR4_RT,COMP_ORIG_YR4_RT,COMP_4YR_TRANS_YR4_RT,COMP_2YR_TRANS_YR4_RT,WDRAW_ORIG_YR4_RT,WDRAW_4YR_TRANS_YR4_RT,WDRAW_2YR_TRANS_YR4_RT,ENRL_ORIG_YR4_RT,ENRL_4YR_TRANS_YR4_RT,ENRL_2YR_TRANS_YR4_RT,UNKN_ORIG_YR4_RT,UNKN_4YR_TRANS_YR4_RT,UNKN_2YR_TRANS_YR4_RT,LO_INC_DEATH_YR4_RT,LO_INC_COMP_ORIG_YR4_RT,LO_INC_COMP_4YR_TRANS_YR4_RT,LO_INC_COMP_2YR_TRANS_YR4_RT,LO_INC_WDRAW_ORIG_YR4_RT,LO_INC_WDRAW_4YR_TRANS_YR4_RT,LO_INC_WDRAW_2YR_TRANS_YR4_RT,LO_INC_ENRL_ORIG_YR4_RT,LO_INC_ENRL_4YR_TRANS_YR4_RT,LO_INC_ENRL_2YR_TRANS_YR4_RT,LO_INC_UNKN_ORIG_YR4_RT,LO_INC_UNKN_4YR_TRANS_YR4_RT,LO_INC_UNKN_2YR_TRANS_YR4_RT,MD_INC_DEATH_YR4_RT,MD_INC_COMP_ORIG_YR4_RT,MD_INC_COMP_4YR_TRANS_YR4_RT,MD_INC_COMP_2YR_TRANS_YR4_RT,MD_INC_WDRAW_ORIG_YR4_RT,MD_INC_WDRAW_4YR_TRANS_YR4_RT,MD_INC_WDRAW_2YR_TRANS_YR4_RT,MD_INC_ENRL_ORIG_YR4_RT,MD_INC_ENRL_4YR_TRANS_YR4_RT,MD_INC_ENRL_2YR_TRANS_YR4_RT,MD_INC_UNKN_ORIG_YR4_RT,MD_INC_UNKN_4YR_TRANS_YR4_RT,MD_INC_UNKN_2YR_TRANS_YR4_RT,HI_INC_DEATH_YR4_RT,HI_INC_COMP_ORIG_YR4_RT,HI_INC_COMP_4YR_TRANS_YR4_RT,HI_INC_COMP_2YR_TRANS_YR4_RT,HI_INC_WDRAW_ORIG_YR4_RT,HI_INC_WDRAW_4YR_TRANS_YR4_RT,HI_INC_WDRAW_2YR_TRANS_YR4_RT,HI_INC_ENRL_ORIG_YR4_RT,HI_INC_ENRL_4YR_TRANS_YR4_RT,HI_INC_ENRL_2YR_TRANS_YR4_RT,HI_INC_UNKN_ORIG_YR4_RT,HI_INC_UNKN_4YR_TRANS_YR4_RT,HI_INC_UNKN_2YR_TRANS_YR4_RT,DEP_DEATH_YR4_RT,DEP_COMP_ORIG_YR4_RT,DEP_COMP_4YR_TRANS_YR4_RT,DEP_COMP_2YR_TRANS_YR4_RT,DEP_WDRAW_ORIG_YR4_RT,DEP_WDRAW_4YR_TRANS_YR4_RT,DEP_WDRAW_2YR_TRANS_YR4_RT,DEP_ENRL_ORIG_YR4_RT,DEP_ENRL_4YR_TRANS_YR4_RT,DEP_ENRL_2YR_TRANS_YR4_RT,DEP_UNKN_ORIG_YR4_RT,DEP_UNKN_4YR_TRANS_YR4_RT,DEP_UNKN_2YR_TRANS_YR4_RT,IND_DEATH_YR4_RT,IND_COMP_ORIG_YR4_RT,IND_COMP_4YR_TRANS_YR4_RT,IND_COMP_2YR_TRANS_YR4_RT,IND_WDRAW_ORIG_YR4_RT,IND_WDRAW_4YR_TRANS_YR4_RT,IND_WDRAW_2YR_TRANS_YR4_RT,IND_ENRL_ORIG_YR4_RT,IND_ENRL_4YR_TRANS_YR4_RT,IND_ENRL_2YR_TRANS_YR4_RT,IND_UNKN_ORIG_YR4_RT,IND_UNKN_4YR_TRANS_YR4_RT,IND_UNKN_2YR_TRANS_YR4_RT,FEMALE_DEATH_YR4_RT,FEMALE_COMP_ORIG_YR4_RT,FEMALE_COMP_4YR_TRANS_YR4_RT,FEMALE_COMP_2YR_TRANS_YR4_RT,FEMALE_WDRAW_ORIG_YR4_RT,FEMALE_WDRAW_4YR_TRANS_YR4_RT,FEMALE_WDRAW_2YR_TRANS_YR4_RT,FEMALE_ENRL_ORIG_YR4_RT,FEMALE_ENRL_4YR_TRANS_YR4_RT,FEMALE_ENRL_2YR_TRANS_YR4_RT,FEMALE_UNKN_ORIG_YR4_RT,FEMALE_UNKN_4YR_TRANS_YR4_RT,FEMALE_UNKN_2YR_TRANS_YR4_RT,MALE_DEATH_YR4_RT,MALE_COMP_ORIG_YR4_RT,MALE_COMP_4YR_TRANS_YR4_RT,MALE_COMP_2YR_TRANS_YR4_RT,MALE_WDRAW_ORIG_YR4_RT,MALE_WDRAW_4YR_TRANS_YR4_RT,MALE_WDRAW_2YR_TRANS_YR4_RT,MALE_ENRL_ORIG_YR4_RT,MALE_ENRL_4YR_TRANS_YR4_RT,MALE_ENRL_2YR_TRANS_YR4_RT,MALE_UNKN_ORIG_YR4_RT,MALE_UNKN_4YR_TRANS_YR4_RT,MALE_UNKN_2YR_TRANS_YR4_RT,PELL_DEATH_YR4_RT,PELL_COMP_ORIG_YR4_RT,PELL_COMP_4YR_TRANS_YR4_RT,PELL_COMP_2YR_TRANS_YR4_RT,PELL_WDRAW_ORIG_YR4_RT,PELL_WDRAW_4YR_TRANS_YR4_RT,PELL_WDRAW_2YR_TRANS_YR4_RT,PELL_ENRL_ORIG_YR4_RT,PELL_ENRL_4YR_TRANS_YR4_RT,PELL_ENRL_2YR_TRANS_YR4_RT,PELL_UNKN_ORIG_YR4_RT,PELL_UNKN_4YR_TRANS_YR4_RT,PELL_UNKN_2YR_TRANS_YR4_RT,NOPELL_DEATH_YR4_RT,NOPELL_COMP_ORIG_YR4_RT,NOPELL_COMP_4YR_TRANS_YR4_RT,NOPELL_COMP_2YR_TRANS_YR4_RT,NOPELL_WDRAW_ORIG_YR4_RT,NOPELL_WDRAW_4YR_TRANS_YR4_RT,NOPELL_WDRAW_2YR_TRANS_YR4_RT,NOPELL_ENRL_ORIG_YR4_RT,NOPELL_ENRL_4YR_TRANS_YR4_RT,NOPELL_ENRL_2YR_TRANS_YR4_RT,NOPELL_UNKN_ORIG_YR4_RT,NOPELL_UNKN_4YR_TRANS_YR4_RT,NOPELL_UNKN_2YR_TRANS_YR4_RT,LOAN_DEATH_YR4_RT,LOAN_COMP_ORIG_YR4_RT,LOAN_COMP_4YR_TRANS_YR4_RT,LOAN_COMP_2YR_TRANS_YR4_RT,LOAN_WDRAW_ORIG_YR4_RT,LOAN_WDRAW_4YR_TRANS_YR4_RT,LOAN_WDRAW_2YR_TRANS_YR4_RT,LOAN_ENRL_ORIG_YR4_RT,LOAN_ENRL_4YR_TRANS_YR4_RT,LOAN_ENRL_2YR_TRANS_YR4_RT,LOAN_UNKN_ORIG_YR4_RT,LOAN_UNKN_4YR_TRANS_YR4_RT,LOAN_UNKN_2YR_TRANS_YR4_RT,NOLOAN_DEATH_YR4_RT,NOLOAN_COMP_ORIG_YR4_RT,NOLOAN_COMP_4YR_TRANS_YR4_RT,NOLOAN_COMP_2YR_TRANS_YR4_RT,NOLOAN_WDRAW_ORIG_YR4_RT,NOLOAN_WDRAW_4YR_TRANS_YR4_RT,NOLOAN_WDRAW_2YR_TRANS_YR4_RT,NOLOAN_ENRL_ORIG_YR4_RT,NOLOAN_ENRL_4YR_TRANS_YR4_RT,NOLOAN_ENRL_2YR_TRANS_YR4_RT,NOLOAN_UNKN_ORIG_YR4_RT,NOLOAN_UNKN_4YR_TRANS_YR4_RT,NOLOAN_UNKN_2YR_TRANS_YR4_RT,FIRSTGEN_DEATH_YR4_RT,FIRSTGEN_COMP_ORIG_YR4_RT,FIRSTGEN_COMP_4YR_TRANS_YR4_RT,FIRSTGEN_COMP_2YR_TRANS_YR4_RT,FIRSTGEN_WDRAW_ORIG_YR4_RT,FIRSTGEN_WDRAW_4YR_TRANS_YR4_RT,FIRSTGEN_WDRAW_2YR_TRANS_YR4_RT,FIRSTGEN_ENRL_ORIG_YR4_RT,FIRSTGEN_ENRL_4YR_TRANS_YR4_RT,FIRSTGEN_ENRL_2YR_TRANS_YR4_RT,FIRSTGEN_UNKN_ORIG_YR4_RT,FIRSTGEN_UNKN_4YR_TRANS_YR4_RT,FIRSTGEN_UNKN_2YR_TRANS_YR4_RT,NOT1STGEN_DEATH_YR4_RT,NOT1STGEN_COMP_ORIG_YR4_RT,NOT1STGEN_COMP_4YR_TRANS_YR4_RT,NOT1STGEN_COMP_2YR_TRANS_YR4_RT,NOT1STGEN_WDRAW_ORIG_YR4_RT,NOT1STGEN_WDRAW_4YR_TRANS_YR4_RT,NOT1STGEN_WDRAW_2YR_TRANS_YR4_RT,NOT1STGEN_ENRL_ORIG_YR4_RT,NOT1STGEN_ENRL_4YR_TRANS_YR4_RT,NOT1STGEN_ENRL_2YR_TRANS_YR4_RT,NOT1STGEN_UNKN_ORIG_YR4_RT,NOT1STGEN_UNKN_4YR_TRANS_YR4_RT,NOT1STGEN_UNKN_2YR_TRANS_YR4_RT,DEATH_YR6_RT,COMP_ORIG_YR6_RT,COMP_4YR_TRANS_YR6_RT,COMP_2YR_TRANS_YR6_RT,WDRAW_ORIG_YR6_RT,WDRAW_4YR_TRANS_YR6_RT,WDRAW_2YR_TRANS_YR6_RT,ENRL_ORIG_YR6_RT,ENRL_4YR_TRANS_YR6_RT,ENRL_2YR_TRANS_YR6_RT,UNKN_ORIG_YR6_RT,UNKN_4YR_TRANS_YR6_RT,UNKN_2YR_TRANS_YR6_RT,LO_INC_DEATH_YR6_RT,LO_INC_COMP_ORIG_YR6_RT,LO_INC_COMP_4YR_TRANS_YR6_RT,LO_INC_COMP_2YR_TRANS_YR6_RT,LO_INC_WDRAW_ORIG_YR6_RT,LO_INC_WDRAW_4YR_TRANS_YR6_RT,LO_INC_WDRAW_2YR_TRANS_YR6_RT,LO_INC_ENRL_ORIG_YR6_RT,LO_INC_ENRL_4YR_TRANS_YR6_RT,LO_INC_ENRL_2YR_TRANS_YR6_RT,LO_INC_UNKN_ORIG_YR6_RT,LO_INC_UNKN_4YR_TRANS_YR6_RT,LO_INC_UNKN_2YR_TRANS_YR6_RT,MD_INC_DEATH_YR6_RT,MD_INC_COMP_ORIG_YR6_RT,MD_INC_COMP_4YR_TRANS_YR6_RT,MD_INC_COMP_2YR_TRANS_YR6_RT,MD_INC_WDRAW_ORIG_YR6_RT,MD_INC_WDRAW_4YR_TRANS_YR6_RT,MD_INC_WDRAW_2YR_TRANS_YR6_RT,MD_INC_ENRL_ORIG_YR6_RT,MD_INC_ENRL_4YR_TRANS_YR6_RT,MD_INC_ENRL_2YR_TRANS_YR6_RT,MD_INC_UNKN_ORIG_YR6_RT,MD_INC_UNKN_4YR_TRANS_YR6_RT,MD_INC_UNKN_2YR_TRANS_YR6_RT,HI_INC_DEATH_YR6_RT,HI_INC_COMP_ORIG_YR6_RT,HI_INC_COMP_4YR_TRANS_YR6_RT,HI_INC_COMP_2YR_TRANS_YR6_RT,HI_INC_WDRAW_ORIG_YR6_RT,HI_INC_WDRAW_4YR_TRANS_YR6_RT,HI_INC_WDRAW_2YR_TRANS_YR6_RT,HI_INC_ENRL_ORIG_YR6_RT,HI_INC_ENRL_4YR_TRANS_YR6_RT,HI_INC_ENRL_2YR_TRANS_YR6_RT,HI_INC_UNKN_ORIG_YR6_

In [7]:
# Preview of College ScorecardDataDictionary

df_college_score_card_dictionary.head()

,NAME OF DATA ELEMENT,Year,dev-category,developer-friendly name,VARIABLE NAME,API data type,label,VALUE,LABEL,SCORECARD? Y/N,SOURCE,NOTES
0,Unit ID for institution,NaN,root,id,UNITID,integer,NaN,NaN,NaN,NaN,IPEDS,NaN
1,8-digit OPE ID for institution,NaN,root,ope8_id,OPEID,integer,NaN,NaN,NaN,NaN,IPEDS,NaN
2,6-digit OPE ID for institution,NaN,root,ope6_id,opeid6,integer,NaN,NaN,NaN,NaN,IPEDS,NaN
3,Institution name,2013,school,name,INSTNM,string,NaN,NaN,NaN,Y,IPEDS,NaN
4,City,2013,school,city,CITY,string,NaN,NaN,NaN,Y,IPEDS,NaN

In [8]:
# Getting our dataset shape

df.shape

(7804, 1729)

In [9]:
# Looking for duplicates
df.duplicated().sum()

0

In [10]:
# Checking the shape of the crime dataset

df_crime_2015.shape

(378, 12)

In [11]:
# Previewing the first 5 records of the crime dataset

df_crime_2015.head()

,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
0,"Abilene, TX M.S.A.",412.5,5.3,56.0,78.4,272.8,3609.0,852.0,2493.6,263.4,TX,Abilene
1,"Akron, OH M.S.A.",238.4,5.1,38.2,75.2,119.8,2552.4,575.3,1853.0,124.1,OH,Akron
2,"Albany, GA M.S.A.",667.9,7.8,30.4,157.9,471.8,3894.1,1099.6,2652.8,141.7,GA,Albany
3,"Albany, OR M.S.A.",114.3,2.5,28.2,20.7,63.0,3208.4,484.6,2476.1,247.7,OR,Albany
4,"Albuquerque, NM M.S.A.",792.6,6.1,63.8,206.7,516.0,4607.8,883.4,3047.6,676.9,NM,Albuquerque

In [12]:
# Looking for null values in the crime dataset

df_crime_2015.isnull().sum()

MSA                  0
ViolentCrime         1
Murder               0
Rape                 0
Robbery              0
AggravatedAssault    1
PropertyCrime        6
Burglary             4
Theft                3
MotorVehicleTheft    0
State                0
City                 5
dtype: int64

In [13]:
# A closer inspection of the observations with the missing 'City' values
df_crime_2015[df_crime_2015['City'].isnull()]

,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
21,"Barnstable Town, MA M.S.A.",518.7,1.4,49.4,28.9,439.1,1722.5,475.9,1170.7,75.9,MA,NaN
146,"Hinesville, GA M.S.A.",304.4,1.2,10.7,60.9,231.6,2270.3,490.6,1656.8,122.9,GA,NaN
273,"Punta Gorda, FL M.S.A.",202.2,0.6,18.1,17.5,166.1,1509.5,242.4,1202.9,64.1,FL,NaN
310,"Sebring, FL M.S.A.",341.7,5.1,38.5,56.8,241.3,2739.4,633.6,1994.2,111.5,FL,NaN
311,"Sheboygan, WI M.S.A.",174.5,2.6,26.0,16.5,129.4,1569.7,159.7,1363.9,46.0,WI,NaN

From the college scorecard and crimes datasets, the common columns that will help us join these two dataframes are the CITY/STABBR columns in the college scorecard dataframes and the City/State columns in the crimes dataset. However, the City column in the crimes dataframe has some missing values so we have to fix this first before attempting a merger of the two dataframes

In [14]:
# Fix null city values in crimes Dataframe
# The appropriate city name can be deduced from the MSA Column
# of each row entry among the rows having missing city names
for index, row in df_crime_2015.iterrows():
  if pd.isnull(row['City']):
    df_crime_2015.loc[index, 'City'] = row['MSA'].split(',')[0]

In [15]:
# Confirming that 'City' does not have any missing values

df_crime_2015[df_crime_2015['City'].isnull()]

Empty DataFrame
Columns: [MSA, ViolentCrime, Murder, Rape, Robbery, AggravatedAssault, PropertyCrime, Burglary, Theft, MotorVehicleTheft, State, City]
Index: []

In [16]:
# Checking the 'City' variable for duplicates
df_crime_2015['City'].duplicated().sum()

32

In [17]:
# Removing duplicated rows from the crimes Dataframe
#unique_df = df.drop_duplicates(['country'])

df_crime_2015.drop_duplicates(['City'], inplace=True)

df_crime_2015['City'].duplicated().sum()

0

In [18]:
# Previewing the Kauffman Startup Index dataset

df_kauffman_startup_index.head()

,year_CPS,Characteristic,OppShare_New_Entrp,Breakdown,Rate_New_Entrp,Location,startup_index,Index Year,year_BDS,startup_density,Rank,Composition_of_New_Entrp,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text
0,1996.0,Less than High School,NaN,Education,0.003935,0,NaN,1996.0,NaN,NaN,NaN,0.1716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,national_demog,United States,National,NaN,393.468292,the,.
1,1998.0,Ages 35-44,0.79575,Age,0.003054,0,NaN,1998.0,NaN,NaN,NaN,0.2979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,national_demog,United States,National,7.9575,305.423187,the,.
2,2011.0,White,0.76008,Race,0.002936,0,NaN,2011.0,NaN,NaN,NaN,0.6021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,national_demog,United States,National,7.6008,293.582398,the,.
3,2011.0,Other,NaN,Race,NaN,0,NaN,2011.0,NaN,NaN,NaN,0.0248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,national_demog,United States,National,NaN,NaN,the,.
4,2011.0,Latino,0.67777,Race,0.005153,0,NaN,2011.0,NaN,NaN,NaN,0.2291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,national_demog,United States,National,6.7777,515.293396,the,.

In [19]:
# Selecting the important variables for Jane
columns = [
           'INSTNM',
           'sch_deg',
           'main',
           'CURROPER',
           'LONGITUDE',
           'LATITUDE',
           'CITY',
           'STABBR',
           'LOCALE',
           'HIGHDEG',
           'PREDDEG',
           'CONTROL',
           'faminc',
           'md_faminc',
           'faminc_ind',
           'RET_FT4',
           'RET_PT4',
           'RET_PT4',
           'RET_FTL4',
           'RET_PTL4',
           'COSTT4_A',
           'COSTT4_P',
           'TUITIONFEE_IN',
           'TUITIONFEE_OUT',
           'TUITIONFEE_PROG',
           'CIP10BACHL',
           'CIP11BACHL',
           'CIP14BACHL',
           'CIP15BACHL',
           'CIP10ASSOC',
           'CIP11ASSOC',
           'CIP14ASSOC',
           'CIP15ASSOC',
           'DISTANCEONLY',
           'PCIP10',
           'PCIP11',
           'PCIP14',
           'PCIP15',
           'TUITFTE',
           'INEXPFTE',
           'ADM_RATE',
           'ADM_RATE_ALL',
           'ACTCM25',
           'ACTCM75',
           'SAT_AVG_ALL',
           'NPT4_PUB',
           'NPT4_PRIV',
           'median_hh_inc',
           'C150_4',
           'C150_L4'
]

In [20]:
# Creating a dataframe called df_filtered which takes the above-listed columns from the df dataset

df_filtered = pd.DataFrame(df[columns])

In [21]:
# Previewing the first 5 records of the df_filtered dataset

df_filtered.head()

,INSTNM,sch_deg,main,CURROPER,LONGITUDE,LATITUDE,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,faminc,md_faminc,faminc_ind,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,DISTANCEONLY,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,median_hh_inc,C150_4,C150_L4
0,Alabama A & M University,NaN,1,1,-86.5685,34.7834,Normal,AL,12.0,4,3,1,NaN,NaN,NaN,0.6314,0.5000,0.5000,NaN,NaN,18888.0,NaN,7182.0,12774.0,NaN,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0348,0.0348,0.1175,0.0348,9063.0,7459.0,0.8989,0.8989,15.0,19.0,823.0,13415.0,NaN,NaN,0.2914,NaN
1,University of Alabama at Birmingham,NaN,1,1,-86.8092,33.5022,Birmingham,AL,12.0,4,3,1,NaN,NaN,NaN,0.8016,0.5000,0.5000,NaN,NaN,19990.0,NaN,7206.0,16398.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0099,0.0632,0.0000,9033.0,17208.0,0.8673,0.8673,22.0,28.0,1146.0,14805.0,NaN,NaN,0.5377,NaN
2,Amridge University,NaN,1,1,-86.1740,32.3626,Montgomery,AL,12.0,4,3,2,NaN,NaN,NaN,0.3750,0.3333,0.3333,NaN,NaN,12300.0,NaN,6870.0,6870.0,NaN,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0000,0.0411,0.0000,0.0000,12057.0,5123.0,NaN,NaN,NaN,NaN,NaN,NaN,7455.0,NaN,0.6667,NaN
3,University of Alabama in Huntsville,NaN,1,1,-86.6384,34.7228,Huntsville,AL,12.0,4,3,1,NaN,NaN,NaN,0.8098,0.4444,0.4444,NaN,NaN,20306.0,NaN,9192.0,21506.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0273,0.2566,0.0000,8322.0,9352.0,0.8062,0.8062,23.0,29.0,1180.0,17520.0,NaN,NaN,0.4835,NaN
4,Alabama State University,NaN,1,1,-86.2957,32.3643,Montgomery,AL,12.0,4,3,1,NaN,NaN,NaN,0.6219,0.3023,0.3023,NaN,NaN,17400.0,NaN,8720.0,15656.0,NaN,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0450,0.0000,0.0000,7813.0,7393.0,0.5125,0.5125,15.0,19.0,830.0,11936.0,NaN,NaN,0.2517,NaN

In [22]:
# Checking the shape of our new dataset
df_filtered.shape

(7804, 50)

In [23]:
# Checking the number of missing values

df_filtered.isnull().sum()

INSTNM                0
sch_deg            7804
main                  0
CURROPER              0
LONGITUDE           785
LATITUDE            785
CITY                  0
STABBR                0
LOCALE              424
HIGHDEG               0
PREDDEG               0
CONTROL               0
faminc             7804
md_faminc          7804
faminc_ind         7804
RET_FT4            5456
RET_PT4            6336
RET_PT4            6336
RET_FTL4           3884
RET_PTL4           5540
COSTT4_A           3667
COSTT4_P           5263
TUITIONFEE_IN      3389
TUITIONFEE_OUT     3608
TUITIONFEE_PROG    5092
CIP10BACHL          421
CIP11BACHL          421
CIP14BACHL          421
CIP15BACHL          421
CIP10ASSOC          421
CIP11ASSOC          421
CIP14ASSOC          421
CIP15ASSOC          421
DISTANCEONLY        421
PCIP10              718
PCIP11              718
PCIP14              718
PCIP15              718
TUITFTE             442
INEXPFTE            442
ADM_RATE           5584
ADM_RATE_ALL       5320
ACTCM25            6462
ACTCM75            6462
SAT_AVG_ALL        6273
NPT4_PUB           5881
NPT4_PRIV          3051
median_hh_inc      7804
C150_4             5356
C150_L4            3839
dtype: int64

It can be seen that there are 5 columns, with all values missing, hence we are to drop the columns.

In [24]:
# Dropping columns with a hundred percent missing values

df_filtered.dropna(axis = 1, how="all", inplace=True)

df_filtered.shape

(7804, 45)

Jane wants to physically attend school in the United States and expereicence the big city life. Institutions that are regarded as distance only and which are not currently operating are therefore, out of the question for Jane and we have to exclude them from the Dataframe

In [25]:
# Getting the distribution of the unique values in the 'DISTANCEONLY' column

df_filtered['DISTANCEONLY'].unique()

array([ 0.,  1., nan])

In [26]:
# Dropping all rows where DISTANCEONLY is set to 1 then drop the DISTANCEONLY column

df_filtered.drop(df_filtered[df_filtered.DISTANCEONLY == 1].index, inplace=True)

#df_filtered.groupby('DISTANCEONLY', as_index=False).count()

#df_filtered['DISTANCEONLY'].unique()

df_filtered.drop(['DISTANCEONLY'], axis = 1,  inplace=True)

df_filtered.shape

(7767, 44)

In [27]:
# Dropping all rows where CURROPER is set to 0 then drop the CURROPER column

#df_filtered['CURROPER'].unique()

#df_filtered.groupby('CURROPER', as_index=False).count()


df_filtered.drop(df_filtered[df_filtered.CURROPER == 0].index, inplace=True)

df_filtered.shape

(7405, 44)

In [28]:
# Checking the dataset's shape
df_filtered.shape

(7405, 44)

Before attempting a merger between the crimes dataframe and the college scorecard dataframe, we have to ensure that the city/state combinations across the two dataframes actually match. If a blind merger is done some entries in the college scorecard dataframe might end up having missing crime data probably because there was a typo in the way the city name was written in one of the datasets. To avoid this, we need the ability to determine if two city names refer to the same location.

In [29]:
"""
First, we extract all cities in the college scorecard dataframe that do not have an 
exact 100% match in the crimes dataframe and save them in a list for later use.
"""
def find_cities_without_exact_matches(df1, df2):
  cities_without_match = []
  for index, row in df1.iterrows():
    if  row['CITY'] not in df2['City'].values:
      cities_without_match.append(f"{row['CITY']}, {row['STABBR']}")
  return cities_without_match    

cities_without_match = find_cities_without_exact_matches(df_filtered, df_crime_2015)

To detect possibly matching cities across the cities that we found have no matching names in the crimes dataframe, we enlist the fuzzywuzzy module which has functionaliy that allows one to determine the extent to which two words or sentences are similar

In [30]:
! pip install fuzzywuzzy[speedup]

from fuzzywuzzy import process

#utility function to determine the extent to which two words are similar
def get_possible_matching_strings(input_list, search_against_list):
  original = []
  best_match = []
  probability = []
  similarities = {}
  for x in input_list:
    prediction = process.extractOne(x, search_against_list)
    original.append(x)
    best_match.append(prediction[0])
    probability.append(prediction[1])
  similarities['original'] = pd.Series(original)
  similarities['best_match'] =  pd.Series(best_match)
  similarities['probability'] = pd.Series(probability)
  return pd.DataFrame(similarities)

Requirement already satisfied: fuzzywuzzy[speedup] in /usr/local/lib/python3.6/dist-packages (0.18.0)
Requirement already satisfied: python-levenshtein>=0.12; extra == "speedup" in /usr/local/lib/python3.6/dist-packages (from fuzzywuzzy[speedup]) (0.12.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from python-levenshtein>=0.12; extra == "speedup"->fuzzywuzzy[speedup]) (50.3.0)

In [31]:
# We prepare the search_against list which is among the inputs to the utility functions defined above
city_state_combinations_in_crimes = []

for index, row in df_crime_2015.iterrows():
  city_state_combinations_in_crimes.append(f"{row['City']}, {row['State']}")

In [32]:
# We find cities that could possibly be referring to the same location

df_similar_cities = get_possible_matching_strings(cities_without_match, city_state_combinations_in_crimes)
df_similar_cities.reset_index(drop=True)

                          original  \
0                       Normal, AL
1               Alexander City, AL
2            Auburn University, AL
3                  Phenix City, AL
4                        Selma, AL
5                   Enterprise, AL
6                  Bay Minette, AL
7                  Albertville, AL
8                   Hanceville, AL
9                        Selma, AL
10                     Brewton, AL
11                      Tanner, AL
12                      Marion, AL
13                  Livingston, AL
14                   Andalusia, AL
15                      Marion, AL
16                   Fairfield, AL
17                  Montevallo, AL
18               Muscle Shoals, AL
19                  Rainsville, AL
20                 Monroeville, AL
21                   Evergreen, AL
22                       Selma, AL
23                        Boaz, AL
24                   Talladega, AL
25                        Troy, AL
26                    Tuskegee, AL
27                      Jasper, AL
28                      Palmer, AK
29                      Juneau, AK
30                      Seward, AK
31                      Valdez, AK
32                        Mesa, AZ
33                       Tempe, AZ
34                    Coolidge, AZ
35                     Douglas, AZ
36                    Chandler, AZ
37                        Mesa, AZ
38                    Thatcher, AZ
39                  Scottsdale, AZ
40                    Glendale, AZ
41                        Mesa, AZ
42                       Tempe, AZ
43                     Kingman, AZ
44                      Tsaile, AZ
45                    Holbrook, AZ
46                  Scottsdale, AZ
47                       Tempe, AZ
48                       Tempe, AZ
49                     Safford, AZ
50                  Scottsdale, AZ
51                    Avondale, AZ
52                       Tempe, AZ
53                    Glendale, AZ
54                 Arkadelphia, AR
55                Russellville, AR
56                  Batesville, AR
57           North Little Rock, AR
58                Fayetteville, AR
59                       Beebe, AR
60                Russellville, AR
61                  Monticello, AR
62                  Pocahontas, AR
63                      Conway, AR
64                      Conway, AR
65                    De Queen, AR
66                   Paragould, AR
67                Forrest City, AR
68                Forrest City, AR
69           North Little Rock, AR
70                 Hot Springs, AR
71                  Batesville, AR
72                      Searcy, AR
73                 Arkadelphia, AR
74                      Conway, AR
75                 Hot Springs, AR
76              Siloam Springs, AR
77           North Little Rock, AR
78                  Springdale, AR
79                West Memphis, AR
80                 Blytheville, AR
81                  Monticello, AR
82           North Little Rock, AR
83                    Harrison, AR
84                  Springdale, AR
85                 Arkadelphia, AR
86                     Malvern, AR
87                   Morrilton, AR
88                      Helena, AR
89                   El Dorado, AR
90           North Little Rock, AR
91                        Hope, AR
92                        Mena, AR
93                Fayetteville, AR
94                      Searcy, AR
95               N Little Rock, AR
96                Walnut Ridge, AR
97                   El Dorado, AR
98                    Magnolia, AR
99              Rancho Cordova, CA
100           Huntington Beach, CA
101                    Alameda, CA
102                    Alameda, CA
103                   Berkeley, CA
104                West Covina, CA
105                   Pasadena, CA
106                      Azusa, CA
107                    Barstow, CA
108              National City, CA
109                  La Mirada, CA
110              Santa Barbara, CA
111                   Oroville, CA
112                 Chatsworth, CA
113                      Aptos, CA
114                   Pasadena, CA
115              Thousand Oaks, CA
116                    Turlock, CA
117             San Bernardino, CA
118                     Pomona, CA
119                     Carson, CA
120                  Fullerton, CA
121                    Hayward, CA
122                 Long Beach, CA
123                 Northridge, CA
124                   Berkeley, CA
125                      Davis, CA
126                     Irvine, CA
127                   La Jolla, CA
128              Santa Barbara, CA
129                  Palo Alto, CA
130                    La Mesa, CA
131                   Valencia, CA
132               Redwood City, CA
133              Santa Clarita, CA
134               Garden Grove, CA
135                   Van Nuys, CA
136             San Bernardino, CA
137                Watsonville, CA
138                    Norwalk, CA
139                 Ridgecrest, CA
140                    Hayward, CA
141           Rancho Cucamonga, CA
142                     Orange, CA
143                     Irvine, CA
144                   El Cajon, CA
145                   Berkeley, CA
146                   Glendora, CA
147             Citris Heights, CA
148                  Claremont, CA
149                  Claremont, CA
150                     Clovis, CA
151            Fountain Valley, CA
152                  Sunnyvale, CA
153                     Orange, CA
154                     Pomona, CA
155                     Sonora, CA
156                    Tarzana, CA
157                    Compton, CA
158                  San Pablo, CA
159                    Yucaipa, CA
160                   El Cajon, CA
161                    Cypress, CA
162                  Cupertino, CA
163                      Hemet, CA
164                Palm Desert, CA
165                  Blue Lake, CA
166                Palm Desert, CA
167              Pleasant Hill, CA
168                   Berkeley, CA
169              Monterey Park, CA
170                Santa Clara, CA
171                   Torrance, CA
172                  Hollywood, CA
173                    Burbank, CA
174              Moreno Valley, CA
175               Santa Monica, CA
176                     Irvine, CA
177                     Quincy, CA
178              Santa Barbara, CA
179                     Orange, CA
180            Los Altos Hills, CA
181                   Berkeley, CA
182                     Eureka, CA
183                   Pasadena, CA
184                  Fullerton, CA
185                     Gilroy, CA
186                   Carlsbad, CA
187                   Glendale, CA
188                   Glendale, CA
189           Huntington Beach, CA
190                   Berkeley, CA
191                   El Cajon, CA
192             San Bernardino, CA
193                  Claremont, CA
194                  Daly City, CA
195                Carpinteria, CA
196                     Arcata, CA
197                   Imperial, CA
198                Santa Clara, CA
199              Newport Beach, CA
200               Santa Monica, CA
201                     Irvine, CA
202              National City, CA
203                  San Dimas, CA
204                     Orange, CA
205                   El Cajon, CA
206              Pleasant Hill, CA
207                    Reedley, CA
208                  San Dimas, CA
209                   La Verne, CA
210               Laguna Beach, CA
211           South Lake Tahoe, CA
212                 Susanville, CA
213                    Hayward, CA
214                   El Cajon, CA
215                 Loma Linda, CA
216                 Long Beach, CA
217                   Whittier, CA
218             Woodland Hills, CA
219                Valley Glen, CA
220              Santa Clarita, CA
221                     Sylmar, CA
222                  Pittsburg, CA
223                    Ventura, CA
224                      Vista, CA
225                  Kentfield, CA
226        Rancho Palos Verdes, CA
227                      Ukiah, CA
228                   Atherton, CA
229                  Oceanside, CA
230                Santa Clara, CA
231            North Hollywood, CA
232                   Monterey, CA
233                   Monterey, CA
234                   Moorpark, CA
235                     Walnut, CA
236                San Jacinto, CA
237                  Hollywood, CA
238                 Emeryville, CA
239                   La Jolla, CA
240              Granada Hills, CA
241                     Pomona, CA
242                West Covina, CA
243                   Pasadena, CA
244                    Belmont, CA
245                  Oceanside, CA
246                    Fremont, CA
247                 Costa Mesa, CA
248                  Fullerton, CA
249                  Palo Alto, CA
250                   Berkeley, CA
251                   Pasadena, CA
252                   Berkeley, CA
253                     Angwin, CA
254                     Blythe, CA
255                 San Marcos, CA
256                    Concord, CA
257                   Pasadena, CA
258                     Malibu, CA
259                  Claremont, CA
260                  Claremont, CA
261                Porterville, CA
262                   Torrance, CA
263                   El Monte, CA
264                  Santa Ana, CA
265               Santa Monica, CA
266                   Redlands, CA
267                     Eureka, CA
268                     Upland, CA
269                     Corona, CA
270                   Whittier, CA
271                    Alameda, CA
272                   Rosemead, CA
273              Mission Viejo, CA
274                   Carlsbad, CA
275                San Anselmo, CA
276                     Clovis, CA
277                    Rocklin, CA
278                  San Mateo, CA
279              Santa Barbara, CA
280                Santa Clara, CA
281               Santa Monica, CA
282                  Claremont, CA
283                    Rocklin, CA
284                  Santa Ana, CA
285                       Weed, CA
286                  San Bruno, CA
287             San Bernardino, CA
288                     Moraga, CA
289                  Fairfield, CA
290               Rohnert Park, CA
291                   Alhambra, CA
292                     Orange, CA
293                 Costa Mesa, CA
294               Garden Grove, CA
295                Chula Vista, CA
296                   Berkeley, CA
297                  Fullerton, CA
298                       Taft, CA
299                  Claremont, CA
300                Santa Paula, CA
301                Lake Forest, CA
302            Huntington Park, CA
303             San Bernardino, CA
304            North Hollywood, CA
305                    Ventura, CA
306                Victorville, CA
307                Victorville, CA
308                   Berkeley, CA
309                   Coalinga, CA
310                Culver City, CA
311                   Saratoga, CA
312                  Escondido, CA
313              Santa Barbara, CA
314                   Whittier, CA
315                    Burbank, CA
316                   Berkeley, CA
317                  Fullerton, CA
318                 Marysville, CA
319                    Alamosa, CO
320                  Littleton, CO
321                 Broomfield, CO
322                   Lakewood, CO
323                     Aurora, CO
324           Glenwood Springs, CO
325                    Rangely, CO
326                     Golden, CO
327                   Lakewood, CO
328                   Lakewood, CO
329                     Aurora, CO
330                      Delta, CO
331                Westminster, CO
332                  Littleton, CO
333                    Durango, CO
334                Westminster, CO
335           Glenwood Springs, CO
336                      Lamar, CO
337                Fort Morgan, CO
338                   Sterling, CO
339                   La Junta, CO
340                   Thornton, CO
341                   Lakewood, CO
342                   Lakewood, CO
343                     Aurora, CO
344                   Trinidad, CO
345                   Thornton, CO
346                   Gunnison, CO
347                  New Haven, CT
348                    Danbury, CT
349                    Enfield, CT
350                   Branford, CT
351                Southington, CT
352                New Britain, CT
353                  Newington, CT
354                 New London, CT
355              East Hartford, CT
356                   Branford, CT
357                     Storrs, CT
358              East Hartford, CT
359               East Windsor, CT
360                Willimantic, CT
361                  Fairfield, CT
362                North Haven, CT
363              West Hartford, CT
364              West Hartford, CT
365                   Cromwell, CT
366                  Waterbury, CT
367                 Middletown, CT
368                 New London, CT
369                New Britain, CT
370                     Somers, CT
371                 West Haven, CT
372                 New London, CT
373                    Norwalk, CT
374                    Winsted, CT
375                     Hamden, CT
376                    Meriden, CT
377                  Stratford, CT
378                  Waterbury, CT
379                  Danielson, CT
380                     Hamden, CT
381                  Fairfield, CT
382              West Hartford, CT
383                  New Haven, CT
384                  New Haven, CT
385                 West Haven, CT
386                   New York, NY
387                 Middletown, CT
388                    Danbury, CT
389                  New Haven, CT
390                  New Haven, CT
391                      Lewes, DE
392                 Georgetown, DE
393                     Newark, DE
394                     Newark, DE
395                 New Castle, DE
396               Falls Church, VA
397               Ormond Beach, FL
398              Coconut Creek, FL
399                 Graceville, FL
400                 Boca Raton, FL
401                  Bradenton, FL
402                     Starke, FL
403                      Cocoa, FL
404                Winter Park, FL
405             Port Charlotte, FL
406                   Marianna, FL
407                 Clearwater, FL
408           Royal Palm Beach, FL
409           Saint Petersburg, FL
410                 Fort Myers, FL
411                 Boca Raton, FL
412            Saint Augustine, FL
413             Temple Terrace, FL
414                    Miramar, FL
415                   Key West, FL
416              Miami Gardens, FL
417                Fort Pierce, FL
418                Winter Park, FL
419                Dania Beach, FL
420                 Hobe Sound, FL
421                  Hollywood, FL
422              Pinellas Park, FL
423                Fort Pierce, FL
424              South Daytona, FL
425                 Fort Myers, FL
426                    Hialeah, FL
427                  Lake City, FL
428                     Eustis, FL
429                   Leesburg, FL
430                 Fort Myers, FL
431           Saint Petersburg, FL
432                   Lithonia, GA
433                  Bradenton, FL
434                  Bradenton, FL
435                      Davie, FL
436                Miami Lakes, FL
437               Coral Gables, FL
438                 Lake Worth, FL
439                  Niceville, FL
440                 Lake Worth, FL
441            New Port Richey, FL
442                 Clearwater, FL
443               Winter Haven, FL
444                     Milton, FL
445              Boynton Beach, FL
446               Winter Haven, FL
447                Winter Park, FL
448            Saint Augustine, FL
449                  Saint Leo, FL
450                 Clearwater, FL
451           Saint Petersburg, FL
452                    Sanford, FL
453                  Hollywood, FL
454                    Palatka, FL
455                  Avon Park, FL
456              Miami Gardens, FL
457                     DeLand, FL
458            New Port Richey, FL
459                   Live Oak, FL
460                Miami Beach, FL
461                      Perry, FL
462                    Trinity, FL
463                 Lake Wales, FL
464                    Chipley, FL
465                Babson Park, FL
466              Winter Garden, FL
467                      Davie, FL
468                Winter Park, FL
469                  Inverness, FL
470                     Tifton, GA
471                   Chamblee, GA
472                     Morrow, GA
473                   Cuthbert, GA
474                    Conyers, GA
475                 West Point, GA
476                    Augusta, GA
477                 Bainbridge, GA
478                Forest Park, GA
479                Mount Berry, GA
480                     Morrow, GA
481           Lookout Mountain, GA
482             Stone Mountain, GA
483                 Swainsboro, GA
484           Franklin Springs, GA
485                Fort Valley, GA
486                   Americus, GA
487              Milledgeville, GA
488              Milledgeville, GA
489                 Statesboro, GA
490                Barnesville, GA
491                    Griffin, GA
492                    Lilburn, GA
493              Lawrenceville, GA
494                   Kennesaw, GA
495                   Lagrange, GA
496                    Oakwood, GA
497                   Marietta, GA
498                   Marietta, GA
499                   Moultrie, GA
500               Clarkesville, GA
501                    Augusta, GA
502                   Demorest, GA
503                    Waleska, GA
504                   Americus, GA
505                   Marietta, GA
506                Thomasville, GA
507                Thomasville, GA
508               Toccoa Falls, GA
509                   Valdosta, GA
510                   Valdosta, GA
511                 Carrollton, GA
512               Young Harris, GA
513                       Hilo, HI
514                      Lihue, HI
515                 Pearl City, HI
516                    Kapolei, HI
517                    Kaneohe, HI
518                     Moscow, ID
519                   Caldwell, ID
520                 Twin Falls, ID
521                     Moscow, ID
522                      Nampa, ID
523                   Chubbuck, ID
524                    Rexburg, ID
525                 Twin Falls, ID
526                Rock Island, IL
527                     Aurora, IL
528                     Urbana, IL
529                 Belleville, IL
530                     Moline, IL
531                Carlinville, IL
532                     Quincy, IL
533                     Quincy, IL
534                Bourbonnais, IL
535                   Oak Lawn, IL
536                 Villa Park, IL
537               Hanover Park, IL
538                 Oak Forest, IL
539                  Galesburg, IL
540                East Moline, IL
541              Downers Grove, IL
542               River Forest, IL
543               Crystal Lake, IL
544                 Glen Ellyn, IL
545                   Elmhurst, IL
546                     Eureka, IL
547               Crystal Lake, IL
548               Bedford Park, IL
549                   Evanston, IL
550                     Quincy, IL
551            University Park, IL
552                West Dundee, IL
553                   Sycamore, IL
554                     Oswego, IL
555                     Skokie, IL
556                   Freeport, IL
557              North Chicago, IL
558                      Lisle, IL
559                  Champaign, IL
560                East Peoria, IL
561                      Olney, IL
562                     Normal, IL
563                    Oglesby, IL
564                Carterville, IL
565                     Quincy, IL
566                     Joliet, IL
567                   Kankakee, IL
568                  Centralia, IL
569                      Malta, IL

In [33]:
# We check the shape of the new generated city similarities dataframe

df_similar_cities.shape

(4273, 3)

In [34]:
# We drop duplicates in the new generated city similarities dataframe

df_similar_cities.drop_duplicates(subset=['original', 'best_match', 'probability'], keep='last', inplace=True)

df_similar_cities.shape

(2422, 3)

In [35]:
"""
Rows with a probability match of 87 and above
are the ones that provide the most promising
matching city combinations from the crimes and 
college score board datasets
"""
df_most_promising_matches = df_similar_cities[df_similar_cities['probability'] >= 87].reset_index(drop=True)
df_most_promising_matches

                      original            best_match  probability
0            N Little Rock, AR       Little Rock, AR           95
1            Santa Clarita, CA       Santa Maria, CA           88
2                Pittsburg, CA        Pittsburgh, PA           89
3            West Hartford, CT          Hartford, CT           95
4              Dania Beach, FL     Daytona Beach, FL           88
5            North Chicago, IL           Chicago, IL           90
6                 Johnston, IA         Johnstown, PA           88
7               S Portland, ME          Portland, ME           95
8                  Taunton, MA          Staunton, VA           87
9                   Dultuh, MN            Duluth, MN           90
10           North Mankato, MN           Mankato, MN           90
11                 Kinston, NC          Kingston, NY           87
12            North Canton, OH            Canton, OH           90
13             Stroudsburg, PA  East Stroudsburg, PA           95
14        North Providence, RI        Providence, RI           95
15                 Newbern, TN          New Bern, NC           87
16             Greeneville, TN        Greenville, NC           90
17               Clarendon, TX            Laredo, TX           87
18                 Chester, VA        Winchester, VA           88
19  University of Richmond, VA          Richmond, VA           90
20             Fond Du Lac, WI       Fond du Lac, WI          100
21                Stanford, CA           Hanford, CA           87
22           Coeur D Alene, ID     Coeur d'Alene, ID          100
23           South Houston, TX           Houston, TX           90
24                Canfield, OH         Mansfield, OH           88
25             North Miami, FL             Miami, FL           90
26            Saint Joseph, MO         St Joseph, MO           90
27                 CHESTER, VA        Winchester, VA           88
28        South Charleston, WV        Charleston, WV           95
29        Port Saint Lucie, FL     Port St Lucie, FL           92
30              Harrisburg, PA      Harrisonburg, VA           87
31             West Monroe, LA            Monroe, LA           90
32           East Hartford, CT          Hartford, CT           95
33          South Portland, ME          Portland, ME           90
34            Saint George, UT        St. George, UT           87
35               Ft. Wayne, IN        Fort Wayne, IN           89
36             East Peoria, IL            Peoria, IL           90
37         North Las Vegas, NV         Las Vegas, NV           95
38                Ft Worth, TX        Fort Worth, TX           92
39       North Little Rock, AR       Little Rock, AR           95
40            East Lansing, MI           Lansing, MI           95
41         West Des Moines, IA        Des Moines, IA           95
42     South San Francisco, CA     San Francisco, CA           95
43         East Providence, RI        Providence, RI           95
44              Dorchester, MA         Worcester, MA           89
45             Santa Clara, CA       Santa Maria, CA           87

In [36]:
# Cities may have possibly matching names but yet be in
# different states meaning that they are not refering to the
# same location. we therefore, have to drop rows with mismatching states
for index, row in df_most_promising_matches.iterrows():
  if row['original'].split(",")[1] != row['best_match'].split(",")[1]:
    df_most_promising_matches.drop(index, inplace=True)

df_most_promising_matches.reset_index(drop=True)
df_most_promising_matches

                      original            best_match  probability
0            N Little Rock, AR       Little Rock, AR           95
1            Santa Clarita, CA       Santa Maria, CA           88
3            West Hartford, CT          Hartford, CT           95
4              Dania Beach, FL     Daytona Beach, FL           88
5            North Chicago, IL           Chicago, IL           90
7               S Portland, ME          Portland, ME           95
9                   Dultuh, MN            Duluth, MN           90
10           North Mankato, MN           Mankato, MN           90
12            North Canton, OH            Canton, OH           90
13             Stroudsburg, PA  East Stroudsburg, PA           95
14        North Providence, RI        Providence, RI           95
17               Clarendon, TX            Laredo, TX           87
18                 Chester, VA        Winchester, VA           88
19  University of Richmond, VA          Richmond, VA           90
20             Fond Du Lac, WI       Fond du Lac, WI          100
21                Stanford, CA           Hanford, CA           87
22           Coeur D Alene, ID     Coeur d'Alene, ID          100
23           South Houston, TX           Houston, TX           90
24                Canfield, OH         Mansfield, OH           88
25             North Miami, FL             Miami, FL           90
26            Saint Joseph, MO         St Joseph, MO           90
27                 CHESTER, VA        Winchester, VA           88
28        South Charleston, WV        Charleston, WV           95
29        Port Saint Lucie, FL     Port St Lucie, FL           92
31             West Monroe, LA            Monroe, LA           90
32           East Hartford, CT          Hartford, CT           95
33          South Portland, ME          Portland, ME           90
34            Saint George, UT        St. George, UT           87
35               Ft. Wayne, IN        Fort Wayne, IN           89
36             East Peoria, IL            Peoria, IL           90
37         North Las Vegas, NV         Las Vegas, NV           95
38                Ft Worth, TX        Fort Worth, TX           92
39       North Little Rock, AR       Little Rock, AR           95
40            East Lansing, MI           Lansing, MI           95
41         West Des Moines, IA        Des Moines, IA           95
42     South San Francisco, CA     San Francisco, CA           95
43         East Providence, RI        Providence, RI           95
44              Dorchester, MA         Worcester, MA           89
45             Santa Clara, CA       Santa Maria, CA           87

We now have the most promising city/state matches yet. However, some matches are still wrong and we need a way of eliminating the dataframe. We cannot do a blind deletion based on the probability values as this would also remove rows that have "true" matches too. Some human intervention will be required for this.

In [37]:
"""
The code below cycles through the rows of the dataframe with the most promising
city/state combinations and asks the user whether to drop or keep an entry with
a probability that is below 90%
"""

for index, row in df_most_promising_matches.iterrows():
  if row['probability'] < 90:
    action = input(f"({row['original']} : {row['best_match']}). Keep/Drop?")
    if action == 'Drop':
      df_most_promising_matches.drop(index, inplace=True)
    elif action == 'Keep':
      continue

(Santa Clarita, CA : Santa Maria, CA). Keep/Drop?Drop
(Dania Beach, FL : Daytona Beach, FL). Keep/Drop?Drop
(Clarendon, TX : Laredo, TX). Keep/Drop?Drop
(Chester, VA : Winchester, VA). Keep/Drop?Drop
(Stanford, CA : Hanford, CA). Keep/Drop?Drop
(Canfield, OH : Mansfield, OH). Keep/Drop?Drop
(CHESTER, VA : Winchester, VA). Keep/Drop?Drop
(Saint George, UT : St. George, UT). Keep/Drop?Keep
(Ft. Wayne, IN : Fort Wayne, IN). Keep/Drop?Keep
(Dorchester, MA : Worcester, MA). Keep/Drop?Drop
(Santa Clara, CA : Santa Maria, CA). Keep/Drop?Drop

In [38]:
df_most_promising_matches.reset_index(drop=True)
df_most_promising_matches.head()

            original       best_match  probability
0  N Little Rock, AR  Little Rock, AR           95
3  West Hartford, CT     Hartford, CT           95
5  North Chicago, IL      Chicago, IL           90
7     S Portland, ME     Portland, ME           95
9         Dultuh, MN       Duluth, MN           90

For each entry in df_most_promising, we have to find a matching CITY/STABBR 
combinaition in df_filtered and replace the CITY value with the value contained
in the best_match column of df_most promising. This will then allow us to merge the college scorecard 
dataframe with the crimes dataframe without loosing as much information as we would have lost if we had one a blind merger

In [39]:
"""
We use a for loop to update city names in college scorecard dataframe
"""
for index, row in df_most_promising_matches.iterrows():
  split_result = row['original'].split(',')
  city = split_result[0].strip()
  state = split_result[1].strip()
  best_match = row['best_match'].split(',')[0]
  print(f"{city} : {state} : {best_match}")
  for index2, row2 in df_filtered.iterrows():
    if row2['CITY'] == city and row2['STABBR'] == state:
      df_filtered.loc[index2, 'CITY'] = best_match
      print(f"Updated {row2['CITY']} to {best_match}")

N Little Rock : AR : Little Rock
Updated N Little Rock to Little Rock
West Hartford : CT : Hartford
Updated West Hartford to Hartford
Updated West Hartford to Hartford
Updated West Hartford to Hartford
North Chicago : IL : Chicago
Updated North Chicago to Chicago
S Portland : ME : Portland
Updated S Portland to Portland
Dultuh : MN : Duluth
Updated Dultuh to Duluth
North Mankato : MN : Mankato
Updated North Mankato to Mankato
North Canton : OH : Canton
Updated North Canton to Canton
Updated North Canton to Canton
Stroudsburg : PA : East Stroudsburg
Updated Stroudsburg to East Stroudsburg
North Providence : RI : Providence
Updated North Providence to Providence
University of Richmond : VA : Richmond
Updated University of Richmond to Richmond
Fond Du Lac : WI : Fond du Lac
Updated Fond Du Lac to Fond du Lac
Coeur D Alene : ID : Coeur d'Alene
Updated Coeur D Alene to Coeur d'Alene
South Houston : TX : Houston
Updated South Houston to Houston
North Miami : FL : Miami
Updated North Miami to Miami
Saint Joseph : MO : St Joseph
Updated Saint Joseph to St Joseph
Updated Saint Joseph to St Joseph
Updated Saint Joseph to St Joseph
South Charleston : WV : Charleston
Updated South Charleston to Charleston
Port Saint Lucie : FL : Port St Lucie
Updated Port Saint Lucie to Port St Lucie
West Monroe : LA : Monroe
Updated West Monroe to Monroe
Updated West Monroe to Monroe
East Hartford : CT : Hartford
Updated East Hartford to Hartford
Updated East Hartford to Hartford
Updated East Hartford to Hartford
South Portland : ME : Portland
Updated South Portland to Portland
Updated South Portland to Portland
Saint George : UT : St. George
Updated Saint George to St. George
Updated Saint George to St. George
Updated Saint George to St. George
Updated Saint George to St. George
Ft. Wayne : IN : Fort Wayne
Updated Ft. Wayne to Fort Wayne
East Peoria : IL : Peoria
Updated East Peoria to Peoria
Updated East Peoria to Peoria
Updated East Peoria to Peoria
North Las Vegas : NV : Las Vegas
Updated North Las Vegas to Las Vegas
Ft Worth : TX : Fort Worth
Updated Ft Worth to Fort Worth
North Little Rock : AR : Little Rock
Updated North Little Rock to Little Rock
Updated North Little Rock to Little Rock
Updated North Little Rock to Little Rock
Updated North Little Rock to Little Rock
Updated North Little Rock to Little Rock
Updated North Little Rock to Little Rock
East Lansing : MI : Lansing
Updated East Lansing to Lansing
Updated East Lansing to Lansing
Updated East Lansing to Lansing
Updated East Lansing to Lansing
West Des Moines : IA : Des Moines
Updated West Des Moines to Des Moines
South San Francisco : CA : San Francisco
Updated South San Francisco to San Francisco
East Providence : RI : Providence
Updated East Providence to Providence

In [40]:
# We now sample a record from the city of Columbus and from the state of Ohio

#df_filtered.head()
#df_filtered['STABBR'].unique()

df_sample = df_filtered[(df_filtered.CITY == 'Columbus') & (df_filtered.STABBR == 'OH')]

df_sample.sample(10)

,INSTNM,main,CURROPER,LONGITUDE,LATITUDE,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4
6254,ITT Technical Institute-Columbus,0,1,-82.8697,39.9343,Columbus,OH,11.0,3,2,3,NaN,NaN,NaN,NaN,NaN,27069.0,NaN,18048.0,18048.0,NaN,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.3273,0.0,0.3636,19072.0,3494.0,0.8478,0.8388,NaN,NaN,NaN,NaN,22800.0,NaN,NaN
6374,Aveda Institute-Columbus,1,1,-83.0141,39.9945,Columbus,OH,11.0,1,1,3,NaN,NaN,NaN,0.8056,NaN,NaN,19659.0,NaN,NaN,19750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0000,15060.0,7228.0,NaN,NaN,NaN,NaN,NaN,NaN,16905.0,NaN,0.6494
5685,Bexley Hall Episcopal Seminary,1,1,-82.9406,39.9562,Columbus,OH,21.0,4,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,8914.0,26081.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4592,Miami-Jacobs Career College-Columbus,0,1,-82.9969,39.9642,Columbus,OH,11.0,2,2,3,NaN,NaN,NaN,0.5366,0.1429,27179.0,NaN,11964.0,11964.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0000,14427.0,3983.0,NaN,NaN,NaN,NaN,NaN,NaN,22666.0,NaN,0.5000
6501,National College-Columbus,0,1,-82.9460,40.0848,Columbus,OH,11.0,2,2,3,NaN,NaN,NaN,0.4444,0.6667,25666.0,NaN,11550.0,11550.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.1000,0.0,0.0000,8254.0,6827.0,NaN,NaN,NaN,NaN,NaN,NaN,20713.0,NaN,0.0000
2994,The Spa School,1,1,-83.0187,40.0654,Columbus,OH,11.0,1,1,3,NaN,NaN,NaN,0.7833,NaN,NaN,17892.0,NaN,NaN,11500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0000,15789.0,3951.0,NaN,NaN,NaN,NaN,NaN,NaN,16240.0,NaN,0.7927
6285,Ohio Center for Broadcasting-Columbus,0,1,-82.8554,39.9553,Columbus,OH,21.0,1,1,3,NaN,NaN,NaN,0.3714,NaN,23834.0,NaN,15557.0,15557.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0000,9227.0,9093.0,NaN,NaN,NaN,NaN,NaN,NaN,20197.0,NaN,0.9583
6309,Regency Beauty Institute-Columbus,0,1,-83.0240,40.0650,Columbus,OH,11.0,1,1,3,NaN,NaN,NaN,0.6667,0.2857,NaN,25608.0,NaN,NaN,16200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0000,14811.0,8755.0,NaN,NaN,NaN,NaN,NaN,NaN,21197.0,NaN,0.2941
7714,Expertise Cosmetology Institute,0,1,NaN,NaN,Columbus,OH,NaN,0,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14015.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2993,Ohio State College of Barber Styling,1,1,-82.8776,39.9761,Columbus,OH,21.0,1,1,3,NaN,NaN,NaN,0.9063,NaN,NaN,14219.0,NaN,NaN,12510.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0000,82.0,1468.0,NaN,NaN,NaN,NaN,NaN,NaN,9499.0,NaN,0.7430

Finally, we can do a merger of the college scorecard and crimes dataframes. We are using an inner join for this because 
this will include colleges located in Metropolitan
State Areas with a record in the crimes dataframe. This allows 
us to filter the data by Metropolitan State Areas thus fullfilling
Janes requirement to experience the big city life. The assumption here 
is that by having a record in the crimes dataset, the specified location
is automatically a Metropolitan area as the crimes data was collected
and aggregated per Metropolitan State area.

In [41]:
# Merging Crimes DataFrame with Schools DataFrame
# create a dataset called 'df_with_crime_data' where you merge the 'df_filtered' dataset with the
# 'df_crime_2015' dataset on 'CITY'/'City' and 'STABBR'/'State'
# preview the 'df_with_crime_data' dataset
# ---
#
df_with_crime_data = pd.merge(left=df_filtered, right=df_crime_2015, left_on=['CITY', 'STABBR'], right_on=['City', 'State'])
df_with_crime_data.head()

,INSTNM,main,CURROPER,LONGITUDE,LATITUDE,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
0,University of Alabama at Birmingham,1,1,-86.8092,33.5022,Birmingham,AL,12.0,4,3,1,0.8016,0.5,0.5,NaN,NaN,19990.0,NaN,7206.0,16398.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0099,0.0632,0.0000,9033.0,17208.0,0.8673,0.8673,22.0,28.0,1146.0,14805.0,NaN,0.5377,NaN,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3,AL,Birmingham
1,Birmingham Southern College,1,1,-86.8536,33.5155,Birmingham,AL,12.0,3,3,2,0.8037,NaN,NaN,NaN,NaN,44512.0,NaN,30690.0,30690.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0033,0.0033,0.0000,11928.0,9990.0,0.6422,0.6422,23.0,29.0,1177.0,NaN,22994.0,0.6192,NaN,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3,AL,Birmingham
2,Herzing University-Birmingham,0,1,-86.8323,33.4681,Birmingham,AL,21.0,3,1,3,0.5000,NaN,NaN,NaN,NaN,26656.0,NaN,11150.0,11150.0,NaN,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0000,0.1304,0.0000,0.0163,8048.0,6942.0,0.7234,0.7490,NaN,NaN,NaN,NaN,22518.0,0.1778,NaN,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3,AL,Birmingham
3,Jefferson State Community College,1,1,-86.7074,33.6524,Birmingham,AL,12.0,2,2,1,NaN,NaN,NaN,0.5235,0.4415,12943.0,NaN,4260.0,7590.0,NaN,0.0,0.0,0.0,0.0,2.0,2.0,0.0,2.0,0.0045,0.0632,0.0000,0.0535,2670.0,4576.0,NaN,NaN,NaN,NaN,NaN,8799.0,NaN,NaN,0.0653,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3,AL,Birmingham
4,Lawson State Community College-Birmingham Campus,1,1,-86.8902,33.4517,Birmingham,AL,12.0,2,1,1,NaN,NaN,NaN,0.5251,0.2403,12602.0,NaN,4230.0,7590.0,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0287,0.0478,0.0000,0.1164,1576.0,5705.0,NaN,NaN,NaN,NaN,NaN,7406.0,NaN,NaN,0.1849,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3,AL,Birmingham

In [42]:
# Dropping duplicate city/state columns introduced by dataframe merger

df_with_crime_data.drop(['City', 'State'], axis = 1, inplace=True)

df_with_crime_data.head()

,INSTNM,main,CURROPER,LONGITUDE,LATITUDE,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft
0,University of Alabama at Birmingham,1,1,-86.8092,33.5022,Birmingham,AL,12.0,4,3,1,0.8016,0.5,0.5,NaN,NaN,19990.0,NaN,7206.0,16398.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0099,0.0632,0.0000,9033.0,17208.0,0.8673,0.8673,22.0,28.0,1146.0,14805.0,NaN,0.5377,NaN,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3
1,Birmingham Southern College,1,1,-86.8536,33.5155,Birmingham,AL,12.0,3,3,2,0.8037,NaN,NaN,NaN,NaN,44512.0,NaN,30690.0,30690.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0033,0.0033,0.0000,11928.0,9990.0,0.6422,0.6422,23.0,29.0,1177.0,NaN,22994.0,0.6192,NaN,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3
2,Herzing University-Birmingham,0,1,-86.8323,33.4681,Birmingham,AL,21.0,3,1,3,0.5000,NaN,NaN,NaN,NaN,26656.0,NaN,11150.0,11150.0,NaN,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0000,0.1304,0.0000,0.0163,8048.0,6942.0,0.7234,0.7490,NaN,NaN,NaN,NaN,22518.0,0.1778,NaN,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3
3,Jefferson State Community College,1,1,-86.7074,33.6524,Birmingham,AL,12.0,2,2,1,NaN,NaN,NaN,0.5235,0.4415,12943.0,NaN,4260.0,7590.0,NaN,0.0,0.0,0.0,0.0,2.0,2.0,0.0,2.0,0.0045,0.0632,0.0000,0.0535,2670.0,4576.0,NaN,NaN,NaN,NaN,NaN,8799.0,NaN,NaN,0.0653,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3
4,Lawson State Community College-Birmingham Campus,1,1,-86.8902,33.4517,Birmingham,AL,12.0,2,1,1,NaN,NaN,NaN,0.5251,0.2403,12602.0,NaN,4230.0,7590.0,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0287,0.0478,0.0000,0.1164,1576.0,5705.0,NaN,NaN,NaN,NaN,NaN,7406.0,NaN,NaN,0.1849,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3

In [43]:
# Checking the shape

df_with_crime_data.shape

(2663, 54)

In [44]:
# Checking the number of missing values


df_with_crime_data.isnull().values.sum()
df_with_crime_data.isnull().sum()

INSTNM                  0
main                    0
CURROPER                0
LONGITUDE             276
LATITUDE              276
CITY                    0
STABBR                  0
LOCALE                151
HIGHDEG                 0
PREDDEG                 0
CONTROL                 0
RET_FT4              1841
RET_PT4              2109
RET_PT4              2109
RET_FTL4             1408
RET_PTL4             2007
COSTT4_A             1306
COSTT4_P             1775
TUITIONFEE_IN        1197
TUITIONFEE_OUT       1277
TUITIONFEE_PROG      1714
CIP10BACHL            151
CIP11BACHL            151
CIP14BACHL            151
CIP15BACHL            151
CIP10ASSOC            151
CIP11ASSOC            151
CIP14ASSOC            151
CIP15ASSOC            151
PCIP10                271
PCIP11                271
PCIP14                271
PCIP15                271
TUITFTE               158
INEXPFTE              158
ADM_RATE             1905
ADM_RATE_ALL         1811
ACTCM25              2197
ACTCM75              2197
SAT_AVG_ALL          2159
NPT4_PUB             2153
NPT4_PRIV             928
C150_4               1799
C150_L4              1392
MSA                     0
ViolentCrime            6
Murder                  0
Rape                    0
Robbery                 0
AggravatedAssault       6
PropertyCrime         135
Burglary               61
Theft                 100
MotorVehicleTheft       0
dtype: int64

The Kauffman Start-Up Index data has data depicting information about startup activity nationwide, per state and per Metropolitan State Area all jumbled up into one single dataset. We need to filter out all the noise and just remain with data containing information about startups for Metropolitan State Areas only as per Jane's requirements

In [45]:
# Filtering Kauffman Start-Up data to remain with data for just the MSAs

df_kauffman_startup_index_filtered = df_kauffman_startup_index[
                                                               (df_kauffman_startup_index['Category'] == 'MSA')
                                                               ].reset_index(drop=True)
df_kauffman_startup_index_filtered.head()

,year_CPS,Characteristic,OppShare_New_Entrp,Breakdown,Rate_New_Entrp,Location,startup_index,Index Year,year_BDS,startup_density,Rank,Composition_of_New_Entrp,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text
0,2012.0,NaN,0.7022,NaN,0.0046,12060,NaN,2013.0,2010.0,91.309998,9.0,NaN,71.428574,54.020164,63.735756,7.339449,-2.695530,-0.289292,3.0,-6.0,2.97,-1.52,Metro Profile,Atlanta-Sandy Springs-Marietta,MSA,7.022,460.0,the metropolitan area of,a large decrease
1,2015.0,NaN,0.7036,NaN,0.0037,12060,NaN,2016.0,2013.0,91.570000,15.0,NaN,54.000000,25.329153,58.575954,3.211009,-2.656424,-0.266840,14.0,-1.0,0.08,0.02,Metro Profile,Atlanta-Sandy Springs-Marietta,MSA,7.036,370.0,the metropolitan area of,basically no changes
2,2014.0,NaN,0.6904,NaN,0.0037,12060,NaN,2015.0,2012.0,95.129997,14.0,NaN,55.813953,29.029156,64.205849,3.211009,-3.025139,0.040587,17.0,3.0,-0.59,0.67,Metro Profile,Atlanta-Sandy Springs-Marietta,MSA,6.904,370.0,the metropolitan area of,a slight increase
3,1989.0,NaN,NaN,NaN,NaN,12060,NaN,1990.0,1987.0,150.589996,NaN,NaN,NaN,NaN,73.267914,NaN,NaN,4.829878,NaN,NaN,NaN,NaN,Metro Profile,Atlanta-Sandy Springs-Marietta,MSA,NaN,NaN,the metropolitan area of,.
4,2008.0,NaN,NaN,NaN,0.0056,12060,NaN,2009.0,2006.0,126.949997,NaN,NaN,100.000000,NaN,61.319107,11.926605,NaN,2.788428,NaN,NaN,NaN,NaN,Metro Profile,Atlanta-Sandy Springs-Marietta,MSA,NaN,560.0,the metropolitan area of,.

In [46]:
# Checking the shape

df_kauffman_startup_index_filtered.shape

(1530, 29)

In [47]:
# Previewing dataset info using info() method

df_kauffman_startup_index_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year_CPS                  1520 non-null   float64
 1   Characteristic            0 non-null      object
 2   OppShare_New_Entrp        274 non-null    float64
 3   Breakdown                 0 non-null      object
 4   Rate_New_Entrp            360 non-null    float64
 5   Location                  1530 non-null   int64
 6   startup_index             0 non-null      float64
 7   Index Year                1520 non-null   float64
 8   year_BDS                  1520 non-null   float64
 9   startup_density           1520 non-null   float64
 10  Rank                      274 non-null    float64
 11  Composition_of_New_Entrp  0 non-null      float64
 12  norm_rate                 360 non-null    float64
 13  norm_opp                  274 non-null    float64
 14  norm_density              1520 non-null   float64
 15  z_rate                    360 non-null    float64
 16  z_oppshare                274 non-null    float64
 17  z_startup_den             1520 non-null   float64
 18  rank_last_y               234 non-null    float64
 19  rank_diff                 234 non-null    float64
 20  index_last_y              234 non-null    float64
 21  index_diff                234 non-null    float64
 22  dataset                   1520 non-null   object
 23  Location_name             1530 non-null   object
 24  Category                  1530 non-null   object
 25  OppShare_New_Entrp_web    274 non-null    float64
 26  Rate_New_Entrp_web        360 non-null    float64
 27  location_category         1530 non-null   object
 28  index_diff_text           1530 non-null   object
dtypes: float64(21), int64(1), object(7)
memory usage: 346.8+ KB

The common columns between the Kauffman Start Up index data and our dataframe with crime data included are the location_name column in the kauffman dataframe and the MSA column introduced to our college scorecard dataframe by the merger with the crimes dataframe. Both these columns contain an entry for the name of the Metropolitan State Area for which the data was collected. From Kauffman data, we also have dataset that matches a Metropoliatan State Area code used to identify it and this code has been used as the value to the location column in the Kauffman start-up index. We can therefore merge the Kauffman dataframe with the new college scorecard dataframe using the MSA Code as value to use for the merger but we have to introduce this MSA Code to the college scorecard dataframe first.

In [48]:
# Extracting the MSA names from the new college scorecard dataframe with crime data included
# ---
#
df_with_crime_data_msas = df_with_crime_data['MSA'].unique()

In [49]:
# Loading the dataset containing MSA names and their matching codes as per Kauffman dataset
# NB: During this step, we can also use other
# ---
#
msa_codes_url = '/content/drive/My Drive/Datascience/exercises-data-wrangling-exercise-1/KaufmanIndexData/MSAcodes.csv'

df_msa_codes = pd.read_csv(msa_codes_url)

In [50]:
# Previewing the 'df_msa_codes' dataset
df_msa_codes.head()

   MSA Code                                    MSA Name
0         0         'Not Identified or Nonmetropolitan'
1       460          'Appleton-Oshkosh-Neenah, WI MSA*'
2      3000    'Grand Rapids-Muskegon-Holland, MI MSA*'
3      3160  'Greenville-Spartanburg-Anderson, SC MSA*'
4      3610                        'Jamestown, NY MSA*'

In [51]:
# Removing apostrophes (') in the MSA Name column
df_msa_codes['MSA Name'] = df_msa_codes['MSA Name'].apply(lambda row: row.strip("'"))

In [52]:
# Previewing the 'df_msa_codes' dataset

df_msa_codes.head()

   MSA Code                                  MSA Name
0         0         Not Identified or Nonmetropolitan
1       460          Appleton-Oshkosh-Neenah, WI MSA*
2      3000    Grand Rapids-Muskegon-Holland, MI MSA*
3      3160  Greenville-Spartanburg-Anderson, SC MSA*
4      3610                        Jamestown, NY MSA*

In [53]:
"""
We then use the utility function created earlier to find possibly matching MSA names
between the MSA column in our new college scorecard dataframe and the loaded MSA_name/code
dataframe as per Kauffman. Doing this will allow us to add MSA Codes to our college scorecard dataframe
that will then be used to merge the dataframe with the kauffman startup index dataframe.
"""
possibly_matching_MSAs = get_possible_matching_strings(df_with_crime_data_msas, df_msa_codes['MSA Name'])

In [54]:
# Showing the output of 'possibly_matching_MSAs' / previewing

possibly_matching_MSAs.head()

,original,best_match,probability
0,"Birmingham-Hoover, AL M.S.A.","Birmingham-Hoover, AL",95
1,"Montgomery, AL M.S.A.","Montgomery, AL",95
2,"Huntsville, AL M.S.A.","Huntsville, AL",95
3,"Tuscaloosa, AL M.S.A.","Columbus, GA-AL (Harris County, GA not in sample)",86
4,"Gadsden, AL M.S.A.","Columbus, GA-AL (Harris County, GA not in sample)",86

In [55]:
"""
Load manually matched city MSA codes
---
The above match between df_with_crime_data_msas dataset and df_msas 
as per the kauffman index dataset results in possibly matching MSAs
but which have a low probability value for a match. This therefore requires 
manual intervention and as a result, a csv was created to specifically match
this MSAs. The created csv is the one being loaded below.
"""
manual_msa_codes_url = '/content/drive/My Drive/Datascience/exercises-data-wrangling-exercise-1/KaufmanIndexData/manually_matched_msa_codes.csv'
df_manual_msa_codes = pd.read_csv(manual_msa_codes_url)
df_manual_msa_codes

,original,best_match,probability
0,"Battle Creek, MI M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",100
1,"Boise City, ID M.S.A","Boise City-Nampa, ID (Owyhee County not in sam...",100
2,"Bloomington, IL M.S.A.",Bloomington-Normal IL,100
3,"Bloomington, IN M.S.A","Bloomington, IN (Owen County not in sample)",100
4,"Waterloo-Cedar Falls, IA M.S.A.","Cedar Rapids, IA (Benton and Jones Counties no...",100
5,"Kansas City, MO-KS M.S.A.","Kansas City, MO-KS (Franklin, KS; Leavenworth,...",100
6,"Houma-Thibodaux, LA M.S.A.","Houma-Bayou Cane-Thibodaux, LA",100
7,"Baltimore-Columbia-Towson, MD M.S.A.","Baltimore-Towson, MD",100
8,"Muskegon, MI M.S.A","Grand Rapids-Muskegon-Holland, MI MSA*",100
9,"Gulfport-Biloxi-Pascagoula, MS M.S.A.","Gulfport-Biloxi, MS",100
10,"Columbia, MO M.S.A","Columbia, MO (Howard County not in sample)",100
11,"Billings, MT M.S.A.","Billings, MT (Carbon County not in sample)",100
12,"Reno, NV M.S.A.","Reno-Sparks, NV",100
13,"Asheville, NC M.S.A.","Asheville, NC (Haywood and Henderson Counties ...",100
14,"Kingsport-Bristol-Bristol, TN-VA M.S.A.","Kingsport-Bristol, TN-VA (Virginia portion not...",100
15,"Amarillo, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",100
16,"Charleston, WV M.S.A.","Charleston, WV (Clay County not in sample)",100
17,"Appleton, WI M.S.A.","Appleton-Oshkosh-Neenah, WI MSA*",100
18,"Albany, GA M.S.A.","Albany, GA (Baker, Terrell, and Worth Counties...",100
19,"Boise City, ID M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",100
20,"Duluth, MN-WI M.S.A.","Duluth, MN-WI (Carlton County, MN not in sampl...",100
21,"Tuscaloosa, AL M.S.A.","Tuscaloosa, AL (Greene and Hale Counties not i...",100
22,"Florence-Muscle Shoals, AL M.S.A.","Florence, AL",100
23,"Little Rock-North Little Rock-Conway, AR M.S.A.","Little Rock-North Little Rock, AR (Perry Count...",100
24,"Fort Smith, AR-OK M.S.A.","Fort Smith, AR-OK (Oklahoma portion not in sam...",100
25,"San Francisco-Oakland-Hayward, CA M.S.A.","San Francisco-Oakland-Fremont, CA",100
26,San Francisco-Redwood City-South San Francisco...,"San Francisco-Oakland-Fremont, CA",100
27,"Oakland-Hayward-Berkeley, CA M.D.","San Francisco-Oakland-Fremont, CA",100
28,"Santa Maria-Santa Barbara, CA M.S.A.","Santa Barbara-Santa Maria-Goleta, CA",100
29,"Los Angeles-Long Beach-Anaheim, CA M.S.A.","Los Angeles-Long Beach-Santa Ana, CA",100
30,"Los Angeles-Long Beach-Glendale, CA M.D.","Los Angeles-Long Beach-Santa Ana, CA",100
31,"San Diego-Carlsbad, CA M.S.A.","San Diego-Carlsbad-San Marcos, CA",100
32,"Anaheim-Santa Ana-Irvine, CA M.D.","Los Angeles-Long Beach-Santa Ana, CA",100
33,"Riverside-San Bernardino-Ontario, CA M.S.A.","Riverside-San Bernardino, CA",100
34,"San Luis Obispo-Paso Robles-Arroyo Grande, CA ...","San Luis Obispo-Paso Robles, CA",100
35,"San Rafael, CA M.D.","San Francisco-Oakland-Fremont, CA",100
36,"Santa Rosa, CA M.S.A.","Santa Rosa-Petaluma, CA",100
37,"Stockton-Lodi, CA M.S.A.","Stockton, CA",100
38,"Denver-Aurora-Lakewood, CO M.S.A.3, 4","Denver-Aurora, CO",100
39,"Fort Collins, CO M.S.A.","Fort Collins-Loveland, CO",100
40,"Norwich-New London, CT M.S.A.","Norwich-New London, CT-RI (RI portion recoded ...",100
41,"Wilmington, DE-MD-NJ M.D.2","Philadelphia-Camden-Wilmington, PA-NJ-DE",100
42,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...","Washington-Arlington-Alexandria, DC-VA-MD-WV (...",100
43,"Fort Lauderdale-Pompano Beach-Deerfield Beach,...","Miami-Fort Lauderdale-Miami Beach, FL",100
44,"Miami-Miami Beach-Kendall, FL M.D.","Miami-Fort Lauderdale-Miami Beach, FL",100
45,"Panama City, FL M.S.A.","Panama City-Lynn Haven, FL",100
46,"Orlando-Kissimmee-Sanford, FL M.S.A.","Orlando, FL",100
47,"Naples-Immokalee-Marco Island, FL M.S.A.","Naples-Marco Island, FL",100
48,"Gainesville, FL M.S.A.","Gainesville, FL (Gilchrist County not in sample)",100
49,"West Palm Beach-Boca Raton-Delray Beach, FL M.D.","Palm Bay-Melbourne-Titusville, FL",100
50,"Atlanta-Sandy Springs-Roswell, GA M.S.A.","Atlanta-Sandy Springs-Marietta, GA (Haralson, ...",100
51,"Columbus, GA-AL M.S.A.","Columbus, GA-AL (Harris County, GA not in sample)",100
52,"Athens-Clarke County, GA M.S.A.","Athens-Clark County, GA (Oglethorpe County not...",100
53,"Macon-Bibb County, GA M.S.A.","Macon,, GA (Crawford, Monroe, and Twiggs Count...",100
54,"Kahului-Wailuku-Lahaina, HI M.S.A.","Honolulu, HI",100
55,"Chicago-Naperville-Elgin, IL-IN-WI M.S.A.","Chicago-Naperville-Joliet, IN-IN-WI (DeKalb, I...",100
56,"Chicago-Naperville-Arlington Heights, IL M.D.","Chicago-Naperville-Joliet, IN-IN-WI (DeKalb, I...",100
57,"Elgin, IL M.D","Chicago-Naperville-Joliet, IN-IN-WI (DeKalb, I...",100
58,"Evansville, IN-KY M.S.A.","Evansville, IN-KY (Gibson County, IN and Kentu...",100
59,"South Bend-Mishawaka, IN-MI M.S.A.","South Bend-Mishawaka, IN-MI (Michigan portion ...",100
60,"Nashville-Davidson–Murfreesboro–Franklin, TN M...","Nashville-Davidson-Murfreesboro, TN (Cannon, H...",100
61,"Des Moines-West Des Moines, IA M.S.A.","Des Moines, IA",100
62,"Sioux City, IA-NE-SD M.S.A.2","Sioux Falls, SD",100
63,"Cedar Rapids, IA M.S.A.","Cedar Rapids, IA (Benton and Jones Counties no...",100
64,"Iowa City, IA M.S.A.","Iowa City, IA (Washington County not in sample)",100
65,"Topeka, KS M.S.A.","Topeka, KS (Jackson and Jefferson Counties not...",100
66,"Louisville/Jefferson County, KY-IN M.S.A.","Louisville, KY-IN (Washington, IN; Henry, KY; ...",100
67,"Shreveport-Bossier City, LA M.S.A.","Shreveport-Bossier City, LA (De Soto Parish no...",100
68,"New Orleans-Metairie, LA M.S.A.","New Orleans-Metairie-Kenner, LA",100
69,"Lake Charles, LA M.S.A.2","Lake Charles, LA (Cameron Parish not in sample)",100
70,"Hagerstown-Martinsburg, MD-WV M.S.A.","Hagerstown-Martinsburg, MD-WV (Berkeley County...",100
71,"Springfield, MA M.S.A.","Springfield, MA-CT (Connecticut portion not id...",100
72,"Worcester, MA-CT M.S.A.","Worcester, MA-CT (Connecticut portion not iden...",100
73,"Minneapolis-St. Paul-Bloomington, MN-WI M.S.A.","Minneapolis-St Paul-Bloomington, MN-WI (Wiscon...",100
74,"Springfield, MO M.S.A.","Springfield, MO (Dallas and Polk Counties not ...",100
75,"Columbia, MO M.S.A.","Columbia, MO (Howard County not in sample)",100
76,"Manchester-Nashua, NH M.S.A.","Manchester, NH",100
77,"Camden, NJ M.D.2","Philadelphia-Camden-Wilmington, PA-NJ-DE",100
78,"Vineland-Bridgeton, NJ M.S.A.2","Vineland-Millville-Bridgeton, NJ",100
79,"Trenton, NJ M.S.A.2","Trenton-Ewing, NJ",100
80,"Buffalo-Cheektowaga-Niagara Falls, NY M.S.A.","Buffalo-Niagara Falls, NY",100
81,"Fargo, ND-MN M.S.A.","Fargo, ND-MN (MN portion not identified)",100
82,"Cincinnati, OH-KY-IN M.S.A.","Cincinnati-Middletown, OH-KY-IN (Franklin Coun...",100
83,"Columbus, OH M.S.A.2","Columbus, OH (Morrow County not in sample)",100
84,"Toledo, OH M.S.A.2","Toledo, OH (Ottawa County not in sample)",100
85,"Tulsa, OK M.S.A.2","Tulsa, OK (Okmulgee County not in sample)",100
86,"Eugene, OR M.S.A.","Eugene-Springfield, OR",100
87,"Philadelphia, PA M.D.","Philadelphia-Camden-Wilmington, PA-NJ-DE",100
88,"Providence-Warwick, RI-MA M.S.A.","Providence-Fall River-Warwick, MA-RI",100
89,"Memphis, TN-MS-AR M.S.A.","Memphis, TN-MS-AR (Arkansas portion not identi...",100
90,"Knoxville, TN M.S.A.","Knoxville, TN (Anderson County not in sample)",100
91,"Houston-The Woodlands-Sugar Land, TX M.S.A.3","Houston-Baytown-Sugar Land, TX",100
92,"San Antonio-New Braunfels, TX M.S.A.","San Antonio, TX",100
93,"Killeen-Temple, TX M.S.A.","Killeen-Temple-Fort Hood, TX",100
94,"Dallas-Fort Worth-Arlington, TX M.S.A.2","Dallas-Fort Worth-Arlington, TX (Delta and Hun...",100
95,"Dallas-Plano-Irving, TX M.D.","Dallas-Fort Worth-Arlington, TX (Delta and Hun...",100
96,"Fort Worth-Arlington, TX M.D.2","Dallas-Fort Worth-Arlington, TX (Delta and Hun...",100
97,"Beaumont-Port Arthur, TX M.S.A.","Beaumont-Port Author, TX",100
98,"Longview, TX M.S.A.","Longview, TX (Rusk and Upshur Counties not in ...",100
99,"Lubbock, TX M.S.A.","Lubbock, TX (Crosby County not in sample)",100
100,"McAllen-Edinburg-Mission, TX M.S.A.2","McAllen-Edinburg-Pharr, TX",100
101,"Provo-Orem, UT M.S.A.","Provo-Orem, UT (Juab County not in sample)",100
102,"Salt Lake City, UT M.S.A.","Salt Lake City, UT (Toole County not in sample)",100
103,"Roanoke, VA M.S.A.","Roanoke, VA (Craig and Franklin Counties not i...",100
104,"Virginia Beach-Norfolk-Newport News, VA-NC M.S.A.","Virginia Beach-Norfolk-Newport News, VA-NC (No...",100
105,"Lynchburg, VA M.S.A.","Lynchburg, VA (Appomattox and Bedford Counties...",100
106,"Richmond, VA M.S.A.","Richmond, VA (Cumberland County not in sample)",100
107,"Seattle-Bellevue-Everett, WA M.D.2","Seattle-Tacoma-Bellevue, WA",100
108,"Olympia-Tumwater, WA M.S.A.","Olympia, WA",100
109,"Spokane-Spokane Valley, WA M.S.A.","Spokane, WA",100
110,"Tacoma-Lakewood, WA M.D.","Seattle-Tacoma-Bellevue, WA",100
111,"Green Bay, WI M.S.A.","Green Bay, WI (Oconto County not in sample)",100
112,"La Crosse-Onalaska, WI-MN M.S.A.","La Crosse, WI (Houston County not in sample)",100
113,"Saginaw, MI M.S.A.","Saginaw-Saginaw Township North, MI",100
114,"St. Louis, MO-IL M.S.A.2","St. Louis, MO-IL (Calhoun County, IL not in sa...",100

In [56]:
final_possibly_matching_MSAs = pd.concat([possibly_matching_MSAs, df_manual_msa_codes], axis=0).reset_index(drop=True)

In [57]:
final_possibly_matching_MSAs

,original,best_match,probability
0,"Birmingham-Hoover, AL M.S.A.","Birmingham-Hoover, AL",95
1,"Montgomery, AL M.S.A.","Montgomery, AL",95
2,"Huntsville, AL M.S.A.","Huntsville, AL",95
3,"Tuscaloosa, AL M.S.A.","Columbus, GA-AL (Harris County, GA not in sample)",86
4,"Gadsden, AL M.S.A.","Columbus, GA-AL (Harris County, GA not in sample)",86
5,"Dothan, AL M.S.A.","Columbus, GA-AL (Harris County, GA not in sample)",86
6,"Florence-Muscle Shoals, AL M.S.A.","Anniston-Oxford, AL",86
7,"Mobile, AL M.S.A.5","Mobile, AL",90
8,"Daphne-Fairhope-Foley, AL M.S.A.","Anniston-Oxford, AL",86
9,"Anchorage, AK M.S.A.","Anchorage, AK",95
10,"Fairbanks, AK M.S.A.","Yakima, WA",54
11,"Phoenix-Mesa-Scottsdale, AZ M.S.A.","Phoenix-Mesa-Scottsdale, AZ",95
12,"Tucson, AZ M.S.A.","Tucson, AZ",90
13,"Flagstaff, AZ M.S.A.","Prescott, AZ",86
14,"Yuma, AZ M.S.A.","Phoenix-Mesa-Scottsdale, AZ",86
15,"Lake Havasu City-Kingman, AZ M.S.A.","Atlantic City, NJ",86
16,"Prescott, AZ M.S.A.","Prescott, AZ",90
17,"Albuquerque, NM M.S.A.","Albuquerque, NM",95
18,"Little Rock-North Little Rock-Conway, AR M.S.A.","Austin-Round Rock, TX",86
19,"Fort Smith, AR-OK M.S.A.","Dallas-Fort Worth-Arlington, TX (Delta and Hun...",86
20,"Pine Bluff, AR M.S.A","Fayetteville- Springdale-Rogers, AR-MO (Madiso...",86
21,"Jonesboro, AR M.S.A.","Fayetteville- Springdale-Rogers, AR-MO (Madiso...",86
22,"San Francisco-Oakland-Hayward, CA M.S.A.","Bakersfield, CA",86
23,"Oakland-Hayward-Berkeley, CA M.D.","Bakersfield, CA",86
24,"Santa Maria-Santa Barbara, CA M.S.A.","Bakersfield, CA",86
25,"Los Angeles-Long Beach-Anaheim, CA M.S.A.","Bakersfield, CA",86
26,"Sacramento–Roseville–Arden-Arcade, CA M.S.A.","Sacramento--Arden-Arcade Roseville, CA",95
27,"San Diego-Carlsbad, CA M.S.A.","Bakersfield, CA",86
28,"Bakersfield, CA M.S.A.","Bakersfield, CA",95
29,"Anaheim-Santa Ana-Irvine, CA M.D.","Bakersfield, CA",86
30,"Riverside-San Bernardino-Ontario, CA M.S.A.","Bakersfield, CA",86
31,"San Luis Obispo-Paso Robles-Arroyo Grande, CA ...","Bakersfield, CA",86
32,"Chico, CA M.S.A.","Chico, CA",90
33,"Fresno, CA M.S.A.","Fresno, CA",90
34,"Santa Cruz-Watsonville, CA M.S.A.","Santa-Cruz-Watsonville, CA",95
35,"Modesto, CA M.S.A.","Modesto, CA",90
36,"Vallejo-Fairfield, CA M.S.A.","Vallejo-Fairfield, CA",95
37,"San Jose-Sunnyvale-Santa Clara, CA M.S.A.","San Jose-Sunnyvale-Santa Clara, CA",95
38,"El Centro, CA M.S.A.","El Centro, CA",95
39,"Salinas, CA M.S.A.","Salinas, CA",90
40,"Visalia-Porterville, CA M.S.A.","Visalia-Porterville, CA",95
41,"San Rafael, CA M.D.","Chico, CA",86
42,"Santa Rosa, CA M.S.A.","Chico, CA",86
43,"Stockton-Lodi, CA M.S.A.","Bakersfield, CA",86
44,"Merced, CA M.S.A.","Merced, CA",90
45,"Oxnard-Thousand Oaks-Ventura, CA M.S.A.","Oxnard-Thousand Oaks-Ventura, CA",95
46,"Napa, CA M.S.A.","Napa, CA",90
47,"Redding, CA M.S.A.","Chico, CA",86
48,"Grand Junction, CO M.S.A.","Grand Rapids-Muskegon-Holland, MI MSA*",86
49,"Greeley, CO M.S.A.","Greeley, CO",90
50,"Denver-Aurora-Lakewood, CO M.S.A.3, 4","Boulder, CO",86
51,"Colorado Springs, CO M.S.A.","Colorado Springs, CO",95
52,"Boulder, CO M.S.A.3","Boulder, CO",90
53,"Fort Collins, CO M.S.A.","Boulder, CO",86
54,"Pueblo, CO M.S.A.","Pueblo, CO",90
55,"Bridgeport-Stamford-Norwalk, CT M.S.A.","Bridgeport-Stamford-Norwalk, CT",95
56,"Hartford-West Hartford-East Hartford, CT M.S.A.","Hartford-West Hartford-East Hartford, CT",95
57,"Norwich-New London, CT M.S.A.","New York-Northern New Jersey-Long Island, NY-N...",86
58,"Wilmington, DE-MD-NJ M.D.2","Atlantic City, NJ",86
59,"Dover, DE M.S.A.","Dover, DE",90
60,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...","Baltimore-Towson, MD",86
61,"Fort Lauderdale-Pompano Beach-Deerfield Beach,...","Cape Coral-Fort Myers, FL",86
62,"Miami-Fort Lauderdale-West Palm Beach, FL M.S.A.","Miami-Fort Lauderdale-Miami Beach, FL",95
63,"Panama City, FL M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
64,"Deltona-Daytona Beach-Ormond Beach, FL M.S.A.","Deltona-Daytona Beach-Ormond Beach, FL",95
65,"Ocala, FL M.S.A.","Ocala, FL",90
66,"Orlando-Kissimmee-Sanford, FL M.S.A.","Jacksonville, FL",86
67,"Naples-Immokalee-Marco Island, FL M.S.A.","Cape Coral-Fort Myers, FL",86
68,"Jacksonville, FL M.S.A.","Jacksonville, FL",95
69,"Tallahassee, FL M.S.A.","Tallahassee, FL",95
70,"Tampa-St. Petersburg-Clearwater, FL M.S.A.","Tampa-St. Petersburg-Clearwater, FL",95
71,"Palm Bay-Melbourne-Titusville, FL M.S.A.","Palm Bay-Melbourne-Titusville, FL",95
72,"Pensacola-Ferry Pass-Brent, FL M.S.A.","Pensacola-Ferry Pass-Brent, FL",95
73,"Gainesville, FL M.S.A.","Deltona-Daytona Beach-Ormond Beach, FL",86
74,"Lakeland-Winter Haven, FL M.S.A.","Lakeland-Winter Haven, FL",95
75,"West Palm Beach-Boca Raton-Delray Beach, FL M.D.","Cape Coral-Fort Myers, FL",86
76,"North Port-Sarasota-Bradenton, FL M.S.A.","Beaumont-Port Author, TX",86
77,"Albany, GA M.S.A.","Albany, GA (Baker, Terrell, and Worth Counties...",86
78,"Savannah, GA M.S.A.","Savannah, GA",90
79,"Atlanta-Sandy Springs-Roswell, GA M.S.A.","Albany, GA (Baker, Terrell, and Worth Counties...",86
80,"Brunswick, GA M.S.A.","Albany, GA (Baker, Terrell, and Worth Counties...",86
81,"Columbus, GA-AL M.S.A.","Albany, GA (Baker, Terrell, and Worth Counties...",86
82,"Rome, GA M.S.A.","Albany, GA (Baker, Terrell, and Worth Counties...",86
83,"Dalton, GA M.S.A.","Albany, GA (Baker, Terrell, and Worth Counties...",86
84,"Athens-Clarke County, GA M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
85,"Macon-Bibb County, GA M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
86,"Urban Honolulu, HI M.S.A.","Honolulu, HI",90
87,"Kahului-Wailuku-Lahaina, HI M.S.A.","Honolulu, HI",86
88,"Boise City, ID M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
89,"Idaho Falls, ID M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
90,"Pocatello, ID M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
91,"Lewiston, ID-WA M.S.A.","Bellingham, WA",86
92,"Coeur d'Alene, ID M.S.A.","Coeur d''Alene, ID",95
93,"Chicago-Naperville-Elgin, IL-IN-WI M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
94,"Peoria, IL M.S.A.","Peoria, IL",90
95,"Elgin, IL M.D.",Bloomington-Normal IL,86
96,"Danville, IL M.S.A.","Champaign-Urbana, IL (Ford County not in sample)",86
97,"Bloomington, IL M.S.A.","Bloomington, IN (Owen County not in sample)",86
98,"Springfield, IL M.S.A.","Springfield, IL",95
99,"Rockford, IL M.S.A.","Rockford, IL",90
100,"Indianapolis-Carmel-Anderson, IN M.S.A.","Anderson, IN",90
101,"Fort Wayne, IN M.S.A.","Fort Wayne, IN",95
102,"Evansville, IN-KY M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
103,"Kokomo, IN M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
104,"South Bend-Mishawaka, IN-MI M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
105,"Gary, IN M.D.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
106,"Nashville-Davidson–Murfreesboro–Franklin, TN M...","Chattanooga, TN-GA",86
107,"Michigan City-La Porte, IN M.S.A.","Michigan City-La Porte, IN",95
108,"Elkhart-Goshen, IN M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
109,"Kalamazoo-Portage, MI M.S.A.","Kalamazoo-Portage, MI",95
110,"Waterloo-Cedar Falls, IA M.S.A.","Cedar Rapids, IA (Benton and Jones Counties no...",86
111,"Des Moines-West Des Moines, IA M.S.A.","Cedar Rapids, IA (Benton and Jones Counties no...",86
112,"Sioux City, IA-NE-SD M.S.A.2","Atlantic City, NJ",86
113,"Dubuque, IA M.S.A.","Cedar Rapids, IA (Benton and Jones Counties no...",86
114,"Cedar Rapids, IA M.S.A.","Grand Rapids-Muskegon-Holland, MI MSA*",86
115,"Davenport-Moline-Rock Island, IA-IL M.S.A.","Davenport-Moline-Rock Island, IA-IL",95
116,"Ames, IA M.S.A.","Cedar Rapids, IA (Benton and Jones Counties no...",86
117,"Iowa City, IA M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
118,"Topeka, KS M.S.A.","Kansas City, MO-KS (Franklin, KS; Leavenworth,...",86
119,"Manhattan, KS M.S.A.","Kansas City, MO-KS (Franklin, KS; Leavenworth,...",86
120,"Wichita, KS M.S.A.6","Wichita, KS",90
121,"Kansas City, MO-KS M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
122,"Louisville/Jefferson County, KY-IN M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
123,"Bowling Green, KY M.S.A.","Bowling Green, KY",95
124,"Owensboro, KY M.S.A.","Cincinnati-Middletown, OH-KY-IN (Franklin Coun...",86
125,"Lexington-Fayette, KY M.S.A.","Lexington-Fayette, KY",95
126,"Elizabethtown-Fort Knox, KY M.S.A.","Bowling Green, KY",86
127,"Alexandria, LA M.S.A.","Houma-Bayou Cane-Thibodaux, LA",86
128,"Shreveport-Bossier City, LA M.S.A.","Atlantic City, NJ",86
129,"Baton Rouge, LA M.S.A.","Baton Rouge, LA",95
130,"New Orleans-Metairie, LA M.S.A.","Baton Rouge, LA",86
131,"Monroe, LA M.S.A.2","Monroe, LA",90
132,"Lake Charles, LA M.S.A.2","Baton Rouge, LA",86
133,"Lafayette, LA M.S.A.","Lafayette, LA",95
134,"Houma-Thibodaux, LA M.S.A.","Baton Rouge, LA",86
135,"Hammond, LA M.S.A.","Houma-Bayou Cane-Thibodaux, LA",86
136,"Portland-South Portland, ME M.S.A.","Portland-South Portland, ME",95
137,"Bangor, ME M.S.A.","Bangor, ME",90
138,"Cumberland, MD-WV M.S.A.","Charleston, WV (Clay County not in sample)",86
139,"Hagerstown-Martinsburg, MD-WV M.S.A.","Baltimore-Towson, MD",86
140,"Baltimore-Columbia-Towson, MD M.S.A.","Baltimore-Towson, MD",86
141,"Salisbury, MD-DE M.S.A.","Salisbury, MD",90
142,"Silver Spring-Frederick-Rockville, MD M.D.","Baltimore-Towson, MD",86
143,"Worcester, MA-CT M.S.A.","Danbury, CT",86
144,"Pittsfield, MA M.S.A.","Boston-Cambridge-Quincy, MA-NH",86
145,"Grand Rapids-Wyoming, MI M.S.A.","Grand Rapids-Wyoming, MI",95
146,"Flint, MI M.S.A.","Flint, MI",90
147,"Bay City, MI M.S.A.","Grand Rapids-Muskegon-Holland, MI MSA*",86
148,"Ann Arbor, MI M.S.A.","Ann Arbor, MI",95
149,"Detroit-Warren-Dearborn, MI M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
150,"Lansing-East Lansing, MI M.S.A.","Lansing-East Lansing, MI",95
151,"Jackson, MI M.S.A.","Jackson, MI",90
152,"Battle Creek, MI M.S.A.","Grand Rapids-Muskegon-Holland, MI MSA*",86
153,"Warren-Troy-Farmington Hills, MI M.D.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
154,"Muskegon, MI M.S.A.","Grand Rapids-Muskegon-Holland, MI MSA*",86
155,"Midland, MI M.S.A.","Grand Rapids-Muskegon-Holland, MI MSA*",86
156,"Minneapolis-St. Paul-Bloomington, MN-WI M.S.A.","Appleton,WI",86
157,"Mankato-North Mankato, MN M.S.A.","Duluth, MN-WI (Carlton County, MN not in sampl...",86
158,"Duluth, MN-WI M.S.A.","Appleton-Oshkosh-Neenah, WI MSA*",86
159,"Rochester, MN M.S.A.","Portsmouth-Rochester, NH-ME MSA* (ME portion n...",86
160,"St. Cloud, MN M.S.A.","St. Cloud, MN",95
161,"Gulfport-Biloxi-Pascagoula, MS M.S.A.","Gulfport-Biloxi, MS",86
162,"Hattiesburg, MS M.S.A.","Jackson, MS",86
163,"Cape Girardeau, MO-IL M.S.A.","Champaign-Urbana, IL (Ford County not in sample)",86
164,"Columbia, MO M.S.A.","Columbia, MO (Howard County not in sample)",86
165,"Jefferson City, MO M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
166,"Joplin, MO M.S.A.","Joplin, MO",90
167,"St. Joseph, MO-KS M.S.A.","Columbia, MO (Howard County not in sample)",86
168,"Billings, MT M.S.A.","Billings, MT (Carbon County not in sample)",86
169,"Great Falls, MT M.S.A.","Billings, MT (Carbon County not in sample)",86
170,"Missoula, MT M.S.A.","Billings, MT (Carbon County not in sample)",86
171,"Omaha-Council Bluffs, NE-IA M.S.A.2","Omaha-Council Bluffs, NE-IA",95
172,"Lincoln, NE M.S.A.","Lincoln, NE",90
173,"Grand Island, NE M.S.A.","Grand Rapids-Muskegon-Holland, MI MSA*",86
174,"Las Vegas-Henderson-Paradise, NV M.S.A.","Asheville, NC (Haywood and Henderson Counties ...",86
175,"Reno, NV M.S.A.","Reno-Sparks, NV",70
176,"Carson City, NV M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
177,"Manchester-Nashua, NH M.S.A.","Portsmouth-Rochester, NH-ME MSA* (ME portion n...",86
178,"Ocean City, NJ M.S.A.2","Ocean City, NJ",90
179,"Camden, NJ M.D.2","Allentown-Bethlehem-Easton, PA-NJ",86
180,"Vineland-Bridgeton, NJ M.S.A.2","Atlantic City, NJ",86
181,"Trenton, NJ M.S.A.2","Allentown-Bethlehem-Easton, PA-NJ",86
182,"Las Cruces, NM M.S.A.","Santa Fe, NM",86
183,"Farmington, NM M.S.A.","Farmington, NM",95
184,"Elmira, NY M.S.A.","Albany-Schenectady-Troy, NY",86
185,"Binghamton, NY M.S.A.","Binghamton, NY",95
186,"Syracuse, NY M.S.A.","Syracuse, NY",90
187,"Buffalo-Cheektowaga-Niagara Falls, NY M.S.A.","Jamestown, NY MSA*",86
188,"Watertown-Fort Drum, NY M.S.A.","Jamestown, NY MSA*",86
189,"Utica-Rome, NY M.S.A.","Utica-Rome, NY",95
190,"Asheville, NC M.S.A.","Asheville, NC (Haywood and Henderson Counties ...",86
191,"Greensboro-High Point, NC M.S.A.","Greensboro-High Point, NC",95
192,"New Bern, NC M.S.A.","Asheville, NC (Haywood and Henderson Counties ...",86
193,"Greenville, NC M.S.A.","Greenville, NC",95
194,"Rocky Mount, NC M.S.A.","Asheville, NC (Haywood and Henderson Counties ...",86
195,"Goldsboro, NC M.S.A.","Asheville, NC (Haywood and Henderson Counties ...",86
196,"Fargo, ND-MN M.S.A.","Duluth, MN-WI (Carlton County, MN not in sampl...",86
197,"Bismarck, ND M.S.A.","Fargo, ND-MN (MN portion not identified)",86
198,"Grand Forks, ND-MN M.S.A.","Grand Rapids-Muskegon-Holland, MI MSA*",86
199,"Cincinnati, OH-KY-IN M.S.A.","Kalamazoo-Battle Creek, MI MSA* (Van Buren Cou...",86
200,"Akron, OH M.S.A.","Akron, OH",90
201,"Lima, OH M.S.A.","Akron, OH",86
202,"Canton-Massillon, OH M.S.A.","Canton-Massillon, OH",95
203,"Dayton, OH M.S.A.","Dayton, OH",90
204,"Wheeling, WV-OH M.S.A.","Wheeling, WV-OH",95
205,"Toledo, OH M.S.A.2","Akron, OH",86
206,"Mansfield, OH M.S.A.","Akron, OH",86
207,"Oklahoma City, OK M.S.A.","Oklahoma City, OK",95
208,"Lawton, OK M.S.A.","Lawton, OK",90
209,"Enid, OK M.S.A.","Fort Smith, AR-OK (Oklahoma portion not in sam...",86
210,"Tulsa, OK M.S.A.2","Fort Smith, AR-OK (Oklahoma portion not in sam...",86
211,"Salem, OR M.S.A.","Salem, OR",90
212,"Medford, OR M.S.A.","Medford, OR",90
213,"Bend-Redmond, OR M.S.A.",Not Identified or Nonmetropolitan,86
214,"Eugene, OR M.S.A.",Not Identified or Nonmetropolitan,86
215,"Grants Pass, OR M.S.A.",Not Identified or Nonmetropolitan,86
216,"Corvallis, OR M.S.A.",Not Identified or Nonmetropolitan,86
217,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD M....","Philadelphia-Camden-Wilmington, PA-NJ-DE",95
218,"Reading, PA M.S.A.","Reading, PA",90
219,"Pittsburgh, PA M.S.A.","Pittsburgh, PA",95
220,"Altoona, PA M.S.A.","Altoona, PA",90
221,"York-Hanover, PA M.S.A.","York-Hanover, PA",95
222,"Bloomsburg-Berwick, PA M.S.A","Altoona, PA",86
223,"Johnstown, PA M.S.A.","Johnstown, PA",95
224,"East Stroudsburg, PA M.S.A.","Altoona, PA",86
225,"State College, PA M.S.A.","Altoona, PA",86
226,"Lebanon, PA M.S.A.","Allentown-Bethlehem-Easton, PA-NJ",86
227,"Lancaster, PA M.S.A.","Lancaster, PA",95
228,"Williamsport, PA M.S.A.","Allentown-Bethlehem-Easton, PA-NJ",86
229,"Erie, PA M.S.A.","Erie, PA",90
230,"Gettysburg, PA M.S.A.","Allentown-Bethlehem-Easton, PA-NJ",86
231,"Chambersburg-Waynesboro, PA M.S.A.","Altoona, PA",86
232,"Providence-Warwick, RI-MA M.S.A.","Barnstable Town, MA",86
233,"Spartanburg, SC M.S.A.","Spartanburg, SC",95
234,"Sumter, SC M.S.A.","Greenville-Spartanburg-Anderson, SC MSA*",86
235,"Hilton Head Island-Bluffton-Beaufort, SC M.S.A.","Anderson, SC",86
236,"Sioux Falls, SD M.S.A.","Sioux Falls, SD",95
237,"Rapid City, SD M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
238,"Clarksville, TN-KY M.S.A.","Clarksville, TN-KY",95
239,"Memphis, TN-MS-AR M.S.A.","Fayetteville- Springdale-Rogers, AR-MO (Madiso...",86
240,"Chattanooga, TN-GA M.S.A.","Chattanooga, TN-GA",95
241,"Cleveland, TN M.S.A.","Kingsport-Bristol, TN-VA (Virginia portion not...",86
242,"Johnson City, TN M.S.A.","Johnson City, TN",95
243,"Knoxville, TN M.S.A.","Kingsport-Bristol, TN-VA (Virginia portion not...",86
244,"Kingsport-Bristol-Bristol, TN-VA M.S.A.","Chattanooga, TN-GA",86
245,"Morristown, TN M.S.A.","Kingsport-Bristol, TN-VA (Virginia portion not...",86
246,"Abilene, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
247,"Amarillo, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
248,"San Angelo, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
249,"Houston-The Woodlands-Sugar Land, TX M.S.A.3","Austin-Round Rock, TX",86
250,"Sherman-Denison, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
251,"Austin-Round Rock, TX M.S.A.2","Austin-Round Rock, TX",95
252,"San Antonio-New Braunfels, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
253,"Waco, TX M.S.A.","Waco, TX",90
254,"Killeen-Temple, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
255,"Corpus Christi, TX M.S.A.","Corpus Christi, TX",95
256,"Dallas-Fort Worth-Arlington, TX M.S.A.2","Albany, GA (Baker, Terrell, and Worth Counties...",86
257,"Texarkana, TX-AR M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
258,"El Paso, TX M.S.A.","El Paso, TX",90
259,"Fort Worth-Arlington, TX M.D.2","Albany, GA (Baker, Terrell, and Worth Counties...",86
260,"Victoria, TX M.S.A.","Victoria, TX",90
261,"Beaumont-Port Arthur, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
262,"Laredo, TX M.S.A.","Laredo, TX",90
263,"Longview, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
264,"Lubbock, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
265,"Wichita Falls, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
266,"Odessa, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
267,"Brownsville-Harlingen, TX M.S.A.","Brownsville-Harlingen, TX",95
268,"McAllen-Edinburg-Mission, TX M.S.A.2","Amarillo, TX (Armstrong and Carson Counties no...",86
269,"College Station-Bryan, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
270,"Tyler, TX M.S.A.","Amarillo, TX (Armstrong and Carson Counties no...",86
271,"Provo-Orem, UT M.S.A.","Provo-Orem, UT (Juab County not in sample)",86
272,"Logan, UT-ID M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
273,"Salt Lake City, UT M.S.A.","Boise City-Nampa, ID (Owyhee County not in sam...",86
274,"St. George, UT M.S.A.","Minneapolis-St Paul-Bloomington, MN-WI (Wiscon...",86
275,"Ogden-Clearfield, UT M.S.A.2, 3","Ogden-Clearfield, UT",90
276,"Roanoke, VA M.S.A.","Kingsport-Bristol, TN-VA (Virginia portion not...",86
277,"Virginia Beach-Norfolk-Newport News, VA-NC M.S.A.","Durham, NC",86
278,"Lynchburg, VA M.S.A.","Kingsport-Bristol, TN-VA (Virginia portion not...",86
279,"Harrisonburg, VA M.S.A.","Harrisonburg, VA",95
280,"Richmond, VA M.S.A.","Augusta-Richmond County, GA-SC",86
281,"Staunton-Waynesboro, VA M.S.A.","Harrisonburg, VA",86
282,"Charlottesville, VA M.S.A.","Harrisonburg, VA",86
283,"Winchester, VA-WV M.S.A.","Charleston, WV (Clay County not in sample)",86
284,"Wenatchee, WA M.S.A.","Olympia, WA",86
285,"Seattle-Tacoma-Bellevue, WA M.S.A.2","Seattle-Tacoma-Bellevue, WA",95
286,"Bellingham, WA M.S.A.","Bellingham, WA",95
287,"Bremerton-Silverdale, WA M.S.A.","Bremerton-Silverdale, WA",95
288,"Olympia-Tumwater, WA M.S.A.","Bellingham, WA",86
289,"Spokane-Spokane Valley, WA M.S.A.","Bellingham, WA",86
290,"Tacoma-Lakewood, WA M.D.","Bellingham, WA",86
291,"Mount Vernon-Anacortes, WA M.S.A.","Bellingham, WA",86
292,"Yakima, WA M.S.A.","Yakima, WA",90
293,"Walla Walla, WA M.S.A.","Bellingham, WA",86
294,"Charleston, WV M.S.A.","Charleston, WV (Clay County not in sample)",86
295,"Morgantown, WV M.S.A.","Charleston, WV (Clay County not in sample)",86
296,"Parkersburg-Vienna, WV M.S.A.","Hagerstown-Martinsburg, MD-WV (Berkeley County...",86
297,"Beckley, WV M.S.A.","Charleston, WV (Clay County not in sample)",86
298,"Milwaukee-Waukesha-West Allis, WI M.S.A.","Milwaukee-Waukesha-West Allis, WI",95
299,"Madison, WI M.S.A.","Madison, WI",90
300,"Green Bay, WI M.S.A.","Appleton-Oshkosh-Neenah, WI MSA*",86
301,"Janesville-Beloit, WI M.S.A.","Appleton,WI",86

In [58]:
# Creating a column called 'MSA_Code' in the 'df_with_crime_data' and populate it with null values
# this will contain the MSA codes for each entry in the college scorecard dataframe with crime 
# data included

df_with_crime_data['MSA_Code'] = np.nan

In [59]:
"""
Anything with a probability greater than 90
can be safely assumed to be an adequate match
we therefore include those MSA Codes to the 
df_with_crime_data without furthher inspection
"""
for index, row in final_possibly_matching_MSAs.iterrows():
  if row['probability'] >=90:
    code = df_msa_codes.loc[df_msa_codes['MSA Name'] == row['best_match'], 'MSA Code'].iloc[0]
    if row['original'] in df_with_crime_data['MSA'].values:
      df_with_crime_data.loc[df_with_crime_data['MSA'] == row['original'], 'MSA_Code'] = code

In [60]:
# Previewing a sample of 10 records from the 'df_with_crime_data' dataset

df_with_crime_data.sample(10)

,INSTNM,main,CURROPER,LONGITUDE,LATITUDE,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code
2455,The Art Institute of Virginia Beach,0,1,-76.1314,36.8422,Virginia Beach,VA,11.0,3,2,3,0.5263,0.4286,0.4286,NaN,NaN,31586.0,NaN,17596.0,17596.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0465,0.0000,0.0,9082.0,3604.0,NaN,NaN,NaN,NaN,NaN,NaN,26591.0,NaN,NaN,"Virginia Beach-Norfolk-Newport News, VA-NC M.S.A.",309.3,8.0,31.3,98.2,171.9,2727.1,388.1,2194.8,144.2,47260.0
2302,Parker University,1,1,-96.8936,32.8803,Dallas,TX,11.0,4,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15230.0,15230.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0,26086.0,12565.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Dallas-Fort Worth-Arlington, TX M.S.A.2",337.6,4.0,41.3,112.4,179.8,2554.3,503.1,1792.5,258.7,19100.0
77,The Art Institute of Phoenix,1,1,-112.1076,33.5671,Phoenix,AZ,11.0,3,3,3,0.5054,0.5000,0.5000,NaN,NaN,30617.0,NaN,17416.0,17416.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0041,0.1660,0.0000,0.0,14908.0,3774.0,NaN,NaN,NaN,NaN,NaN,NaN,25923.0,0.3631,NaN,"Phoenix-Mesa-Scottsdale, AZ M.S.A.",388.4,4.5,43.0,103.5,237.4,2824.2,571.6,1984.2,268.4,38060.0
525,Trinity College,1,1,-72.6887,41.7467,Hartford,CT,12.0,4,3,2,0.9086,NaN,NaN,NaN,NaN,59865.0,NaN,47510.0,47510.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0093,0.0222,0.0,29677.0,23403.0,0.3178,0.3178,25.0,29.0,1240.0,NaN,26419.0,0.8628,NaN,"Hartford-West Hartford-East Hartford, CT M.S.A.",252.8,4.4,22.5,94.7,131.2,2175.4,325.4,1637.0,213.0,73450.0
399,CET-El Centro,0,1,-115.5491,32.7909,El Centro,CA,13.0,1,1,2,NaN,NaN,NaN,0.8519,NaN,NaN,9931.0,NaN,NaN,7958.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0,10520.0,5325.0,NaN,NaN,NaN,NaN,NaN,NaN,-264.0,NaN,0.9257,"El Centro, CA M.S.A.",414.9,1.1,16.1,72.8,324.9,3457.8,773.2,2330.7,353.8,20940.0
1073,Fisk University,1,1,-86.8057,36.1691,Nashville,TN,11.0,4,3,2,0.7014,0.0000,0.0000,NaN,NaN,38893.0,NaN,20449.0,20449.0,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0139,0.0000,0.0,11470.0,9602.0,0.3968,0.3968,17.0,18.0,854.0,NaN,20875.0,0.5217,NaN,"Nashville-Davidson–Murfreesboro–Franklin, TN M...",612.7,5.5,48.1,128.8,430.2,2580.2,506.7,1929.5,144.0,34980.0
8,Southeastern School of Cosmetology,1,1,-86.8421,33.4795,Birmingham,AL,12.0,1,1,2,NaN,NaN,NaN,0.6441,NaN,NaN,10953.0,NaN,NaN,9200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0,342.0,1208.0,NaN,NaN,NaN,NaN,NaN,NaN,5452.0,NaN,0.5696,"Birmingham-Hoover, AL M.S.A.",682.0,11.1,46.2,157.7,467.1,3344.9,817.6,2262.0,265.3,13820.0
2179,Pima Medical Institute-Houston,0,1,-95.5488,29.7839,Houston,TX,11.0,2,1,3,NaN,NaN,NaN,0.7059,NaN,NaN,20272.0,NaN,NaN,11397.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0,4079.0,2212.0,NaN,NaN,NaN,NaN,NaN,NaN,12548.0,NaN,0.6679,"Houston-The Woodlands-Sugar Land, TX M.S.A.3",566.6,6.9,37.3,228.9,293.5,NaN,596.8,NaN,367.2,26420.0
2010,Spartanburg Methodist College,1,1,-81.9709,34.9546,Spartanburg,SC,22.0,2,2,2,NaN,NaN,NaN,0.5284,0.0,25085.0,NaN,15745.0,15745.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0,8284.0,3484.0,0.8812,0.8812,15.0,20.0,859.0,NaN,10916.0,NaN,0.4118,"Spartanburg, SC M.S.A.",406.2,7.7,46.6,87.9,264.0,2772.3,605.5,1998.1,168.7,43900.0
1747,Walsh University,1,1,-81.3691,40.8733,Canton,OH,21.0,4,3,2,0.7348,NaN,NaN,NaN,NaN,34994.0,NaN,25840.0,25840.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0058,0.0000,0.0,12937.0,7309.0,0.7713,0.7713,20.0,25.0,1047.0,NaN,18878.0,0.5519,NaN,"Canton-Massillon, OH M.S.A.",323.7,3.2,43.6,91.1,185.9,2568.2,652.4,1799.4,116.3,15940.0

In [61]:
# Checking the sum of missing values

df_with_crime_data.isnull().values.sum()
df_with_crime_data.isnull().sum()

INSTNM                  0
main                    0
CURROPER                0
LONGITUDE             276
LATITUDE              276
CITY                    0
STABBR                  0
LOCALE                151
HIGHDEG                 0
PREDDEG                 0
CONTROL                 0
RET_FT4              1841
RET_PT4              2109
RET_PT4              2109
RET_FTL4             1408
RET_PTL4             2007
COSTT4_A             1306
COSTT4_P             1775
TUITIONFEE_IN        1197
TUITIONFEE_OUT       1277
TUITIONFEE_PROG      1714
CIP10BACHL            151
CIP11BACHL            151
CIP14BACHL            151
CIP15BACHL            151
CIP10ASSOC            151
CIP11ASSOC            151
CIP14ASSOC            151
CIP15ASSOC            151
PCIP10                271
PCIP11                271
PCIP14                271
PCIP15                271
TUITFTE               158
INEXPFTE              158
ADM_RATE             1905
ADM_RATE_ALL         1811
ACTCM25              2197
ACTCM75              2197
SAT_AVG_ALL          2159
NPT4_PUB             2153
NPT4_PRIV             928
C150_4               1799
C150_L4              1392
MSA                     0
ViolentCrime            6
Murder                  0
Rape                    0
Robbery                 0
AggravatedAssault       6
PropertyCrime         135
Burglary               61
Theft                 100
MotorVehicleTheft       0
MSA_Code              326
dtype: int64

In [62]:
# Getting records whose 'MSA_Code' is equal to 47260

df_code = df_with_crime_data[df_with_crime_data.MSA_Code == 47260]

df_code.shape

(15, 55)

In [63]:
# Filtering the Kauffman Startup Index dataset to show values with MSA as their Caregory and of Metro Profile dataset 
df_kauffman_startup_index_filtered_by_msa = df_kauffman_startup_index[(df_kauffman_startup_index['Category'] == 'MSA') &
                                                                      (df_kauffman_startup_index['dataset'] == 'Metro Profile')]
df_kauffman_startup_index_filtered_by_msa.sample(10)

,year_CPS,Characteristic,OppShare_New_Entrp,Breakdown,Rate_New_Entrp,Location,startup_index,Index Year,year_BDS,startup_density,Rank,Composition_of_New_Entrp,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text
2409,1990.0,NaN,NaN,NaN,NaN,12420,NaN,1991.0,1988.0,122.620003,NaN,NaN,NaN,NaN,46.967270,NaN,NaN,2.414508,NaN,NaN,NaN,NaN,Metro Profile,Austin-Round Rock-San Marcos,MSA,NaN,NaN,the metropolitan area of,.
2547,2008.0,NaN,NaN,NaN,0.0024,16980,NaN,2009.0,2006.0,95.730003,NaN,NaN,27.272728,NaN,27.340010,-2.752294,NaN,0.092401,NaN,NaN,NaN,NaN,Metro Profile,Chicago-Joliet-Naperville,MSA,NaN,240.0,the metropolitan area of,.
2970,2015.0,NaN,0.7743,NaN,0.0038,29820,NaN,2016.0,2013.0,119.029999,5.0,NaN,56.000000,47.492165,100.000000,3.669725,-0.681564,2.104490,6.0,1.0,1.17,0.53,Metro Profile,Las Vegas-Paradise,MSA,7.743,380.0,the metropolitan area of,a slight increase
3258,1990.0,NaN,NaN,NaN,NaN,37980,NaN,1991.0,1988.0,109.290001,NaN,NaN,NaN,NaN,27.578180,NaN,NaN,1.263385,NaN,NaN,NaN,NaN,Metro Profile,Philadelphia-Camden-Wilmington,MSA,NaN,NaN,the metropolitan area of,.
3269,2011.0,NaN,0.8208,NaN,0.0018,37980,NaN,2012.0,2009.0,70.790001,33.0,NaN,2.272727,84.183174,25.210218,-5.504587,0.617319,-2.061313,33.0,0.0,-2.61,0.29,Metro Profile,Philadelphia-Camden-Wilmington,MSA,8.208,180.0,the metropolitan area of,a slight increase
2539,2016.0,NaN,0.8040,NaN,0.0022,16980,NaN,2017.0,2014.0,74.680000,31.0,NaN,24.444443,45.221363,30.743755,-3.669725,0.148045,-1.725389,30.0,-1.0,-1.57,-0.18,Metro Profile,Chicago-Joliet-Naperville,MSA,8.040,220.0,the metropolitan area of,basically no changes
3641,1989.0,NaN,NaN,NaN,NaN,41860,NaN,1990.0,1987.0,127.730003,NaN,NaN,NaN,NaN,38.762264,NaN,NaN,2.855786,NaN,NaN,NaN,NaN,Metro Profile,San Francisco-Oakland-Fremont,MSA,NaN,NaN,the metropolitan area of,.
3022,1995.0,NaN,NaN,NaN,NaN,31100,NaN,1996.0,1993.0,103.639999,NaN,NaN,NaN,NaN,35.192799,NaN,NaN,0.775475,NaN,NaN,NaN,NaN,Metro Profile,Los Angeles-Long Beach-Santa Ana,MSA,NaN,NaN,the metropolitan area of,.
3245,1992.0,NaN,NaN,NaN,NaN,36740,NaN,1993.0,1990.0,142.080002,NaN,NaN,NaN,NaN,80.550041,NaN,NaN,4.094991,NaN,NaN,NaN,NaN,Metro Profile,Orlando-Kissimmee-Sanford,MSA,NaN,NaN,the metropolitan area of,.
3025,1989.0,NaN,NaN,NaN,NaN,33100,NaN,1990.0,1987.0,168.300003,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,6.359240,NaN,NaN,NaN,NaN,Metro Profile,Miami-Fort Lauderdale-Pompano Beach,MSA,NaN,NaN,the metropolitan area of,.

In [64]:
df_kauffman_startup_index_filtered_by_msa.dtypes

year_CPS                    float64
Characteristic               object
OppShare_New_Entrp          float64
Breakdown                    object
Rate_New_Entrp              float64
Location                      int64
startup_index               float64
Index Year                  float64
year_BDS                    float64
startup_density             float64
Rank                        float64
Composition_of_New_Entrp    float64
norm_rate                   float64
norm_opp                    float64
norm_density                float64
z_rate                      float64
z_oppshare                  float64
z_startup_den               float64
rank_last_y                 float64
rank_diff                   float64
index_last_y                float64
index_diff                  float64
dataset                      object
Location_name                object
Category                     object
OppShare_New_Entrp_web      float64
Rate_New_Entrp_web          float64
location_category            object
index_diff_text              object
dtype: object

The rows in the Kauffman Start Up index contain entries across a range of years, some entries go back to the 1980s. This past information wont be of much help as we are assuming that Jane's concern is current status of start-up activity in the MSAs within which the universities/colleges we are to propose to her reside. We will therefore select only the latest record for each MSA in the Kauffman start-up index and use the 'Index Year' column as the filtering column.

In [65]:
"""
Group by location name and extract the row with latest Index year
"""
df_kauffman_startup_index_filtered_by_latest_index_year = df_kauffman_startup_index_filtered_by_msa.iloc[
                                               df_kauffman_startup_index_filtered_by_msa.reset_index(drop=True).groupby(['Location_name'])['Index Year'].idxmax()
                                               ]

In [66]:
df_kauffman_startup_index_filtered_by_latest_index_year.head()

,year_CPS,Characteristic,OppShare_New_Entrp,Breakdown,Rate_New_Entrp,Location,startup_index,Index Year,year_BDS,startup_density,Rank,Composition_of_New_Entrp,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text
2357,2016.0,NaN,0.7549,NaN,0.0043,12060,NaN,2017.0,2014.0,89.930000,12.0,NaN,71.111114,27.969078,53.703705,5.963303,-1.223463,-0.408463,15.0,3.0,0.10,1.34,Metro Profile,Atlanta-Sandy Springs-Marietta,MSA,7.549,430.0,the metropolitan area of,a large increase
2386,2016.0,NaN,0.8473,NaN,0.0051,12420,NaN,2017.0,2014.0,104.540001,2.0,NaN,88.888886,60.435699,75.700089,9.633027,1.357543,0.853195,1.0,-1.0,4.90,-0.95,Metro Profile,Austin-Round Rock-San Marcos,MSA,8.473,510.0,the metropolitan area of,a slight decrease
2452,2016.0,NaN,0.8102,NaN,0.0020,12580,NaN,2017.0,2014.0,69.160004,35.0,NaN,19.999998,47.399860,22.433008,-4.587156,0.321230,-2.202073,22.0,-13.0,-0.99,-1.17,Metro Profile,Baltimore-Towson,MSA,8.102,200.0,the metropolitan area of,a large decrease
2479,2016.0,NaN,0.7985,NaN,0.0033,14460,NaN,2017.0,2014.0,68.190002,21.0,NaN,48.888889,43.288826,20.972603,1.376147,-0.005586,-2.285838,20.0,-1.0,-0.96,0.65,Metro Profile,Boston-Cambridge-Quincy,MSA,7.985,330.0,the metropolitan area of,a slight increase
2494,2016.0,NaN,0.7121,NaN,0.0037,16740,NaN,2017.0,2014.0,87.500000,17.0,NaN,57.777779,12.930430,50.045166,3.211009,-2.418994,-0.618308,20.0,3.0,-0.96,1.02,Metro Profile,Charlotte-Gastonia-Rock Hill,MSA,7.121,370.0,the metropolitan area of,a large increase

To match a college to a record on the kauffman startup index,
we will use the MSA_Code column in the df_with_crimes_dataset
and use a matching location value in the kauffman startup index dataset.

In [67]:
"""
merge df_with_crime_data
with df_kauffman_startup_index
using the MSA_Code as the linking column
"""
final_df = pd.merge(left=df_with_crime_data, right=df_kauffman_startup_index_filtered_by_latest_index_year, left_on=['MSA_Code'], right_on=['Location'])

In [68]:
# Previewing final_df

final_df.head()

,INSTNM,main,CURROPER,LONGITUDE,LATITUDE,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,Characteristic,OppShare_New_Entrp,Breakdown,Rate_New_Entrp,Location,startup_index,Index Year,year_BDS,startup_density,Rank,Composition_of_New_Entrp,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text
0,Collins College,0,1,-111.9865,33.4033,Phoenix,AZ,11.0,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0683,0.0,0.0,19717.0,5313.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3773,NaN,"Phoenix-Mesa-Scottsdale, AZ M.S.A.",388.4,4.5,43.0,103.5,237.4,2824.2,571.6,1984.2,268.4,38060.0,2016.0,NaN,0.8715,NaN,0.0038,38060,NaN,2017.0,2014.0,92.120003,8.0,NaN,60.0,68.938858,57.000908,3.669725,2.03352,-0.219344,10.0,2.0,0.67,1.16,Metro Profile,Phoenix-Mesa-Glendale,MSA,8.715,380.0,the metropolitan area of,a large increase
1,American Indian College of the Assemblies of G...,1,1,-112.0922,33.5777,Phoenix,AZ,11.0,3,3,2,0.6667,NaN,NaN,NaN,NaN,20601.0,NaN,12000.0,12000.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,5550.0,6669.0,NaN,NaN,NaN,NaN,NaN,NaN,12580.0,0.5000,NaN,"Phoenix-Mesa-Scottsdale, AZ M.S.A.",388.4,4.5,43.0,103.5,237.4,2824.2,571.6,1984.2,268.4,38060.0,2016.0,NaN,0.8715,NaN,0.0038,38060,NaN,2017.0,2014.0,92.120003,8.0,NaN,60.0,68.938858,57.000908,3.669725,2.03352,-0.219344,10.0,2.0,0.67,1.16,Metro Profile,Phoenix-Mesa-Glendale,MSA,8.715,380.0,the metropolitan area of,a large increase
2,American Institute of Technology,1,1,-112.1753,33.4423,Phoenix,AZ,11.0,1,1,3,NaN,NaN,NaN,NaN,NaN,NaN,21896.0,NaN,NaN,9150.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,6018.0,3061.0,NaN,NaN,NaN,NaN,NaN,NaN,19019.0,NaN,0.6815,"Phoenix-Mesa-Scottsdale, AZ M.S.A.",388.4,4.5,43.0,103.5,237.4,2824.2,571.6,1984.2,268.4,38060.0,2016.0,NaN,0.8715,NaN,0.0038,38060,NaN,2017.0,2014.0,92.120003,8.0,NaN,60.0,68.938858,57.000908,3.669725,2.03352,-0.219344,10.0,2.0,0.67,1.16,Metro Profile,Phoenix-Mesa-Glendale,MSA,8.715,380.0,the metropolitan area of,a large increase
3,Carrington College-Phoenix,1,1,-112.1155,33.5608,Phoenix,AZ,11.0,3,1,3,NaN,NaN,NaN,NaN,NaN,NaN,24417.0,NaN,NaN,14287.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,11721.0,2326.0,1.0,1.0,NaN,NaN,NaN,NaN,20501.0,0.6443,NaN,"Phoenix-Mesa-Scottsdale, AZ M.S.A.",388.4,4.5,43.0,103.5,237.4,2824.2,571.6,1984.2,268.4,38060.0,2016.0,NaN,0.8715,NaN,0.0038,38060,NaN,2017.0,2014.0,92.120003,8.0,NaN,60.0,68.938858,57.000908,3.669725,2.03352,-0.219344,10.0,2.0,0.67,1.16,Metro Profile,Phoenix-Mesa-Glendale,MSA,8.715,380.0,the metropolitan area of,a large increase
4,Brookline College-Phoenix,1,1,-112.1501,33.5254,Phoenix,AZ,11.0,3,1,3,0.4471,NaN,NaN,NaN,NaN,NaN,29302.0,NaN,NaN,14500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,25798.0,8116.0,NaN,NaN,NaN,NaN,NaN,NaN,25566.0,0.4664,NaN,"Phoenix-Mesa-Scottsdale, AZ M.S.A.",388.4,4.5,43.0,103.5,237.4,2824.2,571.6,1984.2,268.4,38060.0,2016.0,NaN,0.8715,NaN,0.0038,38060,NaN,2017.0,2014.0,92.120003,8.0,NaN,60.0,68.938858,57.000908,3.669725,2.03352,-0.219344,10.0,2.0,0.67,1.16,Metro Profile,Phoenix-Mesa-Glendale,MSA,8.715,380.0,the metropolitan area of,a large increase

In [69]:
# Checking the number of missing values in the final_df column

final_df.isnull().sum()

INSTNM                         0
main                           0
CURROPER                       0
LONGITUDE                    109
LATITUDE                     109
CITY                           0
STABBR                         0
LOCALE                        60
HIGHDEG                        0
PREDDEG                        0
CONTROL                        0
RET_FT4                      684
RET_PT4                      788
RET_PT4                      788
RET_FTL4                     588
RET_PTL4                     810
COSTT4_A                     516
COSTT4_P                     696
TUITIONFEE_IN                475
TUITIONFEE_OUT               505
TUITIONFEE_PROG              668
CIP10BACHL                    60
CIP11BACHL                    60
CIP14BACHL                    60
CIP15BACHL                    60
CIP10ASSOC                    60
CIP11ASSOC                    60
CIP14ASSOC                    60
CIP15ASSOC                    60
PCIP10                       131
PCIP11                       131
PCIP14                       131
PCIP15                       131
TUITFTE                       63
INEXPFTE                      63
ADM_RATE                     726
ADM_RATE_ALL                 700
ACTCM25                      866
ACTCM75                      866
SAT_AVG_ALL                  851
NPT4_PUB                     898
NPT4_PRIV                    314
C150_4                       673
C150_L4                      580
MSA                            0
ViolentCrime                   0
Murder                         0
Rape                           0
Robbery                        0
AggravatedAssault              0
PropertyCrime                 99
Burglary                      26
Theft                         99
MotorVehicleTheft              0
MSA_Code                       0
year_CPS                       0
Characteristic              1011
OppShare_New_Entrp             0
Breakdown                   1011
Rate_New_Entrp                 0
Location                       0
startup_index               1011
Index Year                     0
year_BDS                       0
startup_density                0
Rank                           0
Composition_of_New_Entrp    1011
norm_rate                      0
norm_opp                       0
norm_density                   0
z_rate                         0
z_oppshare                     0
z_startup_den                  0
rank_last_y                    0
rank_diff                      0
index_last_y                   0
index_diff                     0
dataset                        0
Location_name                  0
Category                       0
OppShare_New_Entrp_web         0
Rate_New_Entrp_web             0
location_category              0
index_diff_text                0
dtype: int64

In [70]:
# Checking shape

final_df.shape

(1011, 84)

In [71]:
# Dropping columns with 100% null values after merger
columns_to_drop = [
        'Composition_of_New_Entrp',
        'startup_index',
        'Breakdown',
        'Characteristic',
        'LONGITUDE', 
        'LATITUDE',        
]

# Dropping these columns from the final_df dataset using axis = 1 and inplace = True

final_df.drop(columns_to_drop, axis=1, inplace=True)

final_df.shape

(1011, 78)

In [72]:
# Listing your the dataset's columns

list(final_df.columns)

['INSTNM',
 'main',
 'CURROPER',
 'CITY',
 'STABBR',
 'LOCALE',
 'HIGHDEG',
 'PREDDEG',
 'CONTROL',
 'RET_FT4',
 'RET_PT4',
 'RET_PT4',
 'RET_FTL4',
 'RET_PTL4',
 'COSTT4_A',
 'COSTT4_P',
 'TUITIONFEE_IN',
 'TUITIONFEE_OUT',
 'TUITIONFEE_PROG',
 'CIP10BACHL',
 'CIP11BACHL',
 'CIP14BACHL',
 'CIP15BACHL',
 'CIP10ASSOC',
 'CIP11ASSOC',
 'CIP14ASSOC',
 'CIP15ASSOC',
 'PCIP10',
 'PCIP11',
 'PCIP14',
 'PCIP15',
 'TUITFTE',
 'INEXPFTE',
 'ADM_RATE',
 'ADM_RATE_ALL',
 'ACTCM25',
 'ACTCM75',
 'SAT_AVG_ALL',
 'NPT4_PUB',
 'NPT4_PRIV',
 'C150_4',
 'C150_L4',
 'MSA',
 'ViolentCrime',
 'Murder',
 'Rape',
 'Robbery',
 'AggravatedAssault',
 'PropertyCrime',
 'Burglary',
 'Theft',
 'MotorVehicleTheft',
 'MSA_Code',
 'year_CPS',
 'OppShare_New_Entrp',
 'Rate_New_Entrp',
 'Location',
 'Index Year',
 'year_BDS',
 'startup_density',
 'Rank',
 'norm_rate',
 'norm_opp',
 'norm_density',
 'z_rate',
 'z_oppshare',
 'z_startup_den',
 'rank_last_y',
 'rank_diff',
 'index_last_y',
 'index_diff',
 'dataset',
 'Location_name',
 'Category',
 'OppShare_New_Entrp_web',
 'Rate_New_Entrp_web',
 'location_category',
 'index_diff_text']

As per Jane's requirements, She wants a college/University located in an MSA that ranks 75th percentile or higher on the Kauffman startup index.

In [73]:
# Ranking based on Start Up 
# ---
#In this case ranking is done based on the column ['startup_density']

final_df['Ranking_Start_up'] = final_df['startup_density'].rank(pct=True)

#final_df['Ranking_Start_up'].min()

final_df.shape

(1011, 79)

In [74]:
# Drop all rows with a Start up ranking below 0.75
# ---
#
final_df.drop(final_df[final_df['Ranking_Start_up'] < 0.75].index, inplace=True)

final_df.shape

(279, 79)

In [75]:
# Print the minimum value of the 'Ranking_Start_up variable'

final_df['Ranking_Start_up'].min()

0.7606330365974283

In [76]:
# Preview final_df where the 'Ranking_Start_up' is equal to the maximum value in that column

preview = final_df[(final_df.Ranking_Start_up) == final_df['Ranking_Start_up'].max()]

preview.head()

,INSTNM,main,CURROPER,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,OppShare_New_Entrp,Rate_New_Entrp,Location,Index Year,year_BDS,startup_density,Rank,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text,Ranking_Start_up
323,The Art Institute of Fort Lauderdale,1,1,Fort Lauderdale,FL,12.0,3,2,3,0.6667,0.5556,0.5556,NaN,NaN,30805.0,NaN,17704.0,17704.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0080,0.0880,0.0000,0.0000,15439.0,3955.0,NaN,NaN,NaN,NaN,NaN,NaN,25244.0,0.4293,NaN,"Fort Lauderdale-Pompano Beach-Deerfield Beach,...",405.5,4.5,31.0,129.6,240.5,3029.9,537.3,2234.6,258.0,33100.0,2016.0,0.8109,0.0056,33100,2017.0,2014.0,107.809998,1.0,100.0,47.645817,80.623299,11.926605,0.340783,1.135578,2.0,1.0,3.24,1.23,Metro Profile,Miami-Fort Lauderdale-Pompano Beach,MSA,8.109,560.0,the metropolitan area of,a large increase,0.972305
324,Broward College,1,1,Fort Lauderdale,FL,21.0,3,2,1,NaN,NaN,NaN,NaN,NaN,13383.0,NaN,2542.0,8712.0,NaN,1.0,1.0,0.0,1.0,2.0,2.0,0.0,2.0,0.0010,0.0341,0.0000,0.0130,1336.0,3163.0,NaN,NaN,NaN,NaN,NaN,8286.0,NaN,0.3185,NaN,"Fort Lauderdale-Pompano Beach-Deerfield Beach,...",405.5,4.5,31.0,129.6,240.5,3029.9,537.3,2234.6,258.0,33100.0,2016.0,0.8109,0.0056,33100,2017.0,2014.0,107.809998,1.0,100.0,47.645817,80.623299,11.926605,0.340783,1.135578,2.0,1.0,3.24,1.23,Metro Profile,Miami-Fort Lauderdale-Pompano Beach,MSA,8.109,560.0,the metropolitan area of,a large increase,0.972305
325,Keiser University-Ft Lauderdale,1,1,Fort Lauderdale,FL,12.0,4,2,2,0.7353,0.3827,0.3827,NaN,NaN,26887.0,NaN,16284.0,16284.0,NaN,0.0,2.0,2.0,2.0,0.0,2.0,2.0,2.0,0.0000,0.0406,0.0009,0.0004,17604.0,5117.0,0.9331,0.9331,NaN,NaN,NaN,NaN,22933.0,0.5710,NaN,"Fort Lauderdale-Pompano Beach-Deerfield Beach,...",405.5,4.5,31.0,129.6,240.5,3029.9,537.3,2234.6,258.0,33100.0,2016.0,0.8109,0.0056,33100,2017.0,2014.0,107.809998,1.0,100.0,47.645817,80.623299,11.926605,0.340783,1.135578,2.0,1.0,3.24,1.23,Metro Profile,Miami-Fort Lauderdale-Pompano Beach,MSA,8.109,560.0,the metropolitan area of,a large increase,0.972305
326,Nova Southeastern University,1,1,Fort Lauderdale,FL,21.0,4,3,2,0.7112,0.2459,0.2459,NaN,NaN,40783.0,NaN,25430.0,25430.0,NaN,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0000,0.0130,0.0000,0.0000,16935.0,10921.0,0.5746,0.5746,21.0,27.0,1084.0,NaN,27998.0,0.4049,NaN,"Fort Lauderdale-Pompano Beach-Deerfield Beach,...",405.5,4.5,31.0,129.6,240.5,3029.9,537.3,2234.6,258.0,33100.0,2016.0,0.8109,0.0056,33100,2017.0,2014.0,107.809998,1.0,100.0,47.645817,80.623299,11.926605,0.340783,1.135578,2.0,1.0,3.24,1.23,Metro Profile,Miami-Fort Lauderdale-Pompano Beach,MSA,8.109,560.0,the metropolitan area of,a large increase,0.972305
327,City College-Fort Lauderdale,1,1,Fort Lauderdale,FL,12.0,3,2,2,NaN,NaN,NaN,NaN,NaN,29676.0,NaN,15840.0,15840.0,NaN,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0972,0.0000,0.0000,0.0000,16437.0,6160.0,NaN,NaN,NaN,NaN,NaN,NaN,24458.0,0.3704,NaN,"Fort Lauderdale-Pompano Beach-Deerfield Beach,...",405.5,4.5,31.0,129.6,240.5,3029.9,537.3,2234.6,258.0,33100.0,2016.0,0.8109,0.0056,33100,2017.0,2014.0,107.809998,1.0,100.0,47.645817,80.623299,11.926605,0.340783,1.135578,2.0,1.0,3.24,1.23,Metro Profile,Miami-Fort Lauderdale-Pompano Beach,MSA,8.109,560.0,the metropolitan area of,a large increase,0.972305

To get a measure of the total crime per MSA, we then sum all crime and create a new column labeled Total_Crime that will contain this sum. We then rank the rows in the final df based on total crime and drop all rows with a ranking above 50% satisfying Jane's condition of a college/University in a location having below 50th percentile in overall crime.

In [77]:
final_df['Total_Crime'] = final_df.apply(
    lambda row: row['ViolentCrime'] + row['Murder'] + row['Rape'] + row['Robbery'] + row['AggravatedAssault'] + row['PropertyCrime'] + row['Burglary'] + row['Theft'] + row['MotorVehicleTheft'],
    axis=1
    )

In [78]:
# Preview the dataset

final_df.head()

,INSTNM,main,CURROPER,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,OppShare_New_Entrp,Rate_New_Entrp,Location,Index Year,year_BDS,startup_density,Rank,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text,Ranking_Start_up,Total_Crime
167,Associated Technical College-San Diego,1,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,NaN,NaN,NaN,24413.0,NaN,NaN,17008.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8191,0.1809,0.0,0.0,7468.0,3066.0,NaN,NaN,NaN,NaN,NaN,NaN,20138.0,NaN,0.6188,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7
168,Alliant International University,1,1,San Diego,CA,11.0,4,3,2,0.7500,1.0,1.0,NaN,NaN,28901.0,NaN,15816.0,15816.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,20681.0,9501.0,0.4922,0.4922,NaN,NaN,NaN,NaN,19768.0,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7
169,California College San Diego,1,1,San Diego,CA,11.0,3,2,2,0.2737,NaN,NaN,NaN,NaN,27138.0,NaN,18480.0,18480.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0907,0.0,0.0,16010.0,3504.0,NaN,NaN,NaN,NaN,NaN,NaN,22956.0,0.5845,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7
170,California Western School of Law,1,1,San Diego,CA,11.0,4,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,38524.0,13921.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7
171,CET-San Diego,0,1,San Diego,CA,11.0,1,1,2,NaN,NaN,NaN,0.7857,0.875,NaN,17902.0,NaN,NaN,10165.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,5379.0,5529.0,NaN,NaN,NaN,NaN,NaN,NaN,14109.0,NaN,0.7605,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7

As

In [79]:
# Get the maximum total crime rate

final_df['Total_Crime'].max()

7591.8

In [80]:
# Sort by ranking
final_df['Ranking_by_Crime_Rate'] = final_df['Total_Crime'].rank(pct=True)

final_df.head()

,INSTNM,main,CURROPER,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,OppShare_New_Entrp,Rate_New_Entrp,Location,Index Year,year_BDS,startup_density,Rank,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text,Ranking_Start_up,Total_Crime,Ranking_by_Crime_Rate
167,Associated Technical College-San Diego,1,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,NaN,NaN,NaN,24413.0,NaN,NaN,17008.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8191,0.1809,0.0,0.0,7468.0,3066.0,NaN,NaN,NaN,NaN,NaN,NaN,20138.0,NaN,0.6188,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
168,Alliant International University,1,1,San Diego,CA,11.0,4,3,2,0.7500,1.0,1.0,NaN,NaN,28901.0,NaN,15816.0,15816.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,20681.0,9501.0,0.4922,0.4922,NaN,NaN,NaN,NaN,19768.0,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
169,California College San Diego,1,1,San Diego,CA,11.0,3,2,2,0.2737,NaN,NaN,NaN,NaN,27138.0,NaN,18480.0,18480.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0907,0.0,0.0,16010.0,3504.0,NaN,NaN,NaN,NaN,NaN,NaN,22956.0,0.5845,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
170,California Western School of Law,1,1,San Diego,CA,11.0,4,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,38524.0,13921.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
171,CET-San Diego,0,1,San Diego,CA,11.0,1,1,2,NaN,NaN,NaN,0.7857,0.875,NaN,17902.0,NaN,NaN,10165.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,5379.0,5529.0,NaN,NaN,NaN,NaN,NaN,NaN,14109.0,NaN,0.7605,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951

In [81]:
# Preview the records where the 'Total_Crime' is at minimum

preview = final_df[(final_df.Total_Crime) == (final_df['Total_Crime'].min())]

preview.head()

,INSTNM,main,CURROPER,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,OppShare_New_Entrp,Rate_New_Entrp,Location,Index Year,year_BDS,startup_density,Rank,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text,Ranking_Start_up,Total_Crime,Ranking_by_Crime_Rate
167,Associated Technical College-San Diego,1,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,NaN,NaN,NaN,24413.0,NaN,NaN,17008.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8191,0.1809,0.0,0.0,7468.0,3066.0,NaN,NaN,NaN,NaN,NaN,NaN,20138.0,NaN,0.6188,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
168,Alliant International University,1,1,San Diego,CA,11.0,4,3,2,0.7500,1.0,1.0,NaN,NaN,28901.0,NaN,15816.0,15816.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,20681.0,9501.0,0.4922,0.4922,NaN,NaN,NaN,NaN,19768.0,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
169,California College San Diego,1,1,San Diego,CA,11.0,3,2,2,0.2737,NaN,NaN,NaN,NaN,27138.0,NaN,18480.0,18480.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0907,0.0,0.0,16010.0,3504.0,NaN,NaN,NaN,NaN,NaN,NaN,22956.0,0.5845,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
170,California Western School of Law,1,1,San Diego,CA,11.0,4,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,38524.0,13921.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
171,CET-San Diego,0,1,San Diego,CA,11.0,1,1,2,NaN,NaN,NaN,0.7857,0.875,NaN,17902.0,NaN,NaN,10165.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,5379.0,5529.0,NaN,NaN,NaN,NaN,NaN,NaN,14109.0,NaN,0.7605,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951

In [82]:
# Drop all rows with above 50% overall crime ranking

final_df.drop(final_df[final_df['Ranking_by_Crime_Rate'] > 0.5].index, inplace=True)

In [83]:
# Get the maximum 'Ranking_by_Crime_Rate' value

final_df['Ranking_by_Crime_Rate'].max()

0.4368932038834951

In [84]:
final_df

,INSTNM,main,CURROPER,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,OppShare_New_Entrp,Rate_New_Entrp,Location,Index Year,year_BDS,startup_density,Rank,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text,Ranking_Start_up,Total_Crime,Ranking_by_Crime_Rate
167,Associated Technical College-San Diego,1,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,NaN,NaN,NaN,24413.0,NaN,NaN,17008.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8191,0.1809,0.0000,0.0000,7468.0,3066.0,NaN,NaN,NaN,NaN,NaN,NaN,20138.0,NaN,0.6188,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
168,Alliant International University,1,1,San Diego,CA,11.0,4,3,2,0.7500,1.0000,1.0000,NaN,NaN,28901.0,NaN,15816.0,15816.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,20681.0,9501.0,0.4922,0.4922,NaN,NaN,NaN,NaN,19768.0,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
169,California College San Diego,1,1,San Diego,CA,11.0,3,2,2,0.2737,NaN,NaN,NaN,NaN,27138.0,NaN,18480.0,18480.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0907,0.0000,0.0000,16010.0,3504.0,NaN,NaN,NaN,NaN,NaN,NaN,22956.0,0.5845,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
170,California Western School of Law,1,1,San Diego,CA,11.0,4,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,38524.0,13921.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
171,CET-San Diego,0,1,San Diego,CA,11.0,1,1,2,NaN,NaN,NaN,0.7857,0.8750,NaN,17902.0,NaN,NaN,10165.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,5379.0,5529.0,NaN,NaN,NaN,NaN,NaN,NaN,14109.0,NaN,0.7605,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
172,Coleman University,1,1,San Diego,CA,11.0,4,2,2,NaN,NaN,NaN,NaN,NaN,29842.0,NaN,20200.0,20200.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,1.0000,0.0000,0.0000,10081.0,2457.0,1.0000,1.0000,NaN,NaN,NaN,NaN,26043.0,0.5116,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
173,Design Institute of San Diego,1,1,San Diego,CA,11.0,3,3,3,0.6250,0.0000,0.0000,NaN,NaN,29477.0,NaN,20470.0,20470.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,18916.0,3227.0,NaN,NaN,NaN,NaN,NaN,NaN,23265.0,0.6667,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
174,The Art Institute of California-Argosy Univers...,0,1,San Diego,CA,11.0,3,3,3,0.6204,0.1875,0.1875,NaN,NaN,30521.0,NaN,18748.0,18748.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0687,0.1202,0.0000,0.0000,10708.0,3397.0,NaN,NaN,NaN,NaN,NaN,NaN,24859.0,0.4254,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
175,Kaplan College-San Diego,1,1,San Diego,CA,11.0,2,1,3,NaN,NaN,NaN,0.8357,NaN,NaN,27785.0,NaN,NaN,16249.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,12975.0,5044.0,NaN,NaN,NaN,NaN,NaN,NaN,24723.0,NaN,0.7868,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
176,Mueller College,1,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,0.4857,0.7228,34305.0,NaN,19152.0,19152.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,15180.0,4965.0,NaN,NaN,NaN,NaN,NaN,NaN,30702.0,NaN,0.9643,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
177,Newschool of Architecture and Design,1,1,San Diego,CA,11.0,4,3,3,0.5000,NaN,NaN,NaN,NaN,43957.0,NaN,24536.0,24536.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,19559.0,6617.0,0.7949,0.7949,NaN,NaN,NaN,NaN,35550.0,0.3500,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
178,Concorde Career College-San Diego,1,1,San Diego,CA,11.0,2,1,3,NaN,NaN,NaN,0.6919,NaN,NaN,25049.0,NaN,NaN,15244.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,6775.0,3761.0,1.0000,1.0000,NaN,NaN,NaN,NaN,20344.0,NaN,0.8956,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
179,Platt College-San Diego,1,1,San Diego,CA,11.0,3,2,3,NaN,NaN,NaN,NaN,NaN,40468.0,NaN,23250.0,23250.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0404,0.0359,0.0000,0.0000,14002.0,4131.0,NaN,NaN,NaN,NaN,NaN,NaN,35757.0,0.7273,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
180,Point Loma Nazarene University,1,1,San Diego,CA,11.0,4,3,2,0.8933,0.0000,0.0000,NaN,NaN,43060.0,NaN,30356.0,30356.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0071,0.0178,0.0000,18917.0,9224.0,0.6654,0.6654,23.0,28.0,1155.0,NaN,29865.0,0.7208,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
181,San Diego City College,1,1,San Diego,CA,11.0,2,2,1,NaN,NaN,NaN,0.6687,0.3857,12291.0,NaN,1142.0,5702.0,NaN,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0206,0.0062,0.0052,0.0547,648.0,4681.0,NaN,NaN,NaN,NaN,NaN,6054.0,NaN,NaN,0.1397,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
182,San Diego Mesa College,1,1,San Diego,CA,11.0,2,2,1,NaN,NaN,NaN,0.6646,0.3873,12796.0,NaN,1142.0,5702.0,NaN,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0076,0.0295,0.0030,0.0000,409.0,3956.0,NaN,NaN,NaN,NaN,NaN,6824.0,NaN,NaN,0.1967,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
183,San Diego Miramar College,1,1,San Diego,CA,11.0,2,2,1,NaN,NaN,NaN,0.6767,0.4047,11969.0,NaN,1142.0,5702.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0000,0.0103,0.0047,0.0009,490.0,4650.0,NaN,NaN,NaN,NaN,NaN,6109.0,NaN,NaN,0.3031,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
184,San Diego State University,1,1,San Diego,CA,11.0,4,3,1,0.8775,0.7548,0.7548,NaN,NaN,20252.0,NaN,6766.0,17926.0,NaN,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0000,0.0109,0.0605,0.0039,6601.0,6797.0,0.3121,0.3133,21.0,26.0,1084.0,11724.0,NaN,0.6616,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
185,University of San Diego,1,1,San Diego,CA,11.0,4,3,2,0.9021,1.0000,1.0000,NaN,NaN,56346.0,NaN,41392.0,41392.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0045,0.0397,0.0000,25057.0,13166.0,0.4885,0.4885,25.0,30.0,1228.0,NaN,31593.0,0.7502,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
186,Thomas Jefferson School of Law,1,1,San Diego,CA,11.0,4,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,42551.0,8236.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
187,Fashion Institute of Design & Merchandising-Sa...,0,1,San Diego,CA,11.0,2,2,3,NaN,NaN,NaN,0.6757,0.0000,38655.0,NaN,28920.0,28920.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,23284.0,10046.0,0.6059,0.5979,NaN,NaN,NaN,NaN,33181.0,NaN,0.6076,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
188,Bethel Seminary-San Diego,0,1,San Diego,CA,11.0,4,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,12221.0,7071.0,NaN,0.9485,NaN,NaN,1144.0,NaN,NaN,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
189,University of Phoenix-San Diego Campus,0,1,San Diego,CA,11.0,4,3,3,0.5049,NaN,NaN,NaN,NaN,24094.0,NaN,11275.0,11275.0,NaN,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0000,0.0905,0.0000,0.0000,13595.0,1974.0,NaN,NaN,NaN,NaN,NaN,NaN,19234.0,0.1730,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
190,Pacific College of Oriental Medicine-San Diego,1,1,San Diego,CA,11.0,4,1,3,NaN,NaN,NaN,NaN,NaN,24166.0,NaN,8088.0,8088.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,7421.0,2180.0,NaN,NaN,NaN,NaN,NaN,NaN,20946.0,0.5000,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
191,Avance Beauty College,1,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,0.9091,NaN,NaN,21368.0,NaN,NaN,14964.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,5690.0,3120.0,NaN,NaN,NaN,NaN,NaN,NaN,17474.0,NaN,0.7073,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
192,Paul Mitchell the School-San Diego,0,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,0.9333,0.8148,NaN,21047.0,NaN,NaN,18925.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,11734.0,3540.0,NaN,NaN,NaN,NaN,NaN,NaN,18212.0,NaN,0.7273,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
193,Argosy University-San Diego,0,1,San Diego,CA,11.0,4,3,3,0.6000,0.2381,0.2381,NaN,NaN,27325.0,NaN,13663.0,13663.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,9474.0,3004.0,NaN,NaN,NaN,NaN,NaN,NaN,22012.0,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
194,San Diego College,1,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,0.8489,NaN,NaN,38341.0,NaN,NaN,16283.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,7969.0,5078.0,NaN,NaN,NaN,NaN,NaN,NaN,35921.0,NaN,0.5848,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
195,International Professional School of Bodywork,1,1,San Diego,CA,11.0,2,1,3,NaN,NaN,NaN,NaN,0.5000,NaN,NaN,6659.0,6659.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,7149.0,2069.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2000,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
196,Horizon University,1,1,San Diego,CA,11.0,3,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9250.0,9250.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,3004.0,3801.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
197,San Diego Culinary Institute,1,1,San Diego,CA,21.0,1,1,3,NaN,NaN,NaN,0.9800,0.9667,NaN,30229.0,NaN,NaN,21660.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,17529.0,5505.0,1.0000,1.0000,NaN,NaN,NaN,NaN,26622.0,NaN,0.9167,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
198,Tramy Beauty School,1,1,San Diego,CA,11.0,1,1,3,NaN,NaN,NaN,0.8333,0.8333,NaN,19248.0,NaN,NaN,10106.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,1787.0,1885.0,NaN,NaN,NaN,NaN,NaN,NaN,14996.0,NaN,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951

In [85]:
final_df.shape

(179, 81)

Jane also wants a college/university offering a 2-year or 4-year degree in Information Technology/Science. courses related to Jane's required field of study are identified by CIP11[ASSOC, BACHL] columns. within this columns a value of 0 indicates that the courses in those categories are not offered at all, a value of 1 indicates the course is available and a value of 2 indicates that the course is available but only as a distance learning option. Since Jane wants to be physically attend a college/university and persue her field of study, we will discard all rows with a 0 and a 2 in the CIP11ASSOC, CIP11BACHL columns

In [86]:
final_df.drop(final_df[final_df['CIP11ASSOC'] != 1.0].index, inplace=True)
final_df.drop(final_df[final_df['CIP11BACHL'] != 1.0].index, inplace=True)

In [87]:
final_df.shape

(12, 81)

In [88]:
final_df

,INSTNM,main,CURROPER,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,OppShare_New_Entrp,Rate_New_Entrp,Location,Index Year,year_BDS,startup_density,Rank,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text,Ranking_Start_up,Total_Crime,Ranking_by_Crime_Rate
169,California College San Diego,1,1,San Diego,CA,11.0,3,2,2,0.2737,NaN,NaN,NaN,NaN,27138.0,NaN,18480.0,18480.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0907,0.0,0.0000,16010.0,3504.0,NaN,NaN,NaN,NaN,NaN,NaN,22956.0,0.5845,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
172,Coleman University,1,1,San Diego,CA,11.0,4,2,2,NaN,NaN,NaN,NaN,NaN,29842.0,NaN,20200.0,20200.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,1.0000,0.0,0.0000,10081.0,2457.0,1.0000,1.0000,NaN,NaN,NaN,NaN,26043.0,0.5116,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
174,The Art Institute of California-Argosy Univers...,0,1,San Diego,CA,11.0,3,3,3,0.6204,0.1875,0.1875,NaN,NaN,30521.0,NaN,18748.0,18748.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0687,0.1202,0.0,0.0000,10708.0,3397.0,NaN,NaN,NaN,NaN,NaN,NaN,24859.0,0.4254,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
179,Platt College-San Diego,1,1,San Diego,CA,11.0,3,2,3,NaN,NaN,NaN,NaN,NaN,40468.0,NaN,23250.0,23250.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0404,0.0359,0.0,0.0000,14002.0,4131.0,NaN,NaN,NaN,NaN,NaN,NaN,35757.0,0.7273,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951
731,The Art Institute of Houston,1,1,Houston,TX,11.0,3,3,3,0.4955,0.3962,0.3962,NaN,NaN,30536.0,NaN,17668.0,17668.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0394,0.1105,0.0,0.0158,15908.0,3102.0,NaN,NaN,NaN,NaN,NaN,NaN,26501.0,0.3900,NaN,"Houston-The Woodlands-Sugar Land, TX M.S.A.3",566.6,6.9,37.3,228.9,293.5,NaN,596.8,NaN,367.2,26420.0,2016.0,0.8193,0.0040,26420,2017.0,2014.0,92.559998,9.0,64.444443,50.597328,57.663353,4.587156,0.575420,-0.181348,6.0,-3.0,1.49,0.17,Metro Profile,Houston-Sugar Land-Baytown,MSA,8.193,400.0,the metropolitan area of,basically no changes,0.760633,NaN,NaN
739,ITT Technical Institute-Houston West,0,1,Houston,TX,11.0,3,2,3,NaN,NaN,NaN,NaN,NaN,26525.0,NaN,18048.0,18048.0,NaN,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0000,0.4146,0.0,0.4669,18715.0,2691.0,0.9368,0.8388,NaN,NaN,NaN,NaN,22146.0,0.5443,NaN,"Houston-The Woodlands-Sugar Land, TX M.S.A.3",566.6,6.9,37.3,228.9,293.5,NaN,596.8,NaN,367.2,26420.0,2016.0,0.8193,0.0040,26420,2017.0,2014.0,92.559998,9.0,64.444443,50.597328,57.663353,4.587156,0.575420,-0.181348,6.0,-3.0,1.49,0.17,Metro Profile,Houston-Sugar Land-Baytown,MSA,8.193,400.0,the metropolitan area of,basically no changes,0.760633,NaN,NaN
752,ITT Technical Institute-Houston North,0,1,Houston,TX,21.0,3,2,3,NaN,NaN,NaN,NaN,NaN,26516.0,NaN,18048.0,18048.0,NaN,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0000,0.2756,0.0,0.5385,20376.0,3300.0,0.9424,0.8388,NaN,NaN,NaN,NaN,22593.0,0.5844,NaN,"Houston-The Woodlands-Sugar Land, TX M.S.A.3",566.6,6.9,37.3,228.9,293.5,NaN,596.8,NaN,367.2,26420.0,2016.0,0.8193,0.0040,26420,2017.0,2014.0,92.559998,9.0,64.444443,50.597328,57.663353,4.587156,0.575420,-0.181348,6.0,-3.0,1.49,0.17,Metro Profile,Houston-Sugar Land-Baytown,MSA,8.193,400.0,the metropolitan area of,basically no changes,0.760633,NaN,NaN
778,American InterContinental University-Houston,0,1,Houston,TX,11.0,4,3,3,0.6000,0.5000,0.5000,NaN,NaN,24724.0,NaN,14675.0,14675.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0417,0.0,0.0000,15485.0,2889.0,NaN,NaN,NaN,NaN,NaN,NaN,19528.0,0.2759,NaN,"Houston-The Woodlands-Sugar Land, TX M.S.A.3",566.6,6.9,37.3,228.9,293.5,NaN,596.8,NaN,367.2,26420.0,2016.0,0.8193,0.0040,26420,2017.0,2014.0,92.559998,9.0,64.444443,50.597328,57.663353,4.587156,0.575420,-0.181348,6.0,-3.0,1.49,0.17,Metro Profile,Houston-Sugar Land-Baytown,MSA,8.193,400.0,the metropolitan area of,basically no changes,0.760633,NaN,NaN
814,ITT Technical Institute-Austin,0,1,Austin,TX,11.0,3,2,3,NaN,NaN,NaN,NaN,NaN,27074.0,NaN,18048.0,18048.0,NaN,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0000,0.3929,0.0,0.4133,20287.0,4086.0,0.9222,0.8388,NaN,NaN,NaN,NaN,23380.0,0.3958,NaN,"Austin-Round Rock, TX M.S.A.2",287.7,2.2,44.9,61.2,179.4,2672.8,415.7,2096.8,160.2,12420.0,2016.0,0.8473,0.0051,12420,2017.0,2014.0,104.540001,2.0,88.888886,60.435699,75.700089,9.633027,1.357543,0.853195,1.0,-1.0,4.90,-0.95,Metro Profile,Austin-Round Rock-San Marcos,MSA,8.473,510.0,the metropolitan area of,a slight decrease,0.904055,5920.9,0.436893
825,The Art Institute of Austin,0,1,Austin,TX,12.0,3,3,3,0.4845,0.3019,0.3019,NaN,NaN,31680.0,NaN,17668.0,17668.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.1317,0.2064,0.0,0.0000,14482.0,2789.0,NaN,NaN,NaN,NaN,NaN,NaN,27431.0,NaN,NaN,"Austin-Round Rock, TX M.S.A.2",287.7,2.2,44.9,61.2,179.4,2672.8,415.7,2096.8,160.2,12420.0,2016.0,0.8473,0.0051,12420,2017.0,2014.0,104.540001,2.0,88.888886,60.435699,75.700089,9.633027,1.357543,0.853195,1.0,-1.0,4.90,-0.95,Metro Profile,Austin-Round Rock-San Marcos,MSA,8.473,510.0,the metropolitan area of,a slight decrease,0.904055,5920.9,0.436893
831,South University-Austin,0,1,Austin,TX,41.0,4,3,3,0.4000,0.0000,0.0000,NaN,NaN,29061.0,NaN,16360.0,16360.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0000,0.0,0.0000,14779.0,8257.0,0.5000,0.4829,NaN,NaN,NaN,NaN,24977.0,NaN,NaN,"Austin-Round Rock, TX M.S.A.2",287.7,2.2,44.9,61.2,179.4,2672.8,415.7,2096.8,160.2,12420.0,2016.0,0.8473,0.0051,12420,2017.0,2014.0,104.540001,2.0,88.888886,60.435699,75.700089,9.633027,1.357543,0.853195,1.0,-1.0,4.90,-0.95,Metro Profile,Austin-Round Rock-San Marcos,MSA,8.473,510.0,the metropolitan area of,a slight decrease,0.904055,5920.9,0.436893
892,South University-The Art Institute of Dallas,0,1,Dallas,TX,11.0,4,3,3,0.4615,0.2857,0.2857,NaN,NaN,31013.0,NaN,17668.0,17668.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0917,0.0,0.0000,15210.0,4097.0,NaN,0.4829,NaN,NaN,NaN,NaN,26846.0,0.2656,NaN,"Dallas-Fort Worth-Arlington, TX M.S.A.2",337.6,4.0,41.3,112.4,179.8,2554.3,503.1,1792.5,258.7,19100.0,2016.0,0.8518,0.0037,19100,2017.0,2014.0,94.169998,11.0,57.777779,62.016865,60.087322,3.211009,1.483241,-0.042315,12.0,1.0,0.37,1.18,Metro Profile,Dallas-Fort Worth-Arlington,MSA,8.518,370.0,the metropolitan area of,a large increase,0.822453,5783.7,0.262136

In [89]:
final_df.isnull().sum()

INSTNM                     0
main                       0
CURROPER                   0
CITY                       0
STABBR                     0
LOCALE                     0
HIGHDEG                    0
PREDDEG                    0
CONTROL                    0
RET_FT4                    5
RET_PT4                    6
RET_PT4                    6
RET_FTL4                  12
RET_PTL4                  12
COSTT4_A                   0
COSTT4_P                  12
TUITIONFEE_IN              0
TUITIONFEE_OUT             0
TUITIONFEE_PROG           12
CIP10BACHL                 0
CIP11BACHL                 0
CIP14BACHL                 0
CIP15BACHL                 0
CIP10ASSOC                 0
CIP11ASSOC                 0
CIP14ASSOC                 0
CIP15ASSOC                 0
PCIP10                     0
PCIP11                     0
PCIP14                     0
PCIP15                     0
TUITFTE                    0
INEXPFTE                   0
ADM_RATE                   7
ADM_RATE_ALL               6
ACTCM25                   12
ACTCM75                   12
SAT_AVG_ALL               12
NPT4_PUB                  12
NPT4_PRIV                  0
C150_4                     2
C150_L4                   12
MSA                        0
ViolentCrime               0
Murder                     0
Rape                       0
Robbery                    0
AggravatedAssault          0
PropertyCrime              4
Burglary                   0
Theft                      4
MotorVehicleTheft          0
MSA_Code                   0
year_CPS                   0
OppShare_New_Entrp         0
Rate_New_Entrp             0
Location                   0
Index Year                 0
year_BDS                   0
startup_density            0
Rank                       0
norm_rate                  0
norm_opp                   0
norm_density               0
z_rate                     0
z_oppshare                 0
z_startup_den              0
rank_last_y                0
rank_diff                  0
index_last_y               0
index_diff                 0
dataset                    0
Location_name              0
Category                   0
OppShare_New_Entrp_web     0
Rate_New_Entrp_web         0
location_category          0
index_diff_text            0
Ranking_Start_up           0
Total_Crime                4
Ranking_by_Crime_Rate      4
dtype: int64

Finally, to get the college/university that meets all of Jane's requirements and is also relatively cheap as compared to other universities/colleges that meet Jane's requirements, we then rank the final dataframe based on tuition fee

In [90]:
# Ranking the final dataframe based on tuition fee
# ---
#

final_df['Rank_based_tuition_fee'] = final_df['TUITIONFEE_IN'].rank(ascending = 0)

final_df.head()

,INSTNM,main,CURROPER,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,OppShare_New_Entrp,Rate_New_Entrp,Location,Index Year,year_BDS,startup_density,Rank,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text,Ranking_Start_up,Total_Crime,Ranking_by_Crime_Rate,Rank_based_tuition_fee
169,California College San Diego,1,1,San Diego,CA,11.0,3,2,2,0.2737,NaN,NaN,NaN,NaN,27138.0,NaN,18480.0,18480.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,0.0907,0.0,0.0000,16010.0,3504.0,NaN,NaN,NaN,NaN,NaN,NaN,22956.0,0.5845,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951,4.0
172,Coleman University,1,1,San Diego,CA,11.0,4,2,2,NaN,NaN,NaN,NaN,NaN,29842.0,NaN,20200.0,20200.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,1.0000,0.0,0.0000,10081.0,2457.0,1.0,1.0,NaN,NaN,NaN,NaN,26043.0,0.5116,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951,2.0
174,The Art Institute of California-Argosy Univers...,0,1,San Diego,CA,11.0,3,3,3,0.6204,0.1875,0.1875,NaN,NaN,30521.0,NaN,18748.0,18748.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0687,0.1202,0.0,0.0000,10708.0,3397.0,NaN,NaN,NaN,NaN,NaN,NaN,24859.0,0.4254,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951,3.0
179,Platt College-San Diego,1,1,San Diego,CA,11.0,3,2,3,NaN,NaN,NaN,NaN,NaN,40468.0,NaN,23250.0,23250.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0404,0.0359,0.0,0.0000,14002.0,4131.0,NaN,NaN,NaN,NaN,NaN,NaN,35757.0,0.7273,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951,1.0
731,The Art Institute of Houston,1,1,Houston,TX,11.0,3,3,3,0.4955,0.3962,0.3962,NaN,NaN,30536.0,NaN,17668.0,17668.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0394,0.1105,0.0,0.0158,15908.0,3102.0,NaN,NaN,NaN,NaN,NaN,NaN,26501.0,0.3900,NaN,"Houston-The Woodlands-Sugar Land, TX M.S.A.3",566.6,6.9,37.3,228.9,293.5,NaN,596.8,NaN,367.2,26420.0,2016.0,0.8193,0.0040,26420,2017.0,2014.0,92.559998,9.0,64.444443,50.597328,57.663353,4.587156,0.575420,-0.181348,6.0,-3.0,1.49,0.17,Metro Profile,Houston-Sugar Land-Baytown,MSA,8.193,400.0,the metropolitan area of,basically no changes,0.760633,NaN,NaN,9.0

In [91]:
final_df['Rank_based_tuition_fee'].min()

1.0

In [92]:
# Select all records where the 'Rank_based_tuition_fee' is equal to 1, 2 and 3

final_list = final_df[(final_df['Rank_based_tuition_fee']) < 4]

#final_list['Rank_based_tuition_fee'].unique()

final_list

,INSTNM,main,CURROPER,CITY,STABBR,LOCALE,HIGHDEG,PREDDEG,CONTROL,RET_FT4,RET_PT4,RET_PT4,RET_FTL4,RET_PTL4,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,TUITIONFEE_PROG,CIP10BACHL,CIP11BACHL,CIP14BACHL,CIP15BACHL,CIP10ASSOC,CIP11ASSOC,CIP14ASSOC,CIP15ASSOC,PCIP10,PCIP11,PCIP14,PCIP15,TUITFTE,INEXPFTE,ADM_RATE,ADM_RATE_ALL,ACTCM25,ACTCM75,SAT_AVG_ALL,NPT4_PUB,NPT4_PRIV,C150_4,C150_L4,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,MSA_Code,year_CPS,OppShare_New_Entrp,Rate_New_Entrp,Location,Index Year,year_BDS,startup_density,Rank,norm_rate,norm_opp,norm_density,z_rate,z_oppshare,z_startup_den,rank_last_y,rank_diff,index_last_y,index_diff,dataset,Location_name,Category,OppShare_New_Entrp_web,Rate_New_Entrp_web,location_category,index_diff_text,Ranking_Start_up,Total_Crime,Ranking_by_Crime_Rate,Rank_based_tuition_fee
172,Coleman University,1,1,San Diego,CA,11.0,4,2,2,NaN,NaN,NaN,NaN,NaN,29842.0,NaN,20200.0,20200.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0000,1.0000,0.0,0.0,10081.0,2457.0,1.0,1.0,NaN,NaN,NaN,NaN,26043.0,0.5116,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951,2.0
174,The Art Institute of California-Argosy Univers...,0,1,San Diego,CA,11.0,3,3,3,0.6204,0.1875,0.1875,NaN,NaN,30521.0,NaN,18748.0,18748.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0687,0.1202,0.0,0.0,10708.0,3397.0,NaN,NaN,NaN,NaN,NaN,NaN,24859.0,0.4254,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951,3.0
179,Platt College-San Diego,1,1,San Diego,CA,11.0,3,2,3,NaN,NaN,NaN,NaN,NaN,40468.0,NaN,23250.0,23250.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0404,0.0359,0.0,0.0,14002.0,4131.0,NaN,NaN,NaN,NaN,NaN,NaN,35757.0,0.7273,NaN,"San Diego-Carlsbad, CA M.S.A.",331.8,2.5,33.3,84.9,211.1,1922.1,325.4,1296.6,300.0,41740.0,2016.0,0.8254,0.0049,41740,2017.0,2014.0,95.919998,4.0,84.444443,52.740688,62.722069,8.715596,0.745811,0.108808,11.0,7.0,0.46,2.73,Metro Profile,San Diego-Carlsbad-San Marcos,MSA,8.254,490.0,the metropolitan area of,a large increase,0.864985,4507.7,0.084951,1.0

### 3. Summary of Findings


Three Institutions were found to be of perfect match to Jane's preferences. The schools been; Coleman University, The Art Institute of California-Argosy University and Platt College-San Diego.The institutuions Offer both a 2-year and a 4-year degree in Information Technology/Science. With all of them located in San Diego City whose Kauffman's start-up ranking is 86.4985%  and has an overal crime rate of 8.4951%.